# Generated by Django 5.2.11 on 2026-03-24 21:08

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=150, verbose_name="Ім'я")),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='Email підтверджено')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('dietary_preferences', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('traditional', 'Традиційне (без жодних обмежень)'), ('vegetarian', 'Вегетаріанське'), ('vegan', 'Веганське'), ('pescatarian', 'Пескетаріанське'), ('gluten_free', 'Безглютенове'), ('lactose_free', 'Безлактозне'), ('sugar_free', 'Без цукру'), ('keto', 'Кето (Кетогенне)'), ('low_carb', 'Низьковуглеводне'), ('paleo', 'Палеодієта'), ('raw', 'Сироїдіння'), ('halal', 'Халяль'), ('kosher', 'Кошерне'), ('fasting', 'Пісне меню'), ('dietary', 'Дієтичне')], max_length=30), blank=True, null=True, size=None, verbose_name='Дієтичні обмеження')),
                ('favorite_cuisines', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('eu', '🇪🇺 Європейська кухня'), ('mediterranean', '🌊 Середземноморська кухня'), ('it', '🇮🇹 Італійська кухня'), ('mx', '🇲🇽 Мексиканська кухня'), ('intl', '🌍 Міжнародна кухня'), ('ua', '🇺🇦 Українська кухня'), ('fr', '🇫🇷 Французька кухня'), ('us', '🇺🇸 Американська кухня'), ('cn', '🇨🇳 Китайська кухня'), ('jp', '🇯🇵 Японська кухня')], max_length=50), blank=True, null=True, size=None, verbose_name='Улюблені кухні')),
                ('allergies', models.ManyToManyField(blank=True, to='recipes.ingredient', verbose_name='Алергії на інгредієнти')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Кількість')),
                ('unit', models.CharField(choices=[('g', 'Грам (г)'), ('kg', 'Кілограм (кг)'), ('ml', 'Мілілітр (мл)'), ('l', 'Літр (л)'), ('tsp', 'Чайна ложка (ч. л.)'), ('tbsp', 'Столова ложка (ст. л.)'), ('glass', 'Склянка (скл.)'), ('pcs', 'Штука (шт.)'), ('pack', 'Упаковка / Пачка (уп.)'), ('can', 'Банка'), ('leaf', 'Лист'), ('clove', 'Зубчик'), ('pinch', 'Дрібка'), ('bunch', 'Пучок'), ('sprig', 'Гілочка'), ('stalk', 'Стебло'), ('drop', 'Крапля'), ('cm', 'Сантиметр (см)'), ('taste', 'За смаком'), ('garnish', 'Для подачі / прикраси')], default='g', max_length=20, verbose_name='Одиниця виміру')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Додано у холодильник')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Останнє оновлення кількості')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient', verbose_name='Інгредієнт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Мій інгредієнт',
                'verbose_name_plural': 'Інвентар користувачів',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'ingredient')},
            },
        ),
    ]
