# Generated by Django 5.2.11 on 2026-03-28 10:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dietary_preferences',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('traditional', 'Традиційний (без обмежень)'), ('vegetarian', 'Вегетаріанський'), ('vegan', 'Веганський'), ('dietary', 'Дієтичний'), ('gluten_free', 'Безглютеновий'), ('lactose_free', 'Безлактозний'), ('sugar_free', 'Без цукру')], max_length=30), blank=True, null=True, size=None, verbose_name='Дієтичні обмеження'),
        ),
        migrations.AlterField(
            model_name='useringredient',
            name='unit',
            field=models.CharField(choices=[('g', 'Грам (г)'), ('kg', 'Кілограм (кг)'), ('ml', 'Мілілітр (мл)'), ('l', 'Літр (л)'), ('tsp', 'Чайна ложка (ч. л.)'), ('tbsp', 'Столова ложка (ст. л.)'), ('glass', 'Склянка (скл.)'), ('pcs', 'Штука (шт.)'), ('pack', 'Упаковка / Пачка (уп.)'), ('can', 'Банка'), ('leaf', 'Лист'), ('clove', 'Зубчик'), ('pinch', 'Дрібка'), ('bunch', 'Пучок'), ('sprig', 'Гілочка'), ('stalk', 'Стебло'), ('drop', 'Крапля'), ('cm', 'Сантиметр (см)'), ('taste', 'За смаком'), ('garnish', 'Для подачі / прикраси'), ('frying', 'Для смаження')], default='g', max_length=20, verbose_name='Одиниця виміру'),
        ),
    ]
