# Generated by Django 5.2.11 on 2026-03-28 11:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_dietary_preferences_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='favorite_cuisines',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('eu', '🇪🇺 Європейська кухня'), ('mediterranean', '🌊 Середземноморська кухня'), ('it', '🇮🇹 Італійська кухня'), ('mx', '🇲🇽 Мексиканська кухня'), ('intl', '🌍 Міжнародна кухня'), ('ua', '🇺🇦 Українська кухня'), ('fr', '🇫🇷 Французька кухня'), ('us', '🇺🇸 Американська кухня'), ('cn', '🇨🇳 Китайська кухня'), ('jp', '🇯🇵 Японська кухня'), ('asian', '🥢 Азійська кухня')], max_length=50), blank=True, null=True, size=None, verbose_name='Улюблені кухні'),
        ),
        migrations.AlterField(
            model_name='useringredient',
            name='unit',
            field=models.CharField(choices=[('g', 'Грам (г)'), ('kg', 'Кілограм (кг)'), ('ml', 'Мілілітр (мл)'), ('l', 'Літр (л)'), ('tsp', 'Чайна ложка (ч. л.)'), ('tbsp', 'Столова ложка (ст. л.)'), ('glass', 'Склянка (скл.)'), ('pcs', 'Штука (шт.)'), ('pack', 'Упаковка / Пачка (уп.)'), ('can', 'Банка'), ('leaf', 'Лист'), ('clove', 'Зубчик'), ('pinch', 'Дрібка'), ('bunch', 'Пучок'), ('sprig', 'Гілочка'), ('stalk', 'Стебло'), ('drop', 'Крапля'), ('cm', 'Сантиметр (см)'), ('taste', 'За смаком'), ('garnish', 'Для подачі / прикраси'), ('frying', 'Для смаження'), ('slice', 'Часточка')], default='g', max_length=20, verbose_name='Одиниця виміру'),
        ),
    ]
