# Generated by Django 5.2.11 on 2026-04-12 17:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_favorite_cuisines_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dietary_preferences',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('traditional', 'Традиційний (без обмежень)'), ('vegetarian', 'Вегетаріанський'), ('vegan', 'Веганський'), ('dietary', 'Дієтичний'), ('gluten_free', 'Безглютеновий'), ('lactose_free', 'Безлактозний'), ('sugar_free', 'Без цукру'), ('high_protein', 'Високобілковий'), ('meat_diet', 'М’ясний'), ('seafood_diet', 'Морський (Морепродукти)')], max_length=30), blank=True, null=True, size=None, verbose_name='Дієтичні обмеження'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='favorite_cuisines',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('eu', '🇪🇺 Європейська кухня'), ('mediterranean', '🌊 Середземноморська кухня'), ('it', '🇮🇹 Італійська кухня'), ('mx', '🇲🇽 Мексиканська кухня'), ('intl', '🌍 Міжнародна кухня'), ('ua', '🇺🇦 Українська кухня'), ('fr', '🇫🇷 Французька кухня'), ('us', '🇺🇸 Американська кухня'), ('cn', '🇨🇳 Китайська кухня'), ('jp', '🇯🇵 Японська кухня'), ('asian', '🥢 Азійська кухня'), ('gb', '🇬🇧 Британська кухня'), ('author', '👨\u200d🍳 Авторська кухня'), ('in', '🇮🇳 Індійська кухня')], max_length=50), blank=True, null=True, size=None, verbose_name='Улюблені кухні'),
        ),
    ]
