# Generated by Django 5.2.11 on 2026-04-18 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_dietary_preferences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ban_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина блокування'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='banned_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Заблокований до'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='Заблокований'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Остання активність'),
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адреса')),
                ('os', models.CharField(blank=True, max_length=50, null=True, verbose_name='Операційна система')),
                ('browser', models.CharField(blank=True, max_length=50, null=True, verbose_name='Браузер')),
                ('device_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип пристрою')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Країна')),
                ('last_endpoint', models.CharField(blank=True, max_length=255, null=True, verbose_name='Остання дія (URL)')),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='Перший вхід')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Остання активність тут')),
                ('is_active_session', models.BooleanField(default=True, verbose_name='Токен активний')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сесія користувача',
                'verbose_name_plural': 'Сесії користувачів',
                'ordering': ['-last_seen'],
            },
        ),
    ]
