# Generated by Django 5.2.11 on 2026-04-23 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_ban_reason_customuser_banned_until_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnverifiedUser',
            fields=[
            ],
            options={
                'verbose_name': 'Непідтверджений користувач',
                'verbose_name_plural': 'Непідтверджені користувачі',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.customuser',),
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(max_length=128, verbose_name='Хеш пароля')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата зміни')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Історія пароля',
                'verbose_name_plural': 'Історії паролів',
                'ordering': ['-created_at'],
            },
        ),
    ]
