# Generated by Django 5.2.11 on 2026-04-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_is_ai_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='ai_provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('aws', 'Amazon AWS (Bedrock)')], default='gemini', max_length=20, verbose_name='Провайдер ШІ'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gemini_model',
            field=models.CharField(choices=[('models/gemma-3-27b-it', 'Gemma 3 27B'), ('models/gemma-3-12b-it', 'Gemma 3 12B'), ('models/gemma-3-2b-it', 'Gemma 3 2B'), ('models/gemma-3-4b-it', 'Gemma 3 4B'), ('models/gemma-4-31b-it', 'Gemma 4 31B'), ('models/gemma-4-26b-it', 'Gemma 4 26B'), ('models/gemma-2-27b-it', 'Gemma 2 27B')], default='models/gemma-3-12b-it', max_length=50, verbose_name='Модель Gemini'),
        ),
    ]
