# Generated by Django 5.2.11 on 2026-04-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_sitesettings_ai_provider_sitesettings_gemini_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Налаштування ШІ-асистента', 'verbose_name_plural': 'Налаштування ШІ-асистента'},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gemini_api_key_choice',
            field=models.CharField(choices=[('primary', 'Основний ключ (GEMINI_API_KEY)'), ('secondary', 'Додатковий ключ (GEMINI_API_KEY_1)')], default='primary', max_length=20, verbose_name='Ключ API для Gemini'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='gemini_model',
            field=models.CharField(choices=[('models/gemini-2.5-pro', '⭐️ НАЙКРАЩА: Gemini 2.5 Pro (Найрозумніша, для складних задач)'), ('models/gemini-2.5-flash', '⚡️ ОПТИМАЛЬНА: Gemini 2.5 Flash (Дуже швидка, ідеальний баланс)'), ('models/gemini-2.5-flash-lite', '🏃 БАЗОВА: Gemini 2.5 Flash Lite (Найдешевша, для простих діалогів)'), ('models/gemma-3-27b-it', '🧠 Gemma 3 27B (Найпотужніша з Gemma)'), ('models/gemma-3-12b-it', '⚖️ Gemma 3 12B (Середня, збалансована Gemma)'), ('models/gemma-3-4b-it', '📱 Gemma 3 4B (Легка Gemma)'), ('models/gemma-3-2b-it', '🪶 Gemma 3 2B (Мікро-модель Gemma)'), ('models/gemma-4-31b-it', '💪 Gemma 4 31B (Експериментальна велика)'), ('models/gemma-4-26b-it', '🛠 Gemma 4 26B (Експериментальна середня)'), ('models/gemma-2-27b-it', '📦 Gemma 2 27B (Стабільна попередня версія)')], default='models/gemini-2.5-flash', max_length=50, verbose_name='Модель Gemini'),
        ),
    ]
