# Generated by Django 5.2.11 on 2026-04-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_sitesettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ai_provider_override',
            field=models.CharField(blank=True, choices=[('gemini', 'Google Gemini'), ('aws', 'Amazon AWS (Bedrock)')], max_length=20, null=True, verbose_name='Індивідуальний Провайдер ШІ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gemini_api_key_override',
            field=models.CharField(blank=True, choices=[('primary', 'Основний ключ (GEMINI_API_KEY)'), ('secondary', 'Додатковий ключ (GEMINI_API_KEY_1)')], max_length=20, null=True, verbose_name='Індивідуальний Ключ API'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gemini_model_override',
            field=models.CharField(blank=True, choices=[('models/gemini-2.5-pro', '⭐️ НАЙКРАЩА: Gemini 2.5 Pro (Найрозумніша, для складних задач)'), ('models/gemini-2.5-flash', '⚡️ ОПТИМАЛЬНА: Gemini 2.5 Flash (Дуже швидка, ідеальний баланс)'), ('models/gemini-2.5-flash-lite', '🏃 БАЗОВА: Gemini 2.5 Flash Lite (Найдешевша, для простих діалогів)'), ('models/gemma-3-27b-it', '🧠 Gemma 3 27B (Найпотужніша з Gemma)'), ('models/gemma-3-12b-it', '⚖️ Gemma 3 12B (Середня, збалансована Gemma)'), ('models/gemma-3-4b-it', '📱 Gemma 3 4B (Легка Gemma)'), ('models/gemma-3-2b-it', '🪶 Gemma 3 2B (Мікро-модель Gemma)'), ('models/gemma-4-31b-it', '💪 Gemma 4 31B (Експериментальна велика)'), ('models/gemma-4-26b-it', '🛠 Gemma 4 26B (Експериментальна середня)'), ('models/gemma-2-27b-it', '📦 Gemma 2 27B (Стабільна попередня версія)')], max_length=50, null=True, verbose_name='Індивідуальна Модель Gemini'),
        ),
    ]
