# Generated by Django 5.2.11 on 2026-05-03 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser_ai_provider_override_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User (Користувач)', 'verbose_name_plural': 'Users (Користувачі)'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'AI Settings (Налаштування ШІ)', 'verbose_name_plural': 'AI Settings (Налаштування ШІ)'},
        ),
        migrations.AlterModelOptions(
            name='unverifieduser',
            options={'verbose_name': 'Unverified User (Непідтверджений)', 'verbose_name_plural': 'Unverified Users (Непідтверджені)'},
        ),
    ]
