import os
import django
from django.core.files import File
from django.core.files.storage import default_storage
from django.utils.text import slugify
from unidecode import unidecode

# Налаштування середовища Django для запуску скрипта
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'core.settings')
django.setup()

from recipes.models.recipe import Recipe, RecipeIngredient, RecipeStep, Difficulty, MealTime, Diet, DishType, Cuisine, UnitChoice
from recipes.models.ingredient import Ingredient

# Формат даних для рецептів
RECIPES_DATA = [
    {
        "title": "Вівсянка з ягодами та горіхами",
        "title_en": "Oatmeal with berries and nuts",
        "title_pl": "Owsianka z jagodami i orzechami",
        "description": "Смачний і поживний сніданок, який заряджає енергією на весь день. Поєднання ніжної вівсянки, свіжих ягід і хрустких горіхів робить страву не тільки корисною, а й дуже апетитною.",
        "description_en": "A delicious and nutritious breakfast that energizes you for the whole day. The combination of tender oatmeal, fresh berries, and crunchy nuts makes the dish not only healthy but also very appetizing.",
        "description_pl": "Pyszne i pożywne śniadanie, które dodaje energii na cały dzień. Połączenie delikatnej owsianki, świeżych jagód i chrupiących orzechów sprawia, że danie jest nie tylko zdrowe, ale i bardzo apetyczne.",
        "source": "Шеф-кухар SoulFood Lab Андрій Коваль",
        "source_en": "Chef of SoulFood Lab Andriy Koval",
        "source_pl": "Szef kuchni SoulFood Lab Andrij Kowal",
        "cooking_time": 10,
        "portions": 1,
        "calories": 320,
        "difficulty": Difficulty.EASY,
        "cuisine": [Cuisine.EUROPEAN],
        "meal_times": [MealTime.BREAKFAST],
        "dietary_tags": [Diet.VEGETARIAN],
        "dish_types": [DishType.PORRIDGE],
        "ingredients": [
            ("Вівсяні пластівці", 80, UnitChoice.G),
            ("Мигдальне молоко", 200, UnitChoice.ML),
            ("Полуниця", 50, UnitChoice.G),
            ("Чорниця", 50, UnitChoice.G),
            ("Мед", 1, UnitChoice.TSP),
            ("Волоський горіх", 20, UnitChoice.G),
        ],
        "steps": [
            {"uk": "Влийте мигдальне молоко в каструлю та доведіть до кипіння на середньому вогні.",
             "en": "Pour almond milk into a saucepan and bring to a boil over medium heat.",
             "pl": "Wlej mleko migdałowe do rondla i zagotuj na średnim ogniu."},
            {
                "uk": "Додайте вівсяні пластівці, перемішайте та варіть приблизно 5 хвилин до м’якої, кремової консистенції.",
                "en": "Add oatmeal, stir and cook for about 5 minutes until soft and creamy.",
                "pl": "Dodaj płatki owsiane, wymieszaj i gotuj około 5 minut, aż staną się miękkie i kremowe."},
            {"uk": "Тим часом промийте ягоди, а волоські горіхи злегка подрібніть.",
             "en": "Meanwhile, wash the berries and lightly chop the walnuts.",
             "pl": "W międzyczasie umyj jagody i lekko posiekaj orzechy włoskie."},
            {"uk": "Перекладіть готову вівсянку в тарілку, зверху додайте ягоди, горіхи та полийте медом.",
             "en": "Transfer the finished oatmeal to a plate, top with berries, nuts and drizzle with honey.",
             "pl": "Gotową owsiankę przełóż na talerz, ułóż na wierzchu jagody, orzechy i polej miodem."}
        ]
    },
    {
        "title": "Запечені овочі з травами",
        "title_en": "Baked vegetables with herbs",
        "title_pl": "Pieczone warzywa z ziołami",
        "description": "Ароматна страва з сезонних овочів, запечених із пряними травами та оливковою олією. Легка, корисна та насичена смаком.",
        "description_en": "A fragrant dish of seasonal vegetables baked with spicy herbs and olive oil. Light, healthy, and full of flavor.",
        "description_pl": "Aromatyczne danie z sezonowych warzyw zapiekanych z ostrymi ziołami i oliwą z oliwek. Lekkie, zdrowe i pełne smaku.",
        "source": "Шеф-кухар SoulFood Lab Андрій Коваль",
        "source_en": "Chef of SoulFood Lab Andriy Koval",
        "source_pl": "Szef kuchni SoulFood Lab Andrij Kowal",
        "cooking_time": 30,
        "portions": 2,
        "calories": 150,
        "difficulty": Difficulty.EASY,
        "cuisine": [Cuisine.MEDITERRANEAN],
        "meal_times": [MealTime.LUNCH, MealTime.DINNER],
        "dietary_tags": [Diet.VEGAN],
        "dish_types": [DishType.GARNISH],
        "ingredients": [
            ("Кабачок", 300, UnitChoice.G),
            ("Перець болгарський", 150, UnitChoice.G),
            ("Морква", 100, UnitChoice.G),
            ("Броколі", 100, UnitChoice.G),
            ("Оливкова олія", 2, UnitChoice.TBSP),
            ("Часник", 2, UnitChoice.CLOVE),
            ("Орегано", 1, UnitChoice.TSP),
            ("Сіль", None, UnitChoice.TASTE),
            ("Перець чорний", None, UnitChoice.TASTE),
        ],
        "steps": [
            {"uk": "Розігрійте духовку до 180°C.", "en": "Preheat the oven to 180°C.",
             "pl": "Rozgrzej piekarnik do 180°C."},
            {
                "uk": "Помийте овочі. Кабачок, перець і моркву наріжте великими рівномірними шматками, броколі розділіть на суцвіття.",
                "en": "Wash the vegetables. Cut the zucchini, pepper, and carrot into large even pieces, divide the broccoli into florets.",
                "pl": "Umyj warzywa. Cukinię, paprykę i marchew pokrój na duże, równe kawałki, podziel brokuły na różyczki."},
            {"uk": "Очистіть часник і дрібно подрібніть або розчавіть ножем.",
             "en": "Peel the garlic and finely chop or crush it with a knife.",
             "pl": "Obrany czosnek drobno posiekaj lub rozgnieć nożem."},
            {"uk": "Викладіть овочі на деко в один шар, додайте часник.",
             "en": "Place the vegetables on a baking sheet in one layer, add the garlic.",
             "pl": "Ułóż warzywa na blasze do pieczenia w jednej warstwie, dodaj czosnek."},
            {"uk": "Полийте оливковою олією, посипте орегано, сіллю та чорним перцем, добре перемішайте.",
             "en": "Drizzle with olive oil, sprinkle with oregano, salt and black pepper, mix well.",
             "pl": "Skrop oliwą z oliwek, posyp oregano, solą i czarnym pieprzem, dobrze wymieszaj."},
            {"uk": "Запікайте 20–25 хвилин до м’якості та легкої рум’яної скоринки.",
             "en": "Bake for 20-25 minutes until soft and lightly browned.",
             "pl": "Piecz 20-25 minut, aż będą miękkie i lekko zrumienione."}
        ]
    },
    {
        "title": "Куряче філе з лимоном та зеленню",
        "title_en": "Chicken fillet with lemon and herbs",
        "title_pl": "Filet z kurczaka z cytryną i ziołami",
        "description": "Соковите куряче філе з ніжним цитрусовим ароматом і свіжою зеленню. Легка у приготуванні страва, яка чудово підходить для обіду або вечері.",
        "description_en": "Juicy chicken fillet with a delicate citrus aroma and fresh herbs. An easy-to-prepare dish that is perfect for lunch or dinner.",
        "description_pl": "Soczysty filet z kurczaka z delikatnym cytrusowym aromatem i świeżymi ziołami. Łatwe w przygotowaniu danie, idealne na obiad lub kolację.",
        "source": "Шеф-кухар SoulFood Lab Андрій Коваль",
        "source_en": "Chef of SoulFood Lab Andriy Koval",
        "source_pl": "Szef kuchni SoulFood Lab Andrij Kowal",
        "cooking_time": 30,
        "portions": 2,
        "calories": 280,
        "difficulty": Difficulty.EASY,
        "cuisine": [Cuisine.EUROPEAN],
        "meal_times": [MealTime.LUNCH, MealTime.DINNER],
        "dietary_tags": [Diet.DIETARY],
        "dish_types": [DishType.MAIN, DishType.MEAT],
        "ingredients": [
            ("Куряче філе", 400, UnitChoice.G),
            ("Лимон", 1, UnitChoice.PCS),
            ("Оливкова олія", 2, UnitChoice.TBSP),
            ("Часник", 2, UnitChoice.CLOVE),
            ("Петрушка", 10, UnitChoice.G),
            ("Сіль", None, UnitChoice.TASTE),
            ("Перець чорний", None, UnitChoice.TASTE),
        ],
        "steps": [
            {"uk": "Промийте куряче філе. Лимон розріжте навпіл і вичавіть сік, подрібніть часник.",
             "en": "Wash the chicken fillet. Cut the lemon in half and squeeze the juice, chop the garlic.",
             "pl": "Umyj filet z kurczaka. Przekrój cytrynę na pół i wyciśnij sok, posiekaj czosnek."},
            {
                "uk": "Натріть куряче філе сіллю та чорним перцем з обох боків, залиште на 5 хвилин для легкого маринування.",
                "en": "Rub the chicken fillet with salt and black pepper on both sides, leave for 5 minutes to lightly marinate.",
                "pl": "Natrzyj filet solą i pieprzem z obu stron, odstaw na 5 minut, aby lekko się zamarynował."},
            {"uk": "У невеликій мисці змішайте оливкову олію, лимонний сік і подрібнений часник до однорідності.",
             "en": "In a small bowl, mix olive oil, lemon juice and minced garlic until smooth.",
             "pl": "W małej misce wymieszaj oliwę z oliwek, sok z cytryny i mielony czosnek do uzyskania gładkiej masy."},
            {"uk": "Викладіть куряче філе у форму для запікання та рівномірно полийте підготовленим маринадом.",
             "en": "Place the chicken fillet in a baking dish and pour the prepared marinade evenly over it.",
             "pl": "Umieść filet w naczyniu do pieczenia i równomiernie zalej przygotowaną marynatą."},
            {"uk": "Запікайте у розігрітій до 180°C духовці протягом 20–25 хвилин до готовності та рум’яної скоринки.",
             "en": "Bake in a preheated 180°C oven for 20-25 minutes until done and golden brown.",
             "pl": "Piecz w nagrzanym do 180°C piekarniku przez 20-25 minut, aż do upieczenia i zarumienienia."},
            {"uk": "Додайте дрібно нарізану петрушку після завершення приготування.",
             "en": "Add finely chopped parsley after cooking.",
             "pl": "Po ugotowaniu dodaj drobno posiekaną pietruszkę."}
        ]
    },
    {
        "title": "Салат з кіноа, авокадо та овочами",
        "title_en": "Quinoa salad with avocado and vegetables",
        "title_pl": "Sałatka z komosy ryżowej, awokado i warzyw",
        "description": "Свіжий і поживний салат із кіноа та овочів, який поєднує користь і насичений смак. Легкий, але ситний варіант для обіду або вечері.",
        "description_en": "A fresh and nutritious salad with quinoa and vegetables, combining health and rich taste. A light but satisfying option for lunch or dinner.",
        "description_pl": "Świeża i pożywna sałatka z komosą ryżową i warzywami, łącząca zdrowie i bogaty smak. Lekka, ale sycąca opcja na obiad lub kolację.",
        "source": "Шеф-кухар SoulFood Lab Андрій Коваль",
        "source_en": "Chef of SoulFood Lab Andriy Koval",
        "source_pl": "Szef kuchni SoulFood Lab Andrij Kowal",
        "cooking_time": 20,
        "portions": 2,
        "calories": 340,
        "difficulty": Difficulty.EASY,
        "cuisine": [Cuisine.MEDITERRANEAN],
        "meal_times": [MealTime.LUNCH, MealTime.DINNER],
        "dietary_tags": [Diet.VEGAN],
        "dish_types": [DishType.SALAD],
        "ingredients": [
            ("Кіноа", 100, UnitChoice.G),
            ("Авокадо", 1, UnitChoice.PCS),
            ("Огірок", 100, UnitChoice.G),
            ("Помідори чері", 100, UnitChoice.G),
            ("Листя салату", 50, UnitChoice.G),
            ("Оливкова олія", 2, UnitChoice.TBSP),
            ("Лимонний сік", 1, UnitChoice.TBSP),
            ("Сіль", None, UnitChoice.TASTE),
            ("Перець чорний", None, UnitChoice.TASTE),
        ],
        "steps": [
            {
                "uk": "Промийте кіноа під проточною водою. Відваріть у підсоленій воді у співвідношенні 1:2 приблизно 12–15 хвилин до готовності. Дайте охолонути.",
                "en": "Rinse the quinoa under running water. Boil in salted water in a 1:2 ratio for about 12-15 minutes until done. Let it cool.",
                "pl": "Opłucz komosę pod bieżącą wodą. Gotuj w osolonej wodzie w proporcji 1:2 przez około 12-15 minut. Pozostaw do ostygnięcia."},
            {
                "uk": "Підготуйте овочі: огірок наріжте кубиками, помідори чері розріжте навпіл, авокадо очистіть і наріжте скибками або кубиками.",
                "en": "Prepare the vegetables: dice the cucumber, cut the cherry tomatoes in half, peel the avocado and cut into slices or cubes.",
                "pl": "Przygotuj warzywa: ogórek pokrój w kostkę, pomidorki koktajlowe przekrój na pół, awokado obierz i pokrój w plasterki lub kostkę."},
            {"uk": "Листя салату промийте, обсушіть та порвіть руками на середні шматочки.",
             "en": "Wash the lettuce leaves, dry them and tear them by hand into medium pieces.",
             "pl": "Umyj liście sałaty, osusz i porwij rękami na średnie kawałki."},
            {"uk": "У великій мисці перемішайте охолоджену кіноа, підготовлені овочі та листя салату.",
             "en": "In a large bowl, mix the cooled quinoa, prepared vegetables, and lettuce leaves.",
             "pl": "W dużej misce wymieszaj ostudzoną komosę, przygotowane warzywa i liście sałaty."},
            {"uk": "Приготуйте заправку: змішайте оливкову олію, лимонний сік, сіль та чорний перець до однорідності.",
             "en": "Prepare the dressing: mix olive oil, lemon juice, salt, and black pepper until smooth.",
             "pl": "Przygotuj sos: wymieszaj oliwę z oliwek, sok z cytryny, sól i pieprz na gładką masę."},
            {"uk": "Додайте заправку до салату та обережно перемішайте, щоб не пошкодити структуру авокадо.",
             "en": "Add the dressing to the salad and gently toss to avoid mashing the avocado.",
             "pl": "Dodaj sos do sałatki i delikatnie wymieszaj, aby nie uszkodzić awokado."}
        ]
    },
    {
        "title": "Смузі з бананом та шпинатом",
        "title_en": "Banana and spinach smoothie",
        "title_pl": "Smoothie z bananem i szpinakiem",
        "description": "Освіжаючий і корисний напій, який поєднує солодкість банана та користь зелені. Ідеальний варіант для швидкого сніданку.",
        "description_en": "A refreshing and healthy drink that combines the sweetness of banana and the benefits of greens. Perfect for a quick breakfast.",
        "description_pl": "Orzeźwiający i zdrowy napój, który łączy w sobie słodycz banana i korzyści płynące z zieleni. Idealny na szybkie śniadanie.",
        "source": "Шеф-кухар SoulFood Lab Андрій Коваль",
        "source_en": "Chef of SoulFood Lab Andriy Koval",
        "source_pl": "Szef kuchni SoulFood Lab Andrij Kowal",
        "cooking_time": 5,
        "portions": 1,
        "calories": 190,
        "difficulty": Difficulty.EASY,
        "cuisine": [Cuisine.INTERNATIONAL],
        "meal_times": [MealTime.BREAKFAST, MealTime.SNACK],
        "dietary_tags": [Diet.VEGETARIAN],
        "dish_types": [DishType.SMOOTHIE, DishType.DRINK],
        "ingredients": [
            ("Банан", 1, UnitChoice.PCS),
            ("Шпинат", 50, UnitChoice.G),
            ("Мигдальне молоко", 200, UnitChoice.ML),
            ("Насіння чіа", 1, UnitChoice.TSP),
            ("Мед", 1, UnitChoice.TSP),
        ],
        "steps": [
            {"uk": "Очистіть банан, промийте шпинат під холодною водою та злегка обсушіть.",
             "en": "Peel the banana, wash the spinach under cold water and pat dry.",
             "pl": "Obierz banana, umyj szpinak pod zimną wodą i osusz."},
            {"uk": "У чашу блендера додайте банан, шпинат, мигдальне молоко, насіння чіа та мед.",
             "en": "In a blender, add the banana, spinach, almond milk, chia seeds, and honey.",
             "pl": "Do blendera włóż banana, szpinak, mleko migdałowe, nasiona chia i miód."},
            {
                "uk": "Збивайте на високій швидкості 30–60 секунд до отримання повністю однорідної, кремової консистенції.",
                "en": "Blend on high for 30-60 seconds until completely smooth and creamy.",
                "pl": "Miksuj na wysokich obrotach przez 30-60 sekund do uzyskania gładkiej i kremowej konsystencji."},
            {"uk": "Перелийте смузі у склянку", "en": "Pour the smoothie into a glass",
             "pl": "Przelej smoothie do szklanki"}
        ]
    },
    {
        "title": "Томатний суп з базиліком",
        "title_en": "Tomato soup with basil",
        "title_pl": "Zupa pomidorowa z bazylią",
        "description": "Легкий і ароматний суп із насиченим томатним смаком та свіжим базиліком. Чудовий варіант для обіду.",
        "description_en": "A light and aromatic soup with a rich tomato flavor and fresh basil. A great option for lunch.",
        "description_pl": "Lekka i aromatyczna zupa o bogatym smaku pomidorów i świeżej bazylii. Świetna propozycja na obiad.",
        "source": "Шеф-кухар SoulFood Lab Андрій Коваль",
        "source_en": "Chef of SoulFood Lab Andriy Koval",
        "source_pl": "Szef kuchni SoulFood Lab Andrij Kowal",
        "cooking_time": 25,
        "portions": 2,
        "calories": 120,
        "difficulty": Difficulty.EASY,
        "cuisine": [Cuisine.ITALIAN],
        "meal_times": [MealTime.LUNCH],
        "dietary_tags": [Diet.VEGAN],
        "dish_types": [DishType.SOUP],
        "ingredients": [
            ("Помідор", 400, UnitChoice.G),
            ("Цибуля ріпчаста", 100, UnitChoice.G),
            ("Часник", 2, UnitChoice.CLOVE),
            ("Базилік", 10, UnitChoice.G),
            ("Оливкова олія", 1, UnitChoice.TBSP),
            ("Овочевий бульйон", 400, UnitChoice.ML),
            ("Сіль", None, UnitChoice.TASTE),
            ("Перець чорний", None, UnitChoice.TASTE),
        ],
        "steps": [
            {"uk": "Цибулю дрібно наріжте, часник подрібніть, помідори наріжте кубиками або часточками.",
             "en": "Finely chop the onion, mince the garlic, and dice or slice the tomatoes.",
             "pl": "Cebulę drobno posiekaj, czosnek przeciśnij przez praskę, a pomidory pokrój w kostkę lub w plasterki."},
            {
                "uk": "Розігрійте оливкову олію у каструлі та обсмажте цибулю до прозорості (2–3 хвилини). Додайте часник і готуйте ще 30–60 секунд до появи аромату.",
                "en": "Heat olive oil in a saucepan and sauté the onion until translucent (2-3 minutes). Add garlic and cook for another 30-60 seconds until fragrant.",
                "pl": "Rozgrzej oliwę w rondlu i smaż cebulę, aż będzie szklista (2-3 minuty). Dodaj czosnek i smaż jeszcze 30-60 sekund."},
            {"uk": "Додайте нарізані помідори та тушкуйте 5–7 хвилин, щоб вони почали розм’якшуватися та виділяти сік.",
             "en": "Add the chopped tomatoes and simmer for 5-7 minutes until they begin to soften and release their juices.",
             "pl": "Dodaj posiekane pomidory i duś przez 5-7 minut, aż zmiękną i puszczą sok."},
            {
                "uk": "Влийте овочевий бульйон, доведіть до кипіння та варіть суп на середньому вогні приблизно 10 хвилин.",
                "en": "Pour in the vegetable broth, bring to a boil, and cook the soup over medium heat for about 10 minutes.",
                "pl": "Wlej bulion warzywny, doprowadź do wrzenia i gotuj zupę na średnim ogniu przez około 10 minut."},
            {"uk": "Зніміть з вогню та подрібніть суп блендером до однорідної кремової консистенції (за бажанням).",
             "en": "Remove from heat and blend the soup until smooth and creamy (optional).",
             "pl": "Zdejmij z ognia i zblenduj zupę na gładką, kremową konsystencję (opcjonalnie)."},
            {"uk": "Приправте сіллю та чорним перцем за смаком, додайте свіжий подрібнений базилік.",
             "en": "Season with salt and black pepper to taste, and add freshly chopped basil.",
             "pl": "Dopraw solą i czarnym pieprzem do smaku, dodaj świeżo posiekaną bazylię."}
        ]
    },
    {
        "title": "Паста з грибами та часником",
        "title_en": "Pasta with mushrooms and garlic",
        "title_pl": "Makaron z grzybami i czosnkiem",
        "description": "Ніжна паста з ароматними грибами та часником — проста, але дуже смачна страва. Ідеально підходить для швидкого обіду або вечері з італійським настроєм.",
        "description_en": "Tender pasta with fragrant mushrooms and garlic is a simple but very tasty dish. Perfect for a quick lunch or dinner with an Italian mood.",
        "description_pl": "Delikatny makaron z pachnącymi grzybami i czosnkiem – to proste, ale bardzo smaczne danie. Idealne na szybki lunch lub kolację w włoskim klimacie.",
        "source": "Шеф-кухар SoulFood Lab Андрій Коваль",
        "source_en": "Chef of SoulFood Lab Andriy Koval",
        "source_pl": "Szef kuchni SoulFood Lab Andrij Kowal",
        "cooking_time": 25,
        "portions": 2,
        "calories": 480,
        "difficulty": Difficulty.EASY,
        "cuisine": [Cuisine.ITALIAN],
        "meal_times": [MealTime.LUNCH, MealTime.DINNER],
        "dietary_tags": [Diet.VEGETARIAN],
        "dish_types": [DishType.PASTA, DishType.FLOUR],
        "ingredients": [
            ("Паста", 150, UnitChoice.G),
            ("Печериці", 200, UnitChoice.G),
            ("Часник", 2, UnitChoice.CLOVE),
            ("Оливкова олія", 2, UnitChoice.TBSP),
            ("Петрушка", 10, UnitChoice.G),
            ("Сіль", None, UnitChoice.TASTE),
            ("Перець чорний", None, UnitChoice.TASTE),
        ],
        "steps": [
            {
                "uk": "Відваріть пасту у великій кількості підсоленої води до готовності. Злийте воду, залишивши трохи рідини для соусу.",
                "en": "Boil the pasta in plenty of salted water until done. Drain, reserving a little of the cooking water for the sauce.",
                "pl": "Ugotuj makaron w dużej ilości osolonej wody. Odcedź, zachowując trochę wody z gotowania do sosu."},
            {
                "uk": "Підготуйте інгредієнти: печериці очистіть та наріжте скибками, часник подрібніть, петрушку покришіть.",
                "en": "Prepare the ingredients: clean the mushrooms and slice them, mince the garlic, chop the parsley.",
                "pl": "Przygotuj składniki: oczyść pieczarki i pokrój w plasterki, posiekaj czosnek i natkę pietruszki."},
            {"uk": "На сковороді розігрійте оливкову олію та обсмажте часник до появи аромату (30–60 секунд).",
             "en": "Heat olive oil in a pan and sauté the garlic until fragrant (30-60 seconds).",
             "pl": "Rozgrzej oliwę na patelni i podsmaż czosnek, aż zacznie pachnieć (30-60 sekund)."},
            {
                "uk": "Додайте гриби та готуйте на середньому вогні 5–7 хвилин, поки вони не зменшаться в об’ємі та не підрум’яняться.",
                "en": "Add the mushrooms and cook over medium heat for 5-7 minutes until they reduce in volume and brown slightly.",
                "pl": "Dodaj grzyby i smaż na średnim ogniu przez 5-7 minut, aż zmniejszą objętość i lekko się zarumienią."},
            {
                "uk": "Додайте відварену пасту до грибів, перемішайте та за потреби додайте трохи води від варіння для створення легкого соусу.",
                "en": "Add the cooked pasta to the mushrooms, mix, and if necessary, add a little cooking water to create a light sauce.",
                "pl": "Dodaj ugotowany makaron do grzybów, wymieszaj i w razie potrzeby dodaj odrobinę wody z gotowania, aby uzyskać lekki sos."},
            {"uk": "Приправте сіллю та чорним перцем, додайте покришену петрушку та ще раз акуратно перемішайте.",
             "en": "Season with salt and black pepper, add chopped parsley and gently toss again.",
             "pl": "Dopraw solą i pieprzem, dodaj posiekaną natkę pietruszki i delikatnie wymieszaj ponownie."}
        ]
    },
    {
        "title": "Соус гуакамоле",
        "title_en": "Guacamole sauce",
        "title_pl": "Sos guacamole",
        "description": "Класичний мексиканський соус із кремового авокадо та свіжих овочів. Чудово підходить як закуска або доповнення до основних страв.",
        "description_en": "Classic Mexican sauce with creamy avocado and fresh vegetables. Perfect as a snack or side to main dishes.",
        "description_pl": "Klasyczny meksykański sos z kremowego awokado i świeżych warzyw. Świetnie nadaje się jako przekąska lub dodatek do dań głównych.",
        "source": "Шеф-кухар SoulFood Lab Андрій Коваль",
        "source_en": "Chef of SoulFood Lab Andriy Koval",
        "source_pl": "Szef kuchni SoulFood Lab Andrij Kowal",
        "cooking_time": 10,
        "portions": 2,
        "calories": 220,
        "difficulty": Difficulty.EASY,
        "cuisine": [Cuisine.MEXICAN],
        "meal_times": [MealTime.SNACK],
        "dietary_tags": [Diet.VEGAN],
        "dish_types": [DishType.SAUCE, DishType.SNACK],
        "ingredients": [
            ("Авокадо", 2, UnitChoice.PCS),
            ("Лайм", 1, UnitChoice.PCS),
            ("Помідор", 150, UnitChoice.G),
            ("Цибуля червона", 50, UnitChoice.G),
            ("Кінза", 5, UnitChoice.G),
            ("Сіль", None, UnitChoice.TASTE),
        ],
        "steps": [
            {"uk": "Розріжте авокадо навпіл, видаліть кісточку та ложкою дістаньте м’якоть у миску.",
             "en": "Cut the avocado in half, remove the pit, and scoop the flesh into a bowl with a spoon.",
             "pl": "Przekrój awokado na pół, usuń pestkę i łyżką wydrąż miąższ do miski."},
            {"uk": "Розімніть авокадо виделкою до бажаної текстури.",
             "en": "Mash the avocado with a fork to the desired texture.",
             "pl": "Rozgnieć awokado widelcem na pożądaną konsystencję."},
            {"uk": "Дрібно наріжте помідор та червону цибулю, кінзу подрібніть.",
             "en": "Finely chop the tomato and red onion, and mince the cilantro.",
             "pl": "Drobno posiekaj pomidora i czerwoną cebulę, posiekaj kolendrę."},
            {"uk": "Додайте до авокадо нарізані овочі та акуратно перемішайте.",
             "en": "Add the chopped vegetables to the avocado and gently mix.",
             "pl": "Dodaj posiekane warzywa do awokado i delikatnie wymieszaj."},
            {
                "uk": "Видавіть сік лайма та додайте сіль за смаком, щоб підкреслити свіжість і запобігти потемнінню авокадо.",
                "en": "Squeeze the lime juice and add salt to taste to highlight freshness and prevent the avocado from browning.",
                "pl": "Wyciśnij sok z limonki i dodaj sól do smaku, aby podkreślić świeżość i zapobiec ciemnieniu awokado."},
            {"uk": "Ще раз перемішайте до однорідності, зберігаючи текстуру інгредієнтів.",
             "en": "Carefully mix once more until smooth, maintaining the texture of the ingredients.",
             "pl": "Ponownie delikatnie wymieszaj, zachowując teksturę składników."}
        ]
    },
    {
        "title": "Лосось запечений з овочами",
        "title_en": "Baked salmon with vegetables",
        "title_pl": "Łosoś pieczony z warzywami",
        "description": "Ніжний лосось у поєднанні з овочами — корисна та збалансована страва. Ідеальний варіант для легкої вечері або здорового обіду.",
        "description_en": "Tender salmon combined with vegetables is a healthy and balanced dish. Perfect for a light dinner or a healthy lunch.",
        "description_pl": "Delikatny łosoś w połączeniu z warzywami to zdrowe i zbilansowane danie. Idealne na lekką kolację lub zdrowy lunch.",
        "source": "Шеф-кухар SoulFood Lab Андрій Коваль",
        "source_en": "Chef of SoulFood Lab Andriy Koval",
        "source_pl": "Szef kuchni SoulFood Lab Andrij Kowal",
        "cooking_time": 30,
        "portions": 2,
        "calories": 450,
        "difficulty": Difficulty.EASY,
        "cuisine": [Cuisine.MEDITERRANEAN],
        "meal_times": [MealTime.LUNCH, MealTime.DINNER],
        "dietary_tags": [Diet.DIETARY],
        "dish_types": [DishType.MAIN, DishType.FISH],
        "ingredients": [
            ("Філе лосося", 300, UnitChoice.G),
            ("Броколі", 150, UnitChoice.G),
            ("Кабачок", 300, UnitChoice.G),
            ("Лимон", 0.5, UnitChoice.PCS),
            ("Оливкова олія", 1, UnitChoice.TBSP),
            ("Сіль", None, UnitChoice.TASTE),
            ("Перець чорний", None, UnitChoice.TASTE),
        ],
        "steps": [
            {
                "uk": "Броколі розділіть на суцвіття, кабачок наріжте півкільцями або слайсами. Лосось промийте та обсушіть.",
                "en": "Divide the broccoli into florets, slice the zucchini into half-moons or slices. Wash and dry the salmon.",
                "pl": "Podziel brokuły na różyczki, cukinię pokrój w półplasterki. Umyj i osusz łososia."},
            {
                "uk": "Викладіть овочі на деко, застелене пергаментом, рівномірним шаром. Злегка приправте сіллю та чорним перцем.",
                "en": "Place the vegetables in an even layer on a baking sheet lined with parchment. Lightly season with salt and black pepper.",
                "pl": "Warzywa ułóż równomierną warstwą na blasze wyłożonej papierem. Lekko dopraw solą i pieprzem."},
            {"uk": "Розмістіть філе лосося серед овочів, шкіркою вниз (якщо є шкірка).",
             "en": "Place the salmon fillet among the vegetables, skin side down (if it has skin).",
             "pl": "Umieść filet z łososia wśród warzyw, skórą do dołu (jeśli ma skórę)."},
            {
                "uk": "Полийте все оливковою олією та свіжовичавленим лимонним соком, рівномірно розподіливши по інгредієнтах.",
                "en": "Drizzle everything with olive oil and freshly squeezed lemon juice, distributing evenly over the ingredients.",
                "pl": "Całość skrop oliwą i świeżo wyciśniętym sokiem z cytryny, równomiernie rozprowadzając."},
            {
                "uk": "Запікайте у розігрітій до 180°C духовці приблизно 18–20 хвилин до готовності риби та м’якості овочів.",
                "en": "Bake in a preheated 180°C oven for about 18-20 minutes until the fish is cooked and the vegetables are tender.",
                "pl": "Piecz w nagrzanym do 180°C piekarniku przez około 18-20 minut, aż ryba będzie gotowa, a warzywa miękkie."},
            {"uk": "Дістаньте з духовки та залиште на 2–3 хвилини для отримання кращого смаку",
             "en": "Remove from the oven and let sit for 2-3 minutes for best flavor",
             "pl": "Wyjmij z piekarnika i pozostaw na 2-3 minuty dla uzyskania lepszego smaku"}
        ]
    },
    {
        "title": "Салат з нутом та овочами",
        "title_en": "Chickpea and vegetable salad",
        "title_pl": "Sałatka z ciecierzycą i warzywami",
        "description": "Поживний і ситний салат із нутом та свіжими овочами. Відмінний варіант для веганського обіду або вечері.",
        "description_en": "A nutritious and satisfying salad with chickpeas and fresh vegetables. An excellent option for a vegan lunch or dinner.",
        "description_pl": "Pożywna i sycąca sałatka z ciecierzycą i świeżymi warzywami. Doskonała opcja na wegański obiad lub kolację.",
        "source": "Шеф-кухар SoulFood Lab Андрій Коваль",
        "source_en": "Chef of SoulFood Lab Andriy Koval",
        "source_pl": "Szef kuchni SoulFood Lab Andrij Kowal",
        "cooking_time": 20,
        "portions": 2,
        "calories": 320,
        "difficulty": Difficulty.EASY,
        "cuisine": [Cuisine.MEDITERRANEAN],
        "meal_times": [MealTime.LUNCH, MealTime.DINNER],
        "dietary_tags": [Diet.VEGAN],
        "dish_types": [DishType.SALAD],
        "ingredients": [
            ("Нут", 150, UnitChoice.G),
            ("Огірок", 100, UnitChoice.G),
            ("Помідор", 300, UnitChoice.G),
            ("Петрушка", 10, UnitChoice.G),
            ("Лимонний сік", 1, UnitChoice.TBSP),
            ("Оливкова олія", 1, UnitChoice.TBSP),
            ("Сіль", None, UnitChoice.TASTE),
            ("Перець чорний", None, UnitChoice.TASTE),
        ],
        "steps": [
            {
                "uk": "Підготуйте нут: якщо використовується сухий — замочіть та відваріть до м’якості. Якщо консервований — промийте під холодною водою та дайте стекти.",
                "en": "Prepare the chickpeas: if using dried, soak and boil until soft. If canned, rinse under cold water and drain.",
                "pl": "Przygotuj ciecierzycę: suchą namocz i ugotuj. Z puszki – opłucz zimną wodą i odsącz."},
            {
                "uk": "Підготуйте овочі: огірок наріжте кубиками або півкільцями, помідори розріжте на частинки або четвертинки.",
                "en": "Prepare the vegetables: dice or slice the cucumber, cut the tomatoes into wedges or quarters.",
                "pl": "Przygotuj warzywa: ogórek pokrój w kostkę lub półplasterki, pomidory w ćwiartki lub mniejsze części."},
            {"uk": "Дрібно наріжте свіжу петрушку для аромату та свіжості страви.",
             "en": "Finely chop fresh parsley to add flavor and freshness.",
             "pl": "Drobno posiekaj świeżą pietruszkę, by dodać smaku i świeżości."},
            {"uk": "У великій мисці перемішайте нут, підготовлені овочі та зелень.",
             "en": "In a large bowl, mix the chickpeas, prepared vegetables, and herbs.",
             "pl": "W dużej misce wymieszaj ciecierzycę, przygotowane warzywa i zieleninę."},
            {"uk": "Приготуйте заправку: змішайте оливкову олію, лимонний сік, сіль та чорний перець до однорідності.",
             "en": "Make the dressing: mix olive oil, lemon juice, salt, and black pepper until smooth.",
             "pl": "Przygotuj dressing: wymieszaj oliwę z oliwek, sok z cytryny, sól i pieprz do uzyskania jednolitej konsystencji."},
            {"uk": "Додайте заправку до салату та перемішайте, щоб рівномірно покрити всі інгредієнти.",
             "en": "Add the dressing to the salad and toss to coat all ingredients evenly.",
             "pl": "Dodaj dressing do sałatki i wymieszaj, aby równomiernie pokryć wszystkie składniki."},
            {"uk": "Залиште салат на 5–10 хвилин для гармонізації смаків.",
             "en": "Let the salad sit for 5-10 minutes to allow the flavors to blend.",
             "pl": "Odstaw sałatkę na 5-10 minut, by smaki się przegryzły."}
        ]
    },
    {
        "title": "Йогуртовий десерт з ягодами",
        "title_en": "Yogurt dessert with berries",
        "title_pl": "Deser jogurtowy z jagodami",
        "description": "Легкий і ніжний десерт із йогурту та свіжих ягід. Ідеальний варіант для перекусу або корисного солодкого.",
        "description_en": "A light and delicate dessert made with yogurt and fresh berries. An ideal option for a snack or a healthy sweet treat.",
        "description_pl": "Lekki i delikatny deser z jogurtu i świeżych owoców. Idealna opcja na przekąskę lub zdrową słodycz.",
        "source": "Шеф-кухар SoulFood Lab Андрій Коваль",
        "source_en": "Chef of SoulFood Lab Andriy Koval",
        "source_pl": "Szef kuchni SoulFood Lab Andrij Kowal",
        "cooking_time": 5,
        "portions": 1,
        "calories": 260,
        "difficulty": Difficulty.EASY,
        "cuisine": [Cuisine.EUROPEAN],
        "meal_times": [MealTime.SNACK],
        "dietary_tags": [Diet.VEGETARIAN],
        "dish_types": [DishType.DESSERT],
        "ingredients": [
            ("Йогурт", 200, UnitChoice.G),
            ("Полуниця", 50, UnitChoice.G),
            ("Чорниця", 50, UnitChoice.G),
            ("Мед", 1, UnitChoice.TSP),
            ("Горіхи", 20, UnitChoice.G),
        ],
        "steps": [
            {"uk": "Промийте ягоди під холодною водою та обсушіть. За потреби поріжте великі ягоди.",
             "en": "Wash the berries under cold water and pat dry. Cut large berries if necessary.",
             "pl": "Umyj owoce pod zimną wodą i osusz. W razie potrzeby pokrój większe owoce."},
            {"uk": "Викладіть йогурт у склянку або креманку, формуючи основу десерту.",
             "en": "Place the yogurt into a glass or bowl, forming the base of the dessert.",
             "pl": "Nałóż jogurt do szklanki lub miseczki, tworząc bazę deseru."},
            {"uk": "Рівномірно розподіліть свіжі ягоди поверх йогурту, створюючи шар або декоративну композицію.",
             "en": "Distribute the fresh berries evenly over the yogurt, creating a layer or a decorative pattern.",
             "pl": "Równomiernie rozłóż świeże owoce na jogurcie, tworząc warstwę lub dekorację."},
            {"uk": "Полийте десерт невеликою кількістю меду для легкого солодкого балансу.",
             "en": "Drizzle the dessert with a little honey for a light sweet balance.",
             "pl": "Polej deser odrobiną miodu, aby nadać mu lekką słodycz."},
            {"uk": "Посипте подрібненими горіхами для додаткової текстури та аромату.",
             "en": "Sprinkle with chopped nuts for added texture and flavor.",
             "pl": "Posyp posiekanymi orzechami dla dodatkowej tekstury i smaku."}
        ]
    },
    {
        "title": "Креветки з часником",
        "title_en": "Garlic shrimp",
        "title_pl": "Krewetki z czosnkiem",
        "description": "Ароматні креветки, обсмажені з часником і лимонним соком. Швидка та вишукана страва для легкої вечері або закуски.",
        "description_en": "Aromatic shrimp sautéed with garlic and lemon juice. A quick and elegant dish for a light dinner or appetizer.",
        "description_pl": "Aromatyczne krewetki smażone z czosnkiem i sokiem z cytryny. Szybkie i wykwintne danie na lekką kolację lub przystawkę.",
        "source": "Шеф-кухар SoulFood Lab Андрій Коваль",
        "source_en": "Chef of SoulFood Lab Andriy Koval",
        "source_pl": "Szef kuchni SoulFood Lab Andrij Kowal",
        "cooking_time": 10,
        "portions": 2,
        "calories": 230,
        "difficulty": Difficulty.MEDIUM,
        "cuisine": [Cuisine.MEDITERRANEAN],
        "meal_times": [MealTime.LUNCH, MealTime.DINNER],
        "dietary_tags": [Diet.DIETARY],
        "dish_types": [DishType.SNACK, DishType.SEAFOOD],
        "ingredients": [
            ("Креветки очищені", 300, UnitChoice.G),
            ("Часник", 3, UnitChoice.CLOVE),
            ("Оливкова олія", 1, UnitChoice.TBSP),
            ("Лимонний сік", 1, UnitChoice.TBSP),
            ("Петрушка", 10, UnitChoice.G),
            ("Сіль", None, UnitChoice.TASTE),
            ("Перець чорний", None, UnitChoice.TASTE),
        ],
        "steps": [
            {"uk": "Підготуйте креветки: за потреби розморозьте їх, промийте під холодною водою та обсушіть.",
             "en": "Prepare the shrimp: thaw if necessary, wash under cold water, and dry.",
             "pl": "Przygotuj krewetki: w razie potrzeby rozmroź, opłucz zimną wodą i osusz."},
            {"uk": "Подрібніть часник, петрушку покришіть для фінального оздоблення страви.",
             "en": "Mince the garlic and chop the parsley for the final garnish.",
             "pl": "Posiekaj czosnek, a natkę pietruszki pokrój do dekoracji dania."},
            {"uk": "Розігрійте оливкову олію на сковороді на середньо-високому вогні до легкого шипіння.",
             "en": "Heat olive oil in a pan over medium-high heat until it gently sizzles.",
             "pl": "Rozgrzej oliwę na patelni na średnio wysokim ogniu, aż zacznie lekko skwierczeć."},
            {"uk": "Додайте часник і обсмажте протягом 20–30 секунд до появи аромату, не допускаючи підгоряння.",
             "en": "Add garlic and sauté for 20-30 seconds until fragrant, not allowing it to burn.",
             "pl": "Dodaj czosnek i smaż przez 20-30 sekund do uzyskania aromatu, nie dopuszczając do przypalenia."},
            {
                "uk": "Додайте креветки та готуйте 2–3 хвилини з одного боку, потім переверніть і готуйте ще 1–2 хвилини, поки вони стануть рожевими та щільними.",
                "en": "Add the shrimp and cook 2-3 minutes on one side, then flip and cook another 1-2 minutes until pink and firm.",
                "pl": "Dodaj krewetki i smaż 2-3 minuty z jednej strony, następnie odwróć i smaż jeszcze 1-2 minuty, aż staną się różowe i jędrne."},
            {"uk": "Влийте лимонний сік та перемішайте, щоб утворився легкий соус.",
             "en": "Pour in the lemon juice and stir to create a light sauce.",
             "pl": "Wlej sok z cytryny i wymieszaj, aby powstał lekki sos."},
            {"uk": "Приправте сіллю та чорним перцем за смаком, додайте петрушку.",
             "en": "Season with salt and black pepper to taste, and add the parsley.",
             "pl": "Dopraw solą i pieprzem do smaku, dodaj pietruszkę."}
        ]
    },
    {
        "title": "Український борщ",
        "title_en": "Ukrainian borscht",
        "title_pl": "Barszcz ukraiński",
        "description": "Традиційна українська страва з насиченим смаком і ароматом. Ситний і поживний суп, який ідеально підходить для обіду.",
        "description_en": "A traditional Ukrainian dish with rich flavor and aroma. A hearty and nutritious soup that is perfect for lunch.",
        "description_pl": "Tradycyjne ukraińskie danie o bogatym smaku i aromacie. Sycąca i pożywna zupa, idealna na obiad.",
        "source": "Шеф-кухар SoulFood Lab Андрій Коваль",
        "source_en": "Chef of SoulFood Lab Andriy Koval",
        "source_pl": "Szef kuchni SoulFood Lab Andrij Kowal",
        "cooking_time": 50,
        "portions": 4,
        "calories": 350,
        "difficulty": Difficulty.HARD,
        "cuisine": [Cuisine.UKRAINIAN],
        "meal_times": [MealTime.LUNCH],
        "dietary_tags": [Diet.TRADITIONAL],
        "dish_types": [DishType.SOUP],
        "ingredients": [
            ("Буряк", 300, UnitChoice.G),
            ("Картопля", 300, UnitChoice.G),
            ("Морква", 100, UnitChoice.G),
            ("Капуста білокачанна", 200, UnitChoice.G),
            ("Цибуля ріпчаста", 100, UnitChoice.G),
            ("Томатна паста", 1, UnitChoice.TBSP),
            ("Часник", 2, UnitChoice.CLOVE),
            ("Рослинна олія", 1, UnitChoice.TBSP),
            ("Вода", 1, UnitChoice.L),
            ("Сіль", None, UnitChoice.TASTE),
            ("Перець чорний", None, UnitChoice.TASTE),
            ("Кріп", None, UnitChoice.TASTE),
        ],
        "steps": [
            {
                "uk": "Підготуйте овочі: буряк, моркву та картоплю очистіть. Буряк наріжте тонкою соломкою, моркву натріть або наріжте дрібною соломкою, картоплю — кубиками, капусту нашаткуйте, цибулю дрібно наріжте.",
                "en": "Prepare the vegetables: peel beets, carrots, and potatoes. Julienne the beets, grate or finely julienne the carrots, cube the potatoes, shred the cabbage, and finely chop the onion.",
                "pl": "Przygotuj warzywa: obierz buraki, marchew i ziemniaki. Buraki pokrój w cienkie paski, marchew zetrzyj na tarce, ziemniaki w kostkę, kapustę poszatkuj, a cebulę drobno posiekaj."},
            {
                "uk": "У каструлі розігрійте рослинну олію та обсмажте цибулю до прозорості, додайте моркву та готуйте ще 2–3 хвилини до м’якості.",
                "en": "Heat vegetable oil in a pot and sauté the onion until translucent, add carrots and cook another 2-3 minutes until soft.",
                "pl": "Rozgrzej olej w garnku i podsmaż cebulę na złoty kolor, dodaj marchew i gotuj jeszcze 2-3 minuty."},
            {
                "uk": "Додайте буряк і томатну пасту, перемішайте та тушкуйте 5–7 хвилин, щоб буряк зберіг колір і набув насиченого смаку.",
                "en": "Add the beets and tomato paste, stir and simmer for 5-7 minutes so the beets retain their color and gain a rich flavor.",
                "pl": "Dodaj buraki i koncentrat pomidorowy, wymieszaj i duś przez 5-7 minut, aby burak zachował kolor i smak."},
            {"uk": "Влийте воду, доведіть до кипіння та додайте картоплю. Варіть 10 хвилин на середньому вогні.",
             "en": "Pour in water, bring to a boil, and add the potatoes. Cook for 10 minutes over medium heat.",
             "pl": "Wlej wodę, doprowadź do wrzenia i dodaj ziemniaki. Gotuj przez 10 minut na średnim ogniu."},
            {"uk": "Додайте нашатковану капусту та продовжуйте варити ще 10–12 хвилин до м’якості овочів.",
             "en": "Add shredded cabbage and continue cooking for 10-12 minutes until vegetables are tender.",
             "pl": "Dodaj poszatkowaną kapustę i gotuj przez kolejne 10-12 minut, aż warzywa będą miękkie."},
            {"uk": "Приправте сіллю та чорним перцем за смаком.", "en": "Season with salt and black pepper to taste.",
             "pl": "Dopraw solą i czarnym pieprzem do smaku."},
            {"uk": "Наприкінці додайте подрібнений часник та свіжий кріп, перемішайте та зніміть з вогню.",
             "en": "At the end, add minced garlic and fresh dill, stir, and remove from heat.",
             "pl": "Na koniec dodaj posiekany czosnek i świeży koperek, wymieszaj i zdejmij z ognia."}
        ]
    },
    {
        "title": "Французький омлет з сиром",
        "title_en": "French omelette with cheese",
        "title_pl": "Francuski omlet z serem",
        "description": "Ніжний і повітряний омлет із розплавленим сиром — класичний варіант швидкого сніданку. Легка текстура та насичений смак.",
        "description_en": "A delicate and airy omelette with melted cheese - a classic quick breakfast. Light texture and rich flavor.",
        "description_pl": "Delikatny i puszysty omlet z roztopionym serem - klasyczny wariant na szybkie śniadanie. Lekka tekstura i bogaty smak.",
        "source": "Шеф-кухар SoulFood Lab Андрій Коваль",
        "source_en": "Chef of SoulFood Lab Andriy Koval",
        "source_pl": "Szef kuchni SoulFood Lab Andrij Kowal",
        "cooking_time": 10,
        "portions": 1,
        "calories": 300,
        "difficulty": Difficulty.EASY,
        "cuisine": [Cuisine.FRENCH],
        "meal_times": [MealTime.BREAKFAST],
        "dietary_tags": [Diet.VEGETARIAN],
        "dish_types": [DishType.OMELET],
        "ingredients": [
            ("Яйця", 3, UnitChoice.PCS),
            ("Голландський сир", 50, UnitChoice.G),
            ("Вершкове масло", 10, UnitChoice.G),
            ("Сіль", None, UnitChoice.TASTE),
            ("Перець чорний", None, UnitChoice.TASTE),
        ],
        "steps": [
            {
                "uk": "Розбийте яйця у миску та збийте їх виделкою або вінчиком до однорідної консистенції без надмірного піноутворення.",
                "en": "Crack eggs into a bowl and beat them with a fork or whisk until smooth, without over-foaming.",
                "pl": "Wbij jajka do miski i ubij widelcem lub trzepaczką do gładkości, nie doprowadzając do nadmiernego spienienia."},
            {"uk": "Приправте яйця сіллю та чорним перцем, ще раз легко перемішайте.",
             "en": "Season the eggs with salt and black pepper, mix lightly again.",
             "pl": "Dopraw jajka solą i pieprzem, jeszcze raz delikatnie wymieszaj."},
            {
                "uk": "Розігрійте сковороду на середньому або середньо-низькому вогні та додайте вершкове масло, дайте йому повністю розтанути, не допускаючи підгоряння.",
                "en": "Heat a pan over medium to medium-low heat, add butter and let it melt completely without burning.",
                "pl": "Rozgrzej patelnię na średnim ogniu, dodaj masło i pozwól mu się całkowicie rozpuścić, nie przypalając."},
            {
                "uk": "Вилийте яєчну суміш на сковороду та одразу почніть обережно рухати її лопаткою, формуючи ніжну кремову текстуру.",
                "en": "Pour the egg mixture into the pan and immediately start gently moving it with a spatula, forming a tender, creamy texture.",
                "pl": "Wlej masę jajeczną na patelnię i od razu zacznij delikatnie przesuwać ją łopatką, tworząc kremową teksturę."},
            {"uk": "Коли омлет почне підсмажуватися, рівномірно посипте тертим сиром по поверхні.",
             "en": "When the omelette begins to set, evenly sprinkle grated cheese over the surface.",
             "pl": "Gdy omlet zacznie się ścinać, równomiernie posyp go startym serem."},
            {"uk": "Складіть омлет навпіл або у форму рулету, коли середина ще залишається злегка кремовою.",
             "en": "Fold the omelette in half or roll it up while the center is still slightly creamy.",
             "pl": "Złóż omlet na pół lub zwiń w rulon, gdy środek jest jeszcze lekko kremowy."},
            {"uk": "Зніміть з вогню — страва готова", "en": "Remove from heat — the dish is ready.",
             "pl": "Zdejmij z ognia — danie jest gotowe."}
        ]
    },
    {
        "title": "Американські панкейки",
        "title_en": "American pancakes",
        "title_pl": "Amerykańskie naleśniki",
        "description": "Пухкі та ніжні панкейки — ідеальний варіант для сніданку або десерту. Чудово поєднуються з ягодами, медом або сиропом.",
        "description_en": "Fluffy and tender pancakes - an ideal option for breakfast or dessert. They pair wonderfully with berries, honey, or syrup.",
        "description_pl": "Puszyste i delikatne naleśniki – idealna opcja na śniadanie lub deser. Świetnie komponują się z jagodami, miodem lub syropem.",
        "source": "Шеф-кухар SoulFood Lab Андрій Коваль",
        "source_en": "Chef of SoulFood Lab Andriy Koval",
        "source_pl": "Szef kuchni SoulFood Lab Andrij Kowal",
        "cooking_time": 25,
        "portions": 3,
        "calories": 420,
        "difficulty": Difficulty.MEDIUM,
        "cuisine": [Cuisine.AMERICAN],
        "meal_times": [MealTime.BREAKFAST],
        "dietary_tags": [Diet.VEGETARIAN],
        "dish_types": [DishType.DESSERT, DishType.FLOUR],
        "ingredients": [
            ("Пшеничне борошно", 150, UnitChoice.G),
            ("Яйця", 1, UnitChoice.PCS),
            ("Молоко", 200, UnitChoice.ML),
            ("Цукор", 1, UnitChoice.TBSP),
            ("Розпушувач", 1, UnitChoice.TSP),
            ("Вершкове масло", 20, UnitChoice.G),
        ],
        "steps": [
            {"uk": "У великій мисці просійте пшеничне борошно, щоб уникнути грудочок.",
             "en": "In a large bowl, sift the wheat flour to avoid lumps.",
             "pl": "Do dużej miski przesiej mąkę pszenną, aby uniknąć grudek."},
            {"uk": "Додайте цукор і розпушувач, ретельно перемішайте.",
             "en": "Add sugar and baking powder, mix thoroughly.",
             "pl": "Dodaj cukier i proszek do pieczenia, dokładnie wymieszaj."},
            {
                "uk": "В окремій мисці злегка збийте яйце, додайте молоко та розтоплене вершкове масло, перемішайте до однорідності.",
                "en": "In a separate bowl, lightly beat the egg, add milk and melted butter, mix until smooth.",
                "pl": "W osobnej misce lekko ubij jajko, dodaj mleko i roztopione masło, wymieszaj do gładkości."},
            {
                "uk": "Влийте рідку суміш у сухі інгредієнти та акуратно перемішайте до об’єднання. Не вимішуйте надто довго — тісто має залишатися злегка грудкуватим.",
                "en": "Pour the wet mixture into the dry ingredients and gently mix until combined. Do not overmix - the batter should remain slightly lumpy.",
                "pl": "Wlej mokrą mieszankę do suchych składników i delikatnie wymieszaj. Nie mieszaj za długo – ciasto powinno być lekko grudkowate."},
            {"uk": "Розігрійте сковороду на середньому вогні та злегка змастіть її маслом.",
             "en": "Heat a frying pan over medium heat and lightly grease with butter.",
             "pl": "Rozgrzej patelnię na średnim ogniu i lekko natłuść masłem."},
            {"uk": "Виливайте невеликі порції тіста, формуючи панкейки бажаного розміру.",
             "en": "Pour small portions of batter to form pancakes of desired size.",
             "pl": "Wylewaj małe porcje ciasta, formując naleśniki o pożądanej wielkości."},
            {
                "uk": "Смажте до появи бульбашок на поверхні та золотистого кольору знизу, після чого переверніть і доведіть до готовності протягом ще 1–2 хвилин.",
                "en": "Cook until bubbles form on the surface and the bottom is golden brown, then flip and cook for another 1-2 minutes until done.",
                "pl": "Smaż do pojawienia się bąbelków na powierzchni, a spód będzie złoty, następnie przewróć i smaż jeszcze 1-2 minuty."}
        ]
    },
    {
        "title": "Китайський салат з огірком",
        "title_en": "Chinese cucumber salad",
        "title_pl": "Chińska sałatka z ogórkiem",
        "description": "Легкий і освіжаючий салат із пікантною заправкою. Чудовий варіант для швидкого перекусу.",
        "description_en": "A light and refreshing salad with a spicy dressing. A great option for a quick snack.",
        "description_pl": "Lekka i orzeźwiająca sałatka z pikantnym sosem. Świetna propozycja na szybką przekąskę.",
        "source": "Шеф-кухар SoulFood Lab Андрій Коваль",
        "source_en": "Chef of SoulFood Lab Andriy Koval",
        "source_pl": "Szef kuchni SoulFood Lab Andrij Kowal",
        "cooking_time": 10,
        "portions": 2,
        "calories": 140,
        "difficulty": Difficulty.EASY,
        "cuisine": [Cuisine.CHINESE],
        "meal_times": [MealTime.SNACK],
        "dietary_tags": [Diet.VEGAN],
        "dish_types": [DishType.SALAD],
        "ingredients": [
            ("Огірок", 200, UnitChoice.G),
            ("Часник", 2, UnitChoice.CLOVE),
            ("Соєвий соус", 1, UnitChoice.TBSP),
            ("Рисовий оцет", 1, UnitChoice.TSP),
            ("Кунжутна олія", 1, UnitChoice.TSP),
        ],
        "steps": [
            {"uk": "Ретельно промийте огірки та наріжте на шматочки або кружальця.",
             "en": "Thoroughly wash the cucumbers and slice into pieces or rounds.",
             "pl": "Dokładnie umyj ogórki i pokrój w plasterki lub kawałki."},
            {
                "uk": "Посоліть огірки легенько та залиште на 5 хвилин, щоб вони пустили сік, після чого злегка відтисніть.",
                "en": "Lightly salt the cucumbers and leave for 5 minutes so they release juice, then squeeze lightly.",
                "pl": "Lekko posól ogórki i odstaw na 5 minut, aby puściły sok, a następnie delikatnie wyciśnij."},
            {"uk": "Подрібніть часник для максимально інтенсивного аромату.",
             "en": "Mince the garlic for maximum intense aroma.", "pl": "Posiekaj czosnek dla maksymalnego aromatu."},
            {"uk": "У невеликій мисці змішайте соєвий соус, рисовий оцет та кунжутну олію до однорідної заправки.",
             "en": "In a small bowl, mix soy sauce, rice vinegar, and sesame oil to make a smooth dressing.",
             "pl": "W małej misce wymieszaj sos sojowy, ocet ryżowy i olej sezamowy."},
            {"uk": "Додайте подрібнений часник до заправки та перемішайте.",
             "en": "Add the minced garlic to the dressing and mix.",
             "pl": "Dodaj posiekany czosnek do sosu i wymieszaj."},
            {"uk": "Ретельно перемішайте огірки із соусом, щоб кожен шматочок був покритий заправкою.",
             "en": "Thoroughly toss the cucumbers with the sauce to coat every piece.",
             "pl": "Dokładnie wymieszaj ogórki z sosem, aby każdy kawałek był pokryty."},
            {"uk": "Залиште салат на 5–10 хвилин для насичення смаку.",
             "en": "Leave the salad for 5-10 minutes to absorb the flavors.",
             "pl": "Odstaw sałatkę na 5-10 minut, aby smaki się przegryzły."}
        ]
    },
    {
        "title": "Японський місо-суп",
        "title_en": "Japanese miso soup",
        "title_pl": "Japońska zupa miso",
        "description": "Традиційний японський суп із ніжним смаком місо та тофу. Легка і корисна страва для обіду.",
        "description_en": "A traditional Japanese soup with a delicate miso and tofu flavor. A light and healthy dish for lunch.",
        "description_pl": "Tradycyjna japońska zupa o delikatnym smaku miso i tofu. Lekkie i zdrowe danie na lunch.",
        "source": "Шеф-кухар SoulFood Lab Андрій Коваль",
        "source_en": "Chef of SoulFood Lab Andriy Koval",
        "source_pl": "Szef kuchni SoulFood Lab Andrij Kowal",
        "cooking_time": 15,
        "portions": 2,
        "calories": 180,
        "difficulty": Difficulty.MEDIUM,
        "cuisine": [Cuisine.JAPANESE],
        "meal_times": [MealTime.LUNCH],
        "dietary_tags": [Diet.VEGETARIAN],
        "dish_types": [DishType.SOUP],
        "ingredients": [
            ("Місо паста", 2, UnitChoice.TBSP),
            ("Тофу", 100, UnitChoice.G),
            ("Водорості вакаме", 5, UnitChoice.G),
            ("Цибуля зелена", 20, UnitChoice.G),
            ("Вода", 500, UnitChoice.ML),
        ],
        "steps": [
            {
                "uk": "Нагрійте воду в каструлі до гарячого стану, не доводячи до сильного кипіння, щоб зберегти делікатний смак бульйону.",
                "en": "Heat water in a pot until hot, without boiling vigorously, to preserve the delicate flavor of the broth.",
                "pl": "Podgrzej wodę w garnku, nie doprowadzając do wrzenia, aby zachować delikatny smak bulionu."},
            {"uk": "Додайте водорості вакаме та дайте їм розм’якнути протягом 2–3 хвилин.",
             "en": "Add the wakame seaweed and let it soften for 2-3 minutes.",
             "pl": "Dodaj wodorosty wakame i pozwól im zmięknąć przez 2-3 minuty."},
            {"uk": "Наріжте тофу кубиками середнього розміру, щоб він зберіг форму в супі.",
             "en": "Cut tofu into medium cubes so it retains its shape in the soup.",
             "pl": "Pokrój tofu w średnią kostkę, aby zachowało kształt w zupie."},
            {"uk": "Додайте тофу в гарячий бульйон і прогрійте 1–2 хвилини без активного кипіння.",
             "en": "Add the tofu to the hot broth and heat for 1-2 minutes without boiling vigorously.",
             "pl": "Dodaj tofu do gorącego bulionu i podgrzewaj przez 1-2 minuty bez wrzenia."},
            {"uk": "У невеликій кількості гарячого бульйону розчиніть місо пасту до однорідності, уникаючи грудочок.",
             "en": "Dissolve the miso paste in a small amount of hot broth until smooth, avoiding lumps.",
             "pl": "Rozpuść pastę miso w niewielkiej ilości gorącego bulionu, aby nie było grudek."},
            {
                "uk": "Поверніть розчинену місо пасту в каструлю та перемішайте, не доводячи суп до кипіння після цього етапу.",
                "en": "Return the dissolved miso paste to the pot and mix, without bringing the soup to a boil from this point.",
                "pl": "Wlej rozpuszczoną pastę miso do garnka i wymieszaj, nie gotując zupy."},
            {"uk": "Додайте тонко нарізану зелену цибулю перед завершенням приготування.",
             "en": "Add thinly sliced green onions just before finishing.",
             "pl": "Przed podaniem dodaj cienko pokrojoną zieloną cebulkę."}
        ]
    },
    {
        "title": "Азійський імбирний чай",
        "title_en": "Asian ginger tea",
        "title_pl": "Azjatycka herbata imbirowa",
        "description": "Теплий та зігріваючий напій із яскравим смаком імбиру. Допомагає підтримати імунітет і чудово підходить для холодної пори або як корисний щоденний напій.",
        "description_en": "A warm and soothing drink with a bright ginger flavor. Helps support immunity and is perfect for cold weather or as a healthy daily drink.",
        "description_pl": "Ciepły i rozgrzewający napój o wyrazistym smaku imbiru. Wspiera odporność i świetnie nadaje się na chłodne dni lub jako codzienny, zdrowy napój.",
        "source": "Шеф-кухар SoulFood Lab Андрій Коваль",
        "source_en": "Chef of SoulFood Lab Andriy Koval",
        "source_pl": "Szef kuchni SoulFood Lab Andrij Kowal",
        "cooking_time": 10,
        "portions": 2,
        "calories": 80,
        "difficulty": Difficulty.EASY,
        "cuisine": [Cuisine.ASIAN],
        "meal_times": [MealTime.SNACK],
        "dietary_tags": [Diet.VEGETARIAN],
        "dish_types": [DishType.DRINK],
        "ingredients": [
            ("Вода", 400, UnitChoice.ML),
            ("Імбир", 10, UnitChoice.G),
            ("Лимон", 1, UnitChoice.SLICE),
            ("Мед", 1, UnitChoice.TSP),
        ],
        "steps": [
            {
                "uk": "Підготуйте імбир: ретельно промийте корінь та наріжте його тонкими скибками або легенько розчавіть для більш інтенсивного аромату.",
                "en": "Prepare ginger: wash thoroughly and slice thinly or crush slightly for a more intense aroma.",
                "pl": "Przygotuj imbir: dokładnie umyj i pokrój w cienkie plasterki lub lekko zgnieć, aby uwolnić aromat."},
            {"uk": "Доведіть воду до кипіння в невеликій каструлі.", "en": "Bring water to a boil in a small pot.",
             "pl": "Zagotuj wodę w małym garnku."},
            {
                "uk": "Додайте імбир у киплячу воду, зменшіть вогонь і варіть на повільному кипінні 5–7 хвилин для екстракції смаку.",
                "en": "Add ginger to the boiling water, reduce the heat, and simmer for 5-7 minutes to extract flavor.",
                "pl": "Dodaj imbir do wrzącej wody, zmniejsz ogień i gotuj na wolnym ogniu przez 5-7 minut."},
            {"uk": "Зніміть з вогню та дайте чаю настоятися ще 2–3 хвилини для глибшого аромату.",
             "en": "Remove from heat and steep for another 2-3 minutes for deeper aroma.",
             "pl": "Zdejmij z ognia i odstaw herbatę na kolejne 2-3 minuty, aby smak się wzmocnił."},
            {"uk": "Додайте скибку лимона для свіжості та природної кислотності.",
             "en": "Add a slice of lemon for freshness and natural acidity.",
             "pl": "Dodaj plasterek cytryny dla świeżości."},
            {
                "uk": "Додайте мед у трохи охолоджений напій (щоб зберегти його корисні властивості) та перемішайте до повного розчинення.",
                "en": "Add honey to the slightly cooled drink (to preserve its properties) and stir until dissolved.",
                "pl": "Dodaj miód do lekko przestudzonego napoju (aby zachować jego właściwości) i wymieszaj."}
        ]
    },
    {
        "title": "Свинина запечена з часником",
        "title_en": "Roast pork with garlic",
        "title_pl": "Pieczona wieprzowina z czosnkiem",
        "description": "Соковита свиняча лопатка з насиченим ароматом часнику та спецій. Запікання дозволяє зберегти ніжність м'яса та розкрити його смак.",
        "description_en": "Juicy pork shoulder with a rich aroma of garlic and spices. Baking preserves the tenderness of the meat and reveals its flavor.",
        "description_pl": "Soczysta łopatka wieprzowa z bogatym aromatem czosnku i przypraw. Pieczenie pozwala zachować delikatność mięsa i uwolnić jego smak.",
        "source": "Шеф-кухар SoulFood Lab Андрій Коваль",
        "source_en": "Chef of SoulFood Lab Andriy Koval",
        "source_pl": "Szef kuchni SoulFood Lab Andrij Kowal",
        "cooking_time": 45,
        "portions": 2,
        "calories": 520,
        "difficulty": Difficulty.MEDIUM,
        "cuisine": [Cuisine.EUROPEAN],
        "meal_times": [MealTime.LUNCH, MealTime.DINNER],
        "dietary_tags": [Diet.TRADITIONAL],
        "dish_types": [DishType.MAIN, DishType.MEAT],
        "ingredients": [
            ("Свиняча лопатка", 400, UnitChoice.G),
            ("Часник", 3, UnitChoice.CLOVE),
            ("Оливкова олія", 1, UnitChoice.TBSP),
            ("Паприка", 1, UnitChoice.TSP),
            ("Сіль", None, UnitChoice.TASTE),
            ("Перець чорний", None, UnitChoice.TASTE),
        ],
        "steps": [
            {"uk": "Наріжте свинину шматками середнього розміру для рівномірного запікання.",
             "en": "Cut the pork into medium-sized pieces for even roasting.",
             "pl": "Pokrój wieprzowinę na średniej wielkości kawałki do równomiernego pieczenia."},
            {"uk": "Подрібніть часник.", "en": "Mince the garlic.", "pl": "Posiekaj czosnek."},
            {"uk": "Натріть м’ясо сіллю, чорним перцем і паприкою з усіх боків.",
             "en": "Rub the meat with salt, black pepper, and paprika on all sides.",
             "pl": "Natrzyj mięso solą, czarnym pieprzem i papryką ze wszystkich stron."},
            {"uk": "Додайте подрібнений часник і рівномірно розподіліть по м’ясу.",
             "en": "Add the minced garlic and distribute it evenly over the meat.",
             "pl": "Dodaj posiekany czosnek i równomiernie rozprowadź na mięsie."},
            {"uk": "Полийте оливковою олією та ретельно перемішайте, щоб спеції рівномірно покрили м’ясо.",
             "en": "Drizzle with olive oil and mix thoroughly so the spices coat the meat evenly.",
             "pl": "Polej oliwą z oliwek i dokładnie wymieszaj, aby przyprawy równomiernie pokryły mięso."},
            {"uk": "Викладіть м’ясо у форму для запікання одним рівномірним шаром.",
             "en": "Place the meat in a baking dish in an even layer.",
             "pl": "Ułóż mięso w naczyniu do pieczenia w jednej warstwie."},
            {"uk": "Розігрійте духовку до 180°C.", "en": "Preheat the oven to 180°C.",
             "pl": "Rozgrzej piekarnik do 180°C."},
            {"uk": "Запікайте приблизно 35 хвилин до повної готовності м’яса.",
             "en": "Bake for about 35 minutes until the meat is fully cooked.",
             "pl": "Piecz około 35 minut, aż mięso będzie w pełni gotowe."}
        ]
    },
    {
        "title": "Крем-суп з гарбуза",
        "title_en": "Pumpkin cream soup",
        "title_pl": "Zupa krem z dyni",
        "description": "Ніжний і кремовий суп із гарбуза з м'яким солодкуватим смаком. Легка та поживна страва, яка чудово зігріває.",
        "description_en": "Delicate and creamy pumpkin soup with a mild sweet taste. A light and nutritious dish that warms perfectly.",
        "description_pl": "Delikatna zupa krem z dyni o łagodnym, słodkawym smaku. Lekkie i pożywne danie, które świetnie rozgrzewa.",
        "source": "Шеф-кухар SoulFood Lab Андрій Коваль",
        "source_en": "Chef of SoulFood Lab Andriy Koval",
        "source_pl": "Szef kuchni SoulFood Lab Andrij Kowal",
        "cooking_time": 40,
        "portions": 3,
        "calories": 210,
        "difficulty": Difficulty.MEDIUM,
        "cuisine": [Cuisine.EUROPEAN],
        "meal_times": [MealTime.LUNCH, MealTime.DINNER],
        "dietary_tags": [Diet.VEGETARIAN],
        "dish_types": [DishType.SOUP],
        "ingredients": [
            ("Гарбуз", 400, UnitChoice.G),
            ("Картопля", 150, UnitChoice.G),
            ("Морква", 100, UnitChoice.G),
            ("Цибуля ріпчаста", 100, UnitChoice.G),
            ("Вершки", 100, UnitChoice.ML),
            ("Оливкова олія", 1, UnitChoice.TBSP),
            ("Сіль", None, UnitChoice.TASTE),
            ("Перець чорний", None, UnitChoice.TASTE),
        ],
        "steps": [
            {"uk": "Очистіть гарбуз і наріжте кубиками для рівномірного приготування.",
             "en": "Peel the pumpkin and cut it into cubes for even cooking.",
             "pl": "Obierz dynię i pokrój w kostkę do równomiernego gotowania."},
            {"uk": "Наріжте картоплю, моркву та цибулю невеликими шматками.",
             "en": "Cut potatoes, carrots, and onions into small pieces.",
             "pl": "Ziemniaki, marchew i cebulę pokrój na mniejsze kawałki."},
            {"uk": "У каструлі розігрійте оливкову олію та обсмажте цибулю до прозорості.",
             "en": "Heat olive oil in a pot and sauté the onion until translucent.",
             "pl": "W garnku rozgrzej oliwę z oliwek i zeszklij cebulę."},
            {"uk": "Додайте моркву, гарбуз і картоплю, перемішайте та злегка обсмажте 2–3 хвилини.",
             "en": "Add carrots, pumpkin, and potatoes, stir and sauté lightly for 2-3 minutes.",
             "pl": "Dodaj marchew, dynię i ziemniaki, wymieszaj i lekko podsmaż przez 2-3 minuty."},
            {"uk": "Залийте овочі водою та варіть приблизно 20 хвилин до м’якості.",
             "en": "Cover vegetables with water and cook for about 20 minutes until soft.",
             "pl": "Zalej warzywa wodą i gotuj około 20 minut, aż staną się miękkie."},
            {"uk": "Збийте масу блендером до однорідної кремової консистенції.",
             "en": "Blend the mixture with an immersion blender until smooth and creamy.",
             "pl": "Zblenduj na gładką, kremową konsystencję."},
            {"uk": "Додайте вершки, сіль і чорний перець, прогрійте до однорідності.",
             "en": "Add cream, salt, and black pepper, heat through until smooth.",
             "pl": "Dodaj śmietankę, sól i czarny pieprz, podgrzej do połączenia składników."}
        ]
    },
    {
        "title": "Сирники",
        "title_en": "Cheesecakes",
        "title_pl": "Placuszki serowe",
        "description": "Традиційна страва з ніжного сиру з рум'яною скоринкою та м'якою текстурою всередині. Ідеально підходять для сніданку.",
        "description_en": "A traditional dish made of delicate cottage cheese with a golden crust and soft texture inside. Perfect for breakfast.",
        "description_pl": "Tradycyjne danie z delikatnego twarogu z rumianą skórką i miękkim wnętrzem. Idealne na śniadanie.",
        "source": "Шеф-кухар SoulFood Lab Андрій Коваль",
        "source_en": "Chef of SoulFood Lab Andriy Koval",
        "source_pl": "Szef kuchni SoulFood Lab Andrij Kowal",
        "cooking_time": 25,
        "portions": 3,
        "calories": 340,
        "difficulty": Difficulty.EASY,
        "cuisine": [Cuisine.UKRAINIAN],
        "meal_times": [MealTime.BREAKFAST, MealTime.SNACK],
        "dietary_tags": [Diet.VEGETARIAN],
        "dish_types": [DishType.DESSERT, DishType.FLOUR],
        "ingredients": [
            ("Кисломолочний сир", 300, UnitChoice.G),
            ("Яйця", 1, UnitChoice.PCS),
            ("Пшеничне борошно", 3, UnitChoice.TBSP),
            ("Цукор", 1, UnitChoice.TBSP),
            ("Рослинна олія", 1, UnitChoice.TBSP),
        ],
        "steps": [
            {"uk": "Помістіть кисломолочний сир у миску та розімніть його до однорідної консистенції.",
             "en": "Place cottage cheese in a bowl and mash until smooth.",
             "pl": "Włóż twaróg do miski i rozgnieć do jednolitej konsystencji."},
            {"uk": "Додайте яйце, цукор і пшеничне борошно, ретельно перемішайте до утворення однорідного тіста.",
             "en": "Add egg, sugar, and flour, mix thoroughly into a uniform dough.",
             "pl": "Dodaj jajko, cukier i mąkę, dokładnie wymieszaj."},
            {"uk": "Сформуйте з тіста невеликі сирники однакового розміру.",
             "en": "Form small, equally-sized pancakes from the dough.",
             "pl": "Uformuj małe, równej wielkości placuszki."},
            {"uk": "Розігрійте сковороду та додайте рослинну олію.", "en": "Heat a frying pan and add vegetable oil.",
             "pl": "Rozgrzej patelnię i dodaj olej roślinny."},
            {
                "uk": "Викладіть сирники на сковороду та обсмажуйте на середньому вогні до утворення золотистої скоринки з обох боків.",
                "en": "Place the pancakes in the pan and fry over medium heat until golden brown on both sides.",
                "pl": "Smaż na średnim ogniu, aż będą złociste z obu stron."}
        ]
    },
    {
        "title": "Шоколадний мус",
        "title_en": "Chocolate mousse",
        "title_pl": "Mus czekoladowy",
        "description": "Легкий і повітряний десерт із насиченим шоколадним смаком. Тане в роті та дарує справжнє задоволення — ідеальний варіант для солодкого завершення дня.",
        "description_en": "A light and airy dessert with a rich chocolate flavor. Melts in your mouth and brings true pleasure - perfect for ending the day sweetly.",
        "description_pl": "Lekki i puszysty deser o bogatym smaku czekolady. Rozpływa się w ustach - idealny na słodkie zakończenie dnia.",
        "source": "Шеф-кухар SoulFood Lab Андрій Коваль",
        "source_en": "Chef of SoulFood Lab Andriy Koval",
        "source_pl": "Szef kuchni SoulFood Lab Andrij Kowal",
        "cooking_time": 140,
        "portions": 3,
        "calories": 410,
        "difficulty": Difficulty.MEDIUM,
        "cuisine": [Cuisine.FRENCH],
        "meal_times": [MealTime.SNACK],
        "dietary_tags": [Diet.VEGETARIAN],
        "dish_types": [DishType.DESSERT],
        "ingredients": [
            ("Темний шоколад", 150, UnitChoice.G),
            ("Вершки", 200, UnitChoice.ML),
            ("Цукор", 1, UnitChoice.TBSP),
            ("Яйця", 2, UnitChoice.PCS),
        ],
        "steps": [
            {"uk": "Розтопіть темний шоколад до однорідної консистенції.",
             "en": "Melt the dark chocolate until smooth.",
             "pl": "Rozpuść gorzką czekoladę do jednolitej konsystencji."},
            {"uk": "Візьміть 2 курячих яйця та відокремте жовтки від білків.",
             "en": "Separate yolks from whites of 2 eggs.", "pl": "Oddziel żółtka od białek."},
            {"uk": "Додайте жовтки до розтопленого шоколаду та ретельно перемішайте.",
             "en": "Add yolks to the melted chocolate and mix thoroughly.",
             "pl": "Dodaj żółtka do rozpuszczonej czekolady i wymieszaj."},
            {"uk": "Збийте вершки до м’яких піків.", "en": "Whip the cream to soft peaks.",
             "pl": "Ubij śmietankę na miękkie szczyty."},
            {"uk": "Збийте білки з цукром до стійкої піни.", "en": "Whip egg whites with sugar to stiff peaks.",
             "pl": "Ubij białka z cukrem na sztywną pianę."},
            {"uk": "Змішайте шоколадну масу зі збитими вершками до однорідності, а потім змішайте збиті білки",
             "en": "Fold the chocolate mixture into the whipped cream, then fold in the egg whites.",
             "pl": "Wymieszaj masę czekoladową z ubitą śmietaną, a następnie z białkami."},
            {"uk": "Легкими рухами перемішайте масу до рівномірного стану.",
             "en": "Gently mix everything until evenly combined.",
             "pl": "Delikatnie wymieszaj, aż masa będzie jednolita."},
            {"uk": "Розподіліть масу по формах або порційних ємностях.",
             "en": "Divide the mousse among serving glasses.", "pl": "Rozlej mus do naczyń lub pucharków."},
            {"uk": "Охолодіть у холодильнику протягом 2 годин.", "en": "Chill in the refrigerator for 2 hours.",
             "pl": "Schładzaj w lodówce przez 2 godziny."}
        ]
    },
    {
        "title": "Вареники з картоплею",
        "title_en": "Varenyky with potatoes",
        "title_pl": "Pierogi z ziemniakami",
        "description": "Класична українська страва з ніжним тістом і ситною картопляною начинкою. Домашній смак і аромат роблять її ідеальним вибором для обіду.",
        "description_en": "A classic Ukrainian dish with delicate dough and a hearty potato filling. Homemade taste and aroma make it an ideal choice for lunch.",
        "description_pl": "Klasyczne ukraińskie danie (pierogi) z delikatnego ciasta i obfitego ziemniaczanego farszu. Domowy smak i aromat to idealny wybór na obiad.",
        "source": "Шеф-кухар SoulFood Lab Андрій Коваль",
        "source_en": "Chef of SoulFood Lab Andriy Koval",
        "source_pl": "Szef kuchni SoulFood Lab Andrij Kowal",
        "cooking_time": 60,
        "portions": 3,
        "calories": 450,
        "difficulty": Difficulty.MEDIUM,
        "cuisine": [Cuisine.UKRAINIAN],
        "meal_times": [MealTime.LUNCH, MealTime.DINNER],
        "dietary_tags": [Diet.TRADITIONAL],
        "dish_types": [DishType.MAIN, DishType.FLOUR],
        "ingredients": [
            ("Пшеничне борошно", 300, UnitChoice.G),
            ("Вода", 150, UnitChoice.ML),
            ("Картопля", 400, UnitChoice.G),
            ("Цибуля ріпчаста", 100, UnitChoice.G),
            ("Рослинна олія", 1, UnitChoice.TBSP),
            ("Сіль", None, UnitChoice.TASTE),
            ("Перець чорний", None, UnitChoice.TASTE),
        ],
        "steps": [
            {"uk": "Просійте пшеничне борошно, додайте воду та замісіть еластичне тісто.",
             "en": "Sift the wheat flour, add water, and knead an elastic dough.",
             "pl": "Przesiej mąkę pszenną, dodaj wodę i zagnieć elastyczne ciasto."},
            {"uk": "Очистіть картоплю та відваріть до м’якості.", "en": "Peel the potatoes and boil until tender.",
             "pl": "Obierz ziemniaki i ugotuj do miękkości."},
            {"uk": "Розімніть картоплю у пюре до однорідної консистенції.",
             "en": "Mash the potatoes into a smooth puree.", "pl": "Ziemniaki ugnieć na gładkie purée."},
            {
                "uk": "Дрібно наріжте цибулю та обсмажте її до золотистого кольору, після чого додайте до картопляного пюре.",
                "en": "Finely chop the onion and fry until golden, then add to the potato puree.",
                "pl": "Drobno posiekaj cebulę i usmaż na złoty kolor, po czym dodaj do purée ziemniaczanego."},
            {"uk": "Розкачайте тісто тонким шаром та виріжте кружечки однакового розміру.",
             "en": "Roll the dough out thinly and cut out circles of equal size.",
             "pl": "Cienko rozwałkuj ciasto i wytnij równe kółka."},
            {"uk": "Викладіть картопляну начинку на кожен кружечок та щільно зліпіть краї вареників.",
             "en": "Place potato filling on each circle and tightly pinch the edges of the dumplings.",
             "pl": "Na każde kółko nałóż nadzienie ziemniaczane i mocno zlep brzegi pierogów."},
            {"uk": "Відваріть вареники у киплячій підсоленій воді до моменту їх спливання та готовності тіста.",
             "en": "Boil the varenyky in salted boiling water until they float and the dough is cooked.",
             "pl": "Gotuj pierogi we wrzącej osolonej wodzie, aż wypłyną i ciasto będzie gotowe."},
            {"uk": "Додайте обсмажену цибулю до вареників після завершення варіння.",
             "en": "Toss the varenyky with fried onions after cooking.",
             "pl": "Po ugotowaniu wymieszaj pierogi z usmażoną cebulą."}
        ]
    }
]

def run():
    print("🧹 Очищення старих рецептів...")
    Recipe.objects.all().delete()
    print("✅ Базу рецептів очищено. Починаємо завантаження нових...\n")

    base_dir = os.path.dirname(os.path.abspath(__file__))
    images_dir = os.path.join(base_dir, 'seed_recipe_images')
    extensions = ['.jpg', '.jpeg', '.png', '.webp']

    added_count = 0

    for data in RECIPES_DATA:
        print(f"🔄 Створюємо: {data['title']}...")

        recipe = Recipe.objects.create(
            title=data["title"],
            title_en=data.get("title_en"),
            title_pl=data.get("title_pl"),
            description=data["description"],
            description_en=data.get("description_en"),
            description_pl=data.get("description_pl"),
            source=data.get("source", ""),
            source_en=data.get("source_en", ""),
            source_pl=data.get("source_pl", ""),
            cooking_time=data["cooking_time"],
            portions=data["portions"],
            calories=data["calories"],
            difficulty=data["difficulty"],
            cuisine=data["cuisine"],
            meal_times=data["meal_times"],
            dietary_tags=data["dietary_tags"],
            dish_types=data["dish_types"]
        )

        if os.path.exists(images_dir):
            for ext in extensions:
                file_name_local = f"{recipe.title}{ext}"
                file_path = os.path.join(images_dir, file_name_local)

                if os.path.exists(file_path):
                    safe_name = slugify(unidecode(recipe.title))
                    file_name_db = f"{safe_name}{ext}"

                    media_path = f'recipes/images/{file_name_db}'
                    if default_storage.exists(media_path):
                        default_storage.delete(media_path)

                    with open(file_path, 'rb') as f:
                        recipe.image.save(file_name_db, File(f), save=True)
                    break

        for ing_name, amount, unit in data["ingredients"]:
            try:
                ingredient_obj = Ingredient.objects.get(name__iexact=ing_name)
                RecipeIngredient.objects.create(
                    recipe=recipe,
                    ingredient=ingredient_obj,
                    amount=amount,
                    unit=unit
                )
            except Ingredient.DoesNotExist:
                print(f"   ❌ Помилка: Інгредієнт '{ing_name}' не знайдено в базі! Пропущено.")

        for index, step_data in enumerate(data["steps"], start=1):
            RecipeStep.objects.create(
                recipe=recipe,
                step_number=index,
                text=step_data["uk"],
                text_en=step_data.get("en"),
                text_pl=step_data.get("pl")
            )

        recipe.update_seasonality()
        print(f"✅ Успішно додано: {data['title']}\n")
        added_count += 1

    print(f"🎉 Готово! Додано нових рецептів: {added_count}")

if __name__ == '__main__':
    run()