import os
import django

# Налаштування середовища Django для запуску скрипта
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'core.settings')
django.setup()

from recipes.models.ingredient import Ingredient, IngredientCategory

# Дані у форматі: ("Назва", "Категорія", Сезонний (True/False), [Місяці])
INGREDIENTS_DATA = [
    # ================= ФРУКТИ, ЯГОДИ ТА ЦИТРУСОВІ =================
    ("Інжир", "Fig", "Figa", IngredientCategory.FRUITS, True, [9, 10]),
    ("Абрикос", "Apricot", "Morela", IngredientCategory.FRUITS, True, [7, 8]),
    ("Авокадо", "Avocado", "Awokado", IngredientCategory.FRUITS, False, []),
    ("Айва", "Quince", "Pigwa", IngredientCategory.FRUITS, True, [9, 10]),
    ("Ананас", "Pineapple", "Ananas", IngredientCategory.FRUITS, False, []),
    ("Апельсин", "Orange", "Pomarańcza", IngredientCategory.FRUITS, False, []),
    ("Аґрус", "Gooseberry", "Agrest", IngredientCategory.FRUITS, True, [6, 7]),
    ("Банан", "Banana", "Banan", IngredientCategory.FRUITS, False, []),
    ("Виноград", "Grapes", "Winogrona", IngredientCategory.FRUITS, True, [8, 9, 10]),
    ("Вишня", "Cherry", "Wiśnia", IngredientCategory.FRUITS, True, [6, 7]),
    ("Гранат", "Pomegranate", "Granat", IngredientCategory.FRUITS, False, []),
    ("Грейпфрут", "Grapefruit", "Grejpfrut", IngredientCategory.FRUITS, False, []),
    ("Груша", "Pear", "Gruszka", IngredientCategory.FRUITS, True, [8, 9, 10, 11]),
    ("Диня", "Melon", "Melon", IngredientCategory.FRUITS, True, [8, 9]),
    ("Журавлина", "Cranberry", "Żurawina", IngredientCategory.FRUITS, True, [9, 10]),
    ("Кавун", "Watermelon", "Arbuz", IngredientCategory.FRUITS, True, [8, 9]),
    ("Кокос", "Coconut", "Kokos", IngredientCategory.FRUITS, False, []),
    ("Ківі", "Kiwi", "Kiwi", IngredientCategory.FRUITS, False, []),
    ("Лайм", "Lime", "Limonka", IngredientCategory.FRUITS, False, []),
    ("Лимон", "Lemon", "Cytryna", IngredientCategory.FRUITS, False, []),
    ("Лохина", "Blueberry", "Borówka", IngredientCategory.FRUITS, True, [7, 8]),
    ("Малина", "Raspberry", "Malina", IngredientCategory.FRUITS, True, [7, 8]),
    ("Манго", "Mango", "Mango", IngredientCategory.FRUITS, False, []),
    ("Мандарин", "Mandarin", "Mandarynka", IngredientCategory.FRUITS, False, []),
    ("Нектарин", "Nectarine", "Nektarynka", IngredientCategory.FRUITS, True, [7, 8]),
    ("Ожина", "Blackberry", "Jeżyna", IngredientCategory.FRUITS, True, [7, 8]),
    ("Персик", "Peach", "Brzoskwinia", IngredientCategory.FRUITS, True, [7, 8]),
    ("Полуниця", "Strawberry", "Truskawka", IngredientCategory.FRUITS, True, [5, 6]),
    ("Слива", "Plum", "Śliwka", IngredientCategory.FRUITS, True, [8, 9]),
    ("Хурма", "Persimmon", "Kaki", IngredientCategory.FRUITS, True, [9, 10]),
    ("Червона смородина", "Red currant", "Czerwona porzeczka", IngredientCategory.FRUITS, True, [6, 7]),
    ("Черешня", "Sweet cherry", "Czereśnia", IngredientCategory.FRUITS, True, [6, 7]),
    ("Чорна смородина", "Black currant", "Czarna porzeczka", IngredientCategory.FRUITS, True, [6, 7]),
    ("Чорниця", "Bilberry", "Jagoda", IngredientCategory.FRUITS, True, [7, 8]),
    ("Яблуко", "Apple", "Jabłko", IngredientCategory.FRUITS, True, [8, 9, 10, 11]),

    # ================= СПЕЦІЇ ТА ПРИПРАВИ (І РІДИНИ) =================
    ("Бульйон", "Broth", "Bulion", IngredientCategory.OILS_LIQUIDS, False, []),
    ("Вода", "Water", "Woda", IngredientCategory.OILS_LIQUIDS, False, []),
    ("Лимонний сік", "Lemon juice", "Sok z cytryny", IngredientCategory.OILS_LIQUIDS, False, []),
    ("Овочевий бульйон", "Vegetable broth", "Bulion warzywny", IngredientCategory.OILS_LIQUIDS, False, []),
    ("Оливкова олія", "Olive oil", "Oliwa z oliwek", IngredientCategory.OILS_LIQUIDS, False, []),
    ("Рослинна олія", "Vegetable oil", "Olej roślinny", IngredientCategory.OILS_LIQUIDS, False, []),
    ("Томатна паста", "Tomato paste", "Koncentrat pomidorowy", IngredientCategory.OILS_LIQUIDS, False, []),
    ("Орегано", "Oregano", "Oregano", IngredientCategory.SPICES, False, []),
    ("Перець", "Pepper", "Pieprz", IngredientCategory.SPICES, False, []),
    ("Сіль", "Salt", "Sól", IngredientCategory.SPICES, False, []),

    # ================= СИРИ =================
    ("Бринза", "Bryndza", "Bryndza", IngredientCategory.CHEESE, False, []),
    ("Брі", "Brie", "Brie", IngredientCategory.CHEESE, False, []),
    ("Гауда", "Gouda", "Gouda", IngredientCategory.CHEESE, False, []),
    ("Голландський сир", "Dutch cheese", "Ser holenderski", IngredientCategory.CHEESE, False, []),
    ("Горгонзола", "Gorgonzola", "Gorgonzola", IngredientCategory.CHEESE, False, []),
    ("Дорблю", "Dorblu", "Dorblu", IngredientCategory.CHEESE, False, []),
    ("Едам", "Edam", "Edam", IngredientCategory.CHEESE, False, []),
    ("Камамбер", "Camembert", "Camembert", IngredientCategory.CHEESE, False, []),
    ("Кисломолочний сир", "Cottage cheese", "Twaróg", IngredientCategory.CHEESE, False, []),
    ("Крем-сир", "Cream cheese", "Serek śmietankowy", IngredientCategory.CHEESE, False, []),
    ("Маскарпоне", "Mascarpone", "Mascarpone", IngredientCategory.CHEESE, False, []),
    ("Моцарела", "Mozzarella", "Mozzarella", IngredientCategory.CHEESE, False, []),
    ("Пармезан", "Parmesan", "Parmezan", IngredientCategory.CHEESE, False, []),
    ("Рокфор", "Roquefort", "Roquefort", IngredientCategory.CHEESE, False, []),
    ("Сулугуні", "Suluguni", "Suluguni", IngredientCategory.CHEESE, False, []),
    ("Фета", "Feta", "Feta", IngredientCategory.CHEESE, False, []),
    ("Філадельфія", "Philadelphia cheese", "Ser Philadelphia", IngredientCategory.CHEESE, False, []),
    ("Чеддер", "Cheddar", "Cheddar", IngredientCategory.CHEESE, False, []),

    # ================= РИБА ТА МОРЕПРОДУКТИ =================
    ("Лосось", "Salmon", "Łosoś", IngredientCategory.FISH_RED, False, []),
    ("Тунець", "Tuna", "Tuńczyk", IngredientCategory.FISH_RED, False, []),
    ("Форель", "Trout", "Pstrąg", IngredientCategory.FISH_RED, False, []),
    ("Філе лосося", "Salmon fillet", "Filet z łososia", IngredientCategory.FISH_RED, False, []),
    ("Восьминіг", "Octopus", "Ośmiornica", IngredientCategory.SEAFOOD, False, []),
    ("Кальмар", "Squid", "Kalmar", IngredientCategory.SEAFOOD, False, []),
    ("Креветки", "Shrimp", "Krewetki", IngredientCategory.SEAFOOD, False, []),
    ("Мідії", "Mussels", "Małże", IngredientCategory.SEAFOOD, False, []),
    ("Креветки очищені", "Peeled shrimp", "Obrane krewetki", IngredientCategory.SEAFOOD, False, []),
    ("Дорадо", "Dorado", "Dorada", IngredientCategory.FISH_WHITE, False, []),
    ("Минтай", "Pollock", "Mintaj", IngredientCategory.FISH_WHITE, False, []),
    ("Судак", "Zander", "Sandacz", IngredientCategory.FISH_WHITE, False, []),
    ("Тріска", "Cod", "Dorsz", IngredientCategory.FISH_WHITE, False, []),
    ("Хек", "Hake", "Morszczuk", IngredientCategory.FISH_WHITE, False, []),

    # ================= ОВОЧІ ТА КОРЕНЕПЛОДИ =================
    ("Артишок", "Artichoke", "Karczoch", IngredientCategory.VEGETABLES, True, [6, 7, 8]),
    ("Баклажан", "Eggplant", "Bakłażan", IngredientCategory.VEGETABLES, True, [8, 9, 10]),
    ("Батат", "Sweet potato", "Batat", IngredientCategory.VEGETABLES, True, [9, 10]),
    ("Броколі", "Broccoli", "Brokuł", IngredientCategory.VEGETABLES, True, [9, 10]),
    ("Бруква", "Rutabaga", "Brukiew", IngredientCategory.VEGETABLES, False, []),
    ("Капуста брюссельська", "Brussels sprouts", "Brukselka", IngredientCategory.VEGETABLES, True, [9, 10, 11]),
    ("Буряк", "Beetroot", "Burak", IngredientCategory.VEGETABLES, True, [9, 10, 11]),
    ("Гарбуз", "Pumpkin", "Dynia", IngredientCategory.VEGETABLES, True, [9, 10, 11]),
    ("Горох", "Peas", "Groch", IngredientCategory.VEGETABLES, True, [6, 7]),
    ("Квасоля зелена", "Green beans", "Fasolka szparagowa", IngredientCategory.VEGETABLES, True, [7, 8, 9]),
    ("Кабачок", "Zucchini", "Cukinia", IngredientCategory.VEGETABLES, True, [6, 7, 8]),
    ("Капуста білокачанна", "White cabbage", "Biała kapusta", IngredientCategory.VEGETABLES, True, [9, 10, 11]),
    ("Капуста кейл", "Kale", "Jarmuż", IngredientCategory.VEGETABLES, True, [9, 10, 11]),
    ("Капуста пекінська", "Napa cabbage", "Kapusta pekińska", IngredientCategory.VEGETABLES, True, [9, 10, 11]),
    ("Капуста савойська", "Savoy cabbage", "Kapusta włoska", IngredientCategory.VEGETABLES, True, [9, 10, 11]),
    ("Капуста цвітна", "Cauliflower", "Kalafior", IngredientCategory.VEGETABLES, True, [8, 9, 10]),
    ("Капуста червонокачанна", "Red cabbage", "Czerwona kapusta", IngredientCategory.VEGETABLES, True, [9, 10, 11]),
    ("Картопля", "Potato", "Ziemniak", IngredientCategory.VEGETABLES, True, [9, 10, 11]),
    ("Кольрабі", "Kohlrabi", "Kalarepa", IngredientCategory.VEGETABLES, True, [6, 7, 8, 9, 10]),
    ("Корінь селери", "Celery root", "Seler korzeniowy", IngredientCategory.VEGETABLES, True, [9, 10, 11]),
    ("Кукурудза", "Corn", "Kukurydza", IngredientCategory.VEGETABLES, True, [7, 8]),
    ("Морква", "Carrot", "Marchew", IngredientCategory.VEGETABLES, True, [9, 10, 11]),
    ("Огірок", "Cucumber", "Ogórek", IngredientCategory.VEGETABLES, True, [6, 7, 8, 9]),
    ("Окра", "Okra", "Okra", IngredientCategory.VEGETABLES, False, []),
    ("Пастернак", "Parsnip", "Pasternak", IngredientCategory.VEGETABLES, True, [9, 10, 11]),
    ("Патисон", "Pattypan squash", "Patison", IngredientCategory.VEGETABLES, True, [6, 7, 8]),
    ("Перець болгарський", "Bell pepper", "Papryka", IngredientCategory.VEGETABLES, True, [7, 8, 9]),
    ("Перець гострий", "Hot pepper", "Ostra papryka", IngredientCategory.VEGETABLES, True, [7, 8, 9]),
    ("Помідор", "Tomato", "Pomidor", IngredientCategory.VEGETABLES, True, [7, 8, 9]),
    ("Порей", "Leek", "Por", IngredientCategory.VEGETABLES, True, [8, 9, 10]),
    ("Редис", "Radish", "Rzodkiewka", IngredientCategory.VEGETABLES, True, [4, 5]),
    ("Редька", "Turnip", "Rzepa", IngredientCategory.VEGETABLES, True, [9, 10, 11]),
    ("Ріпа", "Turnip", "Rzepa", IngredientCategory.VEGETABLES, True, [9, 10, 11]),
    ("Спаржа", "Asparagus", "Szparagi", IngredientCategory.VEGETABLES, True, [5, 6]),
    ("Селера (стебла)", "Celery stalk", "Seler naciowy", IngredientCategory.VEGETABLES, True, [9, 10, 11]),
    ("Топінамбур", "Jerusalem artichoke", "Topinambur", IngredientCategory.VEGETABLES, True, [9, 10, 11]),
    ("Фенхель", "Fennel", "Koper włoski", IngredientCategory.VEGETABLES, True, [8, 9, 10]),
    ("Хрін", "Horseradish", "Chrzan", IngredientCategory.VEGETABLES, True, [9, 10, 11]),
    ("Цибуля зелена", "Green onion", "Szczypiorek", IngredientCategory.VEGETABLES, True, [5, 6]),
    ("Цибуля ріпчаста", "Onion", "Cebula", IngredientCategory.VEGETABLES, True, [7, 8, 9]),
    ("Цибуля червона", "Red onion", "Czerwona cebula", IngredientCategory.VEGETABLES, True, [7, 8, 9]),
    ("Цибуля шалот", "Shallot", "Szalotka", IngredientCategory.VEGETABLES, True, [7, 8, 9]),
    ("Цукіні", "Zucchini", "Cukinia", IngredientCategory.VEGETABLES, True, [6, 7, 8]),
    ("Часник", "Garlic", "Czosnek", IngredientCategory.VEGETABLES, True, [7, 8, 9]),
    ("Помідори чері", "Cherry tomatoes", "Pomidorki koktajlowe", IngredientCategory.VEGETABLES, True, [7, 8, 9]),

    # ================= МОЛОЧНІ ПРОДУКТИ ТА ЯЙЦЯ =================
    ("Вершки", "Cream", "Śmietanka", IngredientCategory.DAIRY, False, []),
    ("Вершкове масло", "Butter", "Masło", IngredientCategory.DAIRY, False, []),
    ("Йогурт", "Yogurt", "Jogurt", IngredientCategory.DAIRY, False, []),
    ("Кефір", "Kefir", "Kefir", IngredientCategory.DAIRY, False, []),
    ("Молоко", "Milk", "Mleko", IngredientCategory.DAIRY, False, []),
    ("Сметана", "Sour cream", "Śmietana", IngredientCategory.DAIRY, False, []),
    ("Яйця", "Eggs", "Jajka", IngredientCategory.DAIRY, False, []),
    ("Мигдальне молоко", "Almond milk", "Mleko migdałowe", IngredientCategory.DAIRY, False, []),

    # ================= М'ЯСО ТА ПТИЦЯ =================
    ("Брискет", "Brisket", "Mostek", IngredientCategory.MEAT_BEEF, False, []),
    ("Прайм-ріб", "Prime rib", "Antrykot", IngredientCategory.MEAT_BEEF, False, []),
    ("Рибай", "Ribeye", "Ribeye", IngredientCategory.MEAT_BEEF, False, []),
    ("Сирлоїн", "Sirloin", "Rostbef", IngredientCategory.MEAT_BEEF, False, []),
    ("Солонина", "Corned beef", "Peklowana wołowina", IngredientCategory.MEAT_BEEF, False, []),
    ("Стейк фланк", "Flank steak", "Stek z łaty", IngredientCategory.MEAT_BEEF, False, []),
    ("Стейк флет-айрон", "Flat iron steak", "Stek flat iron", IngredientCategory.MEAT_BEEF, False, []),
    ("Телятина", "Veal", "Cielęcina", IngredientCategory.MEAT_BEEF, False, []),
    ("Філе-міньйон", "Filet mignon", "Filet mignon", IngredientCategory.MEAT_BEEF, False, []),
    ("Яловича вирізка", "Beef tenderloin", "Polędwica wołowa", IngredientCategory.MEAT_BEEF, False, []),
    ("Яловича лопатка", "Beef shoulder", "Łopatka wołowa", IngredientCategory.MEAT_BEEF, False, []),
    ("Яловичий фарш", "Ground beef", "Mielona wołowina", IngredientCategory.MEAT_BEEF, False, []),
    ("Яловичі ребра", "Beef ribs", "Żeberka wołowe", IngredientCategory.MEAT_BEEF, False, []),
    ("Бекон", "Bacon", "Boczek", IngredientCategory.MEAT_PORK, False, []),
    ("Свиняча вирізка", "Pork tenderloin", "Polędwiczka wieprzowa", IngredientCategory.MEAT_PORK, False, []),
    ("Свиняча лопатка", "Pork shoulder", "Łopatka wieprzowa", IngredientCategory.MEAT_PORK, False, []),
    ("Свинячий фарш", "Ground pork", "Mielona wieprzowina", IngredientCategory.MEAT_PORK, False, []),
    ("Свинячі відбивні", "Pork chops", "Kotlety schabowe", IngredientCategory.MEAT_PORK, False, []),
    ("Свинячі ребра", "Pork ribs", "Żeberka wieprzowe", IngredientCategory.MEAT_PORK, False, []),
    # ("Свинина", IngredientCategory.MEAT_PORK, False, []),

    ("Індиче філе", "Turkey fillet", "Filet z indyka", IngredientCategory.MEAT_BIRD, False, []),
    ("Качка", "Duck", "Kaczka", IngredientCategory.MEAT_BIRD, False, []),
    ("Курка ціла", "Whole chicken", "Cały kurczak", IngredientCategory.MEAT_BIRD, False, []),
    ("Куряча грудка", "Chicken breast", "Pierś z kurczaka", IngredientCategory.MEAT_BIRD, False, []),
    ("Курячий фарш", "Ground chicken", "Mielony kurczak", IngredientCategory.MEAT_BIRD, False, []),
    ("Курячі крильця", "Chicken wings", "Skrzydełka z kurczaka", IngredientCategory.MEAT_BIRD, False, []),
    ("Курячі ніжки", "Chicken legs", "Udka z kurczaka", IngredientCategory.MEAT_BIRD, False, []),
    ("Курячі стегна", "Chicken thighs", "Uda z kurczaka", IngredientCategory.MEAT_BIRD, False, []),
    ("Фарш з індички", "Ground turkey", "Mielony indyk", IngredientCategory.MEAT_BIRD, False, []),
    ("Куряче філе", "Chicken fillet", "Filet z kurczaka", IngredientCategory.MEAT_BIRD, False, []),
    ("Ковбаса", "Sausage", "Kiełbasa", IngredientCategory.MEAT_PRODUCTS, False, []),
    ("Сосиски", "Sausages", "Parówki", IngredientCategory.MEAT_PRODUCTS, False, []),
    ("Шинка", "Ham", "Szynka", IngredientCategory.MEAT_PRODUCTS, False, []),
    ("Баранина", "Mutton", "Baranina", IngredientCategory.MEAT_OTHER, False, []),
    ("Дичина", "Game meat", "Dziczyzna", IngredientCategory.MEAT_OTHER, False, []),
    ("Козлятина", "Goat meat", "Mięso kozie", IngredientCategory.MEAT_OTHER, False, []),
    ("Оленина", "Venison", "Dziczyzna (jeleń)", IngredientCategory.MEAT_OTHER, False, []),
    ("Фарш з баранини", "Ground mutton", "Mielona baranina", IngredientCategory.MEAT_OTHER, False, []),

    # ================= КРУПИ ТА БОБОВІ =================
    ("Амарант", "Amaranth", "Amarantus", IngredientCategory.GRAINS, False, []),
    ("Булгур", "Bulgur", "Bulgur", IngredientCategory.GRAINS, False, []),
    ("Рис білий", "White rice", "Biały ryż", IngredientCategory.GRAINS, False, []),
    ("Гречка", "Buckwheat", "Gryka", IngredientCategory.GRAINS, False, []),
    ("Рис дикий", "Wild rice", "Dziki ryż", IngredientCategory.GRAINS, False, []),
    ("Рис коричневий", "Brown rice", "Brązowy ryż", IngredientCategory.GRAINS, False, []),
    ("Кіноа", "Quinoa", "Komosa ryżowa", IngredientCategory.GRAINS, False, []),
    ("Нут", "Chickpeas", "Ciecierzyca", IngredientCategory.GRAINS, False, []),
    ("Овес", "Oats", "Owies", IngredientCategory.GRAINS, False, []),
    ("Просо", "Millet", "Proso", IngredientCategory.GRAINS, False, []),
    ("Сочевиця", "Lentils", "Soczewica", IngredientCategory.GRAINS, False, []),
    ("Спельта", "Spelt", "Orkisz", IngredientCategory.GRAINS, False, []),
    ("Ячмінь", "Barley", "Jęczmień", IngredientCategory.GRAINS, False, []),
    ("Вівсяні пластівці", "Oat flakes", "Płatki owsiane", IngredientCategory.GRAINS, False, []),
    ("Паста", "Pasta", "Makaron", IngredientCategory.GRAINS, False, []),

    # ================= КОНДИТЕРСЬКІ ІНГРЕДІЄНТИ =================
    ("Шоколад", "Chocolate", "Czekolada", IngredientCategory.SWEETS, False, []),
    ("Мед", "Honey", "Miód", IngredientCategory.SWEETS, False, []),

    # ================= ЗЕЛЕНЬ ТА ТРАВИ =================
    ("Базилік", "Basil", "Bazylia", IngredientCategory.GREENS, True, [6, 7, 8, 9]),
    ("Крес-салат", "Watercress", "Rzeżucha", IngredientCategory.GREENS, True, [5, 6, 7]),
    ("Кріп", "Dill", "Koperek", IngredientCategory.GREENS, True, [5, 6, 7, 8]),
    ("Кінза", "Cilantro", "Kolendra", IngredientCategory.GREENS, True, [6, 7, 8, 9]),
    ("Листя салату", "Lettuce leaves", "Liście sałaty", IngredientCategory.GREENS, True, [5, 6, 7]),
    ("М'ята", "Mint", "Mięta", IngredientCategory.GREENS, True, [6, 7, 8, 9]),
    ("Мангольд", "Chard", "Boćwina", IngredientCategory.GREENS, True, [6, 7, 8, 9, 10]),
    ("Петрушка", "Parsley", "Pietruszka", IngredientCategory.GREENS, True, [5, 6, 7, 8]),
    ("Розмарин", "Rosemary", "Rozmaryn", IngredientCategory.GREENS, True, [6, 7, 8, 9, 10]),
    ("Рукола", "Arugula", "Rukola", IngredientCategory.GREENS, True, [5, 6, 7]),
    ("Тим'ян", "Thyme", "Tymianek", IngredientCategory.GREENS, True, [6, 7, 8, 9, 10]),
    ("Шпинат", "Spinach", "Szpinak", IngredientCategory.GREENS, True, [5, 6, 7]),
    ("Щавель", "Sorrel", "Szczaw", IngredientCategory.GREENS, True, [5, 6, 7]),

    # ================= ГРИБИ =================
    ("Білі гриби", "Porcini mushrooms", "Prawdziwki", IngredientCategory.MUSHROOMS, True, [8, 9, 10]),
    ("Гливи", "Oyster mushrooms", "Boczniaki", IngredientCategory.MUSHROOMS, False, []),
    ("Лисички", "Chanterelles", "Kurki", IngredientCategory.MUSHROOMS, True, [8, 9, 10]),
    ("Маслюки", "Slippery jacks", "Maślaki", IngredientCategory.MUSHROOMS, True, [8, 9, 10]),
    ("Опеньки", "Honey fungus", "Opieńki", IngredientCategory.MUSHROOMS, True, [8, 9, 10]),
    ("Печериці", "Champignons", "Pieczarki", IngredientCategory.MUSHROOMS, False, []),
    ("Портобелло", "Portobello", "Portobello", IngredientCategory.MUSHROOMS, False, []),
    ("Шиїтаке", "Shiitake", "Shiitake", IngredientCategory.MUSHROOMS, False, []),

    # ================= ГОРІХИ ТА НАСІННЯ =================
    ("Арахіс", "Peanuts", "Orzeszki ziemne", IngredientCategory.NUTS, False, []),
    ("Волоський горіх", "Walnut", "Orzech włoski", IngredientCategory.NUTS, False, []),
    ("Гарбузове насіння", "Pumpkin seeds", "Pestki dyni", IngredientCategory.NUTS, False, []),
    ("Кеш'ю", "Cashew", "Nerkowiec", IngredientCategory.NUTS, False, []),
    ("Мигдаль", "Almond", "Migdał", IngredientCategory.NUTS, False, []),
    ("Насіння льону", "Flax seeds", "Siemię lniane", IngredientCategory.NUTS, False, []),
    ("Насіння чіа", "Chia seeds", "Nasiona chia", IngredientCategory.NUTS, False, []),
    ("Соняшникове насіння", "Sunflower seeds", "Pestki słonecznika", IngredientCategory.NUTS, False, []),
    ("Горіхи", "Nuts", "Orzechy", IngredientCategory.NUTS, False, []),

    # ================= БОРОШНО =================
    ("Борошно з білого рису", "White rice flour", "Mąka ryżowa", IngredientCategory.FLOUR, False, []),
    ("Вівсяне борошно", "Oat flour", "Mąka owsiana", IngredientCategory.FLOUR, False, []),
    ("Кукурудзяне борошно", "Corn flour", "Mąka kukurydziana", IngredientCategory.FLOUR, False, []),
    ("Кукурудзяне борошно грубого помелу", "Cornmeal", "Mąka kukurydziana gruboziarnista", IngredientCategory.FLOUR,
     False, []),
    ("Мигдальне борошно", "Almond flour", "Mąka migdałowa", IngredientCategory.FLOUR, False, []),
    ("Пшеничне борошно", "Wheat flour", "Mąka pszenna", IngredientCategory.FLOUR, False, []),
    ("Тапіокове борошно", "Tapioca flour", "Mąka z tapioki", IngredientCategory.FLOUR, False, []),
    ("Цільнозернове борошно", "Whole wheat flour", "Mąka pełnoziarnista", IngredientCategory.FLOUR, False, []),

    # ================= АЛЬТЕРНАТИВНІ БІЛКИ =================
    ("Сейтан", "Seitan", "Seitan", IngredientCategory.ALT_PROTEIN, False, []),
    ("Текстурований рослинний білок", "Textured vegetable protein", "Białko sojowe", IngredientCategory.ALT_PROTEIN,
     False, []),
    ("Темпе", "Tempeh", "Tempeh", IngredientCategory.ALT_PROTEIN, False, []),
    ("Тофу", "Tofu", "Tofu", IngredientCategory.ALT_PROTEIN, False, []),
    ("Цукор", "Sugar", "Cukier", IngredientCategory.SWEETS, False, []),
    ("Розпушувач", "Baking powder", "Proszek do pieczenia", IngredientCategory.SWEETS, False, []),
    ("Соєвий соус", "Soy sauce", "Sos sojowy", IngredientCategory.OILS_LIQUIDS, False, []),
    ("Рисовий оцет", "Rice vinegar", "Ocet ryżowy", IngredientCategory.OILS_LIQUIDS, False, []),
    ("Кунжутна олія", "Sesame oil", "Olej sezamowy", IngredientCategory.OILS_LIQUIDS, False, []),
    ("Місо паста", "Miso paste", "Pasta miso", IngredientCategory.OILS_LIQUIDS, False, []),
    ("Водорості вакаме", "Wakame seaweed", "Glony wakame", IngredientCategory.SEAFOOD, False, []),
    ("Імбир", "Ginger", "Imbir", IngredientCategory.SPICES, False, []),
    ("Темний шоколад", "Dark chocolate", "Ciemna czekolada", IngredientCategory.SWEETS, False, []),
    ("Паприка", "Paprika", "Papryka", IngredientCategory.SPICES, False, []),
    ("М'ясний фарш", "Minced meat", "Mielone mięso", IngredientCategory.MEAT_PRODUCTS, False, []),
    ("Сир твердий", "Hard cheese", "Ser twardy", IngredientCategory.CHEESE, False, []),
    ("Панірувальні сухарі", "Breadcrumbs", "Bułka tarta", IngredientCategory.GRAINS, False, []),

    # ================= ІНГРЕДІЄНТИ =================
    ("Телячий язик", "Veal tongue", "Ozór cielęcy", IngredientCategory.MEAT_OTHER, False, []),
    ("Цукор коричневий", "Brown sugar", "Brązowy cukier", IngredientCategory.SWEETS, False, []),
    ("Цукрова пудра", "Powdered sugar", "Cukier puder", IngredientCategory.SWEETS, False, []),
    ("Желатин", "Gelatin", "Żelatyna", IngredientCategory.SPICES, False, []),
    ("Перець білий", "White pepper", "Biały pieprz", IngredientCategory.SPICES, False, []),
    ("Перець рожевий", "Pink pepper", "Różowy pieprz", IngredientCategory.SPICES, False, []),
    ("Перець зелений", "Green pepper", "Zielony pieprz", IngredientCategory.SPICES, False, []),
    ("Перець чилі", "Chili pepper", "Papryczka chili", IngredientCategory.SPICES, False, []),
    ("Кедрові горіхи", "Pine nuts", "Orzeszki piniowe", IngredientCategory.NUTS, False, []),
    ("В'ялені томати", "Sun-dried tomatoes", "Suszone pomidory", IngredientCategory.VEGETABLES, False, []),
    ("Бренді", "Brandy", "Brandy", IngredientCategory.OILS_LIQUIDS, False, []),
    ("Свинина", "Pork", "Wieprzowina", IngredientCategory.MEAT_PORK, False, []),
    ("Раки", "Crayfish", "Raki", IngredientCategory.SEAFOOD, False, []),
    ("Горошок зелений", "Green peas", "Zielony groszek", IngredientCategory.VEGETABLES, False, []),
    ("Листя цикорію", "Chicory leaves", "Liście cykorii", IngredientCategory.VEGETABLES, False, []),
    ("Мікрогрін гороху", "Pea microgreens", "Mikroliście grochu", IngredientCategory.VEGETABLES, False, []),
    ("Цибуля-порей", "Leek", "Por", IngredientCategory.VEGETABLES, False, []),
    ("Солоні огірки", "Pickles", "Ogórki kiszone", IngredientCategory.VEGETABLES, False, []),
    ("Перепелині яйця", "Quail eggs", "Jajka przepiórcze", IngredientCategory.DAIRY, False, []),
    ("Чебрець", "Thyme", "Tymianek", IngredientCategory.GREENS, False, []),
    ("Естрагон", "Tarragon", "Estragon", IngredientCategory.GREENS, False, []),
    ("Лавровий лист", "Bay leaf", "Liść laurowy", IngredientCategory.SPICES, False, []),
    ("Гірчиця", "Mustard", "Musztarda", IngredientCategory.SPICES, False, []),
    ("Букет гарні", "Bouquet garni", "Bouquet garni", IngredientCategory.SPICES, False, []),
    ("Кістки червоної риби", "Red fish bones", "Ości czerwonej ryby", IngredientCategory.FISH_RED, False, []),
    ("Перець чорний", "Black pepper", "Czarny pieprz", IngredientCategory.SPICES, False, []),
    ("Листя карі", "Curry leaves", "Liście curry", IngredientCategory.SPICES, False, []),
    ("Насіння чорної гірчиці", "Black mustard seeds", "Nasiona czarnej gorczycy", IngredientCategory.SPICES, False, []),
    ("Куркума", "Turmeric", "Kurkuma", IngredientCategory.SPICES, False, []),
    ("Кмин", "Cumin", "Kmin rzymski", IngredientCategory.SPICES, False, []),
    ("Фенхель (насіння)", "Fennel seeds", "Nasiona kopru włoskiego", IngredientCategory.SPICES, False, []),
    ("Кокосове молоко", "Coconut milk", "Mleko kokosowe", IngredientCategory.OILS_LIQUIDS, False, []),
    ("Пападам", "Papadum", "Papadum", IngredientCategory.GRAINS, False, []),
]


def run():
    print("Починаємо завантаження інгредієнтів...\n")
    added_count = 0

    for name_uk, name_en, name_pl, category, is_seasonal, months in INGREDIENTS_DATA:
        obj, created = Ingredient.objects.get_or_create(
            name=name_uk,
            defaults={
                'name_en': name_en,
                'name_pl': name_pl,
                'category': category,
                'is_seasonal': is_seasonal,
                'seasonal_months': months
            }
        )

        if created:
            print(f"✅ Додано: {name_uk}")
            added_count += 1
        else:
            # Можемо закоментувати цей принт, щоб не засмічувати консоль,
            # якщо запускатимемо кілька разів
            pass

    print(f"\n🎉 Готово! Успішно додано нових інгредієнтів: {added_count}")


if __name__ == '__main__':
    run()