from recipes.models.recipe import Difficulty, MealTime, Diet, DishType, Cuisine, UnitChoice

# Формат даних для рецептів
RECIPES_DATA_2 = [
    {
        "title": "Йогуртовий десерт з ягодами",
        "title_en": "Yogurt dessert with berries",
        "title_pl": "Deser jogurtowy z jagodami",
        "description": "Легкий і ніжний десерт із йогурту та свіжих ягід. Ідеальний варіант для перекусу або корисного солодкого.",
        "description_en": "A light and delicate dessert made with yogurt and fresh berries. An ideal option for a snack or a healthy sweet treat.",
        "description_pl": "Lekki i delikatny deser z jogurtu i świeżych owoców. Idealna opcja na przekąskę lub zdrową słodycz.",
        "source": "Шеф-кухар SoulFood Lab Андрій Коваль",
        "source_en": "Chef of SoulFood Lab Andriy Koval",
        "source_pl": "Szef kuchni SoulFood Lab Andrij Kowal",
        "cooking_time": 5,
        "portions": 1,
        "calories": 260,
        "difficulty": Difficulty.EASY,
        "cuisine": [Cuisine.EUROPEAN],
        "meal_times": [MealTime.SNACK],
        "dietary_tags": [Diet.VEGETARIAN],
        "dish_types": [DishType.DESSERT],
        "ingredients": [
            ("Йогурт", 200, UnitChoice.G),
            ("Полуниця", 50, UnitChoice.G),
            ("Чорниця", 50, UnitChoice.G),
            ("Мед", 1, UnitChoice.TSP),
            ("Горіхи", 20, UnitChoice.G),
        ],
        "steps": [
            {"uk": "Промийте ягоди під холодною водою та обсушіть. За потреби поріжте великі ягоди.",
             "en": "Wash the berries under cold water and pat dry. Cut large berries if necessary.",
             "pl": "Umyj owoce pod zimną wodą i osusz. W razie potrzeby pokrój większe owoce."},
            {"uk": "Викладіть йогурт у склянку або креманку, формуючи основу десерту.",
             "en": "Place the yogurt into a glass or bowl, forming the base of the dessert.",
             "pl": "Nałóż jogurt do szklanki lub miseczki, tworząc bazę deseru."},
            {"uk": "Рівномірно розподіліть свіжі ягоди поверх йогурту, створюючи шар або декоративну композицію.",
             "en": "Distribute the fresh berries evenly over the yogurt, creating a layer or a decorative pattern.",
             "pl": "Równomiernie rozłóż świeże owoce na jogurcie, tworząc warstwę lub dekorację."},
            {"uk": "Полийте десерт невеликою кількістю меду для легкого солодкого балансу.",
             "en": "Drizzle the dessert with a little honey for a light sweet balance.",
             "pl": "Polej deser odrobiną miodu, aby nadać mu lekką słodycz."},
            {"uk": "Посипте подрібненими горіхами для додаткової текстури та аромату.",
             "en": "Sprinkle with chopped nuts for added texture and flavor.",
             "pl": "Posyp posiekanymi orzechami dla dodatkowej tekstury i smaku."}
        ]
    },
    {
        "title": "Креветки з часником",
        "title_en": "Garlic shrimp",
        "title_pl": "Krewetki z czosnkiem",
        "description": "Ароматні креветки, обсмажені з часником і лимонним соком. Швидка та вишукана страва для легкої вечері або закуски.",
        "description_en": "Aromatic shrimp sautéed with garlic and lemon juice. A quick and elegant dish for a light dinner or appetizer.",
        "description_pl": "Aromatyczne krewetki smażone z czosnkiem i sokiem z cytryny. Szybkie i wykwintne danie na lekką kolację lub przystawkę.",
        "source": "Шеф-кухар SoulFood Lab Андрій Коваль",
        "source_en": "Chef of SoulFood Lab Andriy Koval",
        "source_pl": "Szef kuchni SoulFood Lab Andrij Kowal",
        "cooking_time": 10,
        "portions": 2,
        "calories": 230,
        "difficulty": Difficulty.MEDIUM,
        "cuisine": [Cuisine.MEDITERRANEAN],
        "meal_times": [MealTime.LUNCH, MealTime.DINNER],
        "dietary_tags": [Diet.DIETARY],
        "dish_types": [DishType.SNACK, DishType.SEAFOOD],
        "ingredients": [
            ("Креветки очищені", 300, UnitChoice.G),
            ("Часник", 3, UnitChoice.CLOVE),
            ("Оливкова олія", 1, UnitChoice.TBSP),
            ("Лимонний сік", 1, UnitChoice.TBSP),
            ("Петрушка", 10, UnitChoice.G),
            ("Сіль", None, UnitChoice.TASTE),
            ("Перець чорний", None, UnitChoice.TASTE),
        ],
        "steps": [
            {"uk": "Підготуйте креветки: за потреби розморозьте їх, промийте під холодною водою та обсушіть.",
             "en": "Prepare the shrimp: thaw if necessary, wash under cold water, and dry.",
             "pl": "Przygotuj krewetki: w razie potrzeby rozmroź, opłucz zimną wodą i osusz."},
            {"uk": "Подрібніть часник, петрушку покришіть для фінального оздоблення страви.",
             "en": "Mince the garlic and chop the parsley for the final garnish.",
             "pl": "Posiekaj czosnek, a natkę pietruszki pokrój do dekoracji dania."},
            {"uk": "Розігрійте оливкову олію на сковороді на середньо-високому вогні до легкого шипіння.",
             "en": "Heat olive oil in a pan over medium-high heat until it gently sizzles.",
             "pl": "Rozgrzej oliwę na patelni na średnio wysokim ogniu, aż zacznie lekko skwierczeć."},
            {"uk": "Додайте часник і обсмажте протягом 20–30 секунд до появи аромату, не допускаючи підгоряння.",
             "en": "Add garlic and sauté for 20-30 seconds until fragrant, not allowing it to burn.",
             "pl": "Dodaj czosnek i smaż przez 20-30 sekund do uzyskania aromatu, nie dopuszczając do przypalenia."},
            {
                "uk": "Додайте креветки та готуйте 2–3 хвилини з одного боку, потім переверніть і готуйте ще 1–2 хвилини, поки вони стануть рожевими та щільними.",
                "en": "Add the shrimp and cook 2-3 minutes on one side, then flip and cook another 1-2 minutes until pink and firm.",
                "pl": "Dodaj krewetki i smaż 2-3 minuty z jednej strony, następnie odwróć i smaż jeszcze 1-2 minuty, aż staną się różowe i jędrne."},
            {"uk": "Влийте лимонний сік та перемішайте, щоб утворився легкий соус.",
             "en": "Pour in the lemon juice and stir to create a light sauce.",
             "pl": "Wlej sok z cytryny i wymieszaj, aby powstał lekki sos."},
            {"uk": "Приправте сіллю та чорним перцем за смаком, додайте петрушку.",
             "en": "Season with salt and black pepper to taste, and add the parsley.",
             "pl": "Dopraw solą i pieprzem do smaku, dodaj pietruszkę."}
        ]
    },
    {
        "title": "Український борщ",
        "title_en": "Ukrainian borscht",
        "title_pl": "Barszcz ukraiński",
        "description": "Традиційна українська страва з насиченим смаком і ароматом. Ситний і поживний суп, який ідеально підходить для обіду.",
        "description_en": "A traditional Ukrainian dish with rich flavor and aroma. A hearty and nutritious soup that is perfect for lunch.",
        "description_pl": "Tradycyjne ukraińskie danie o bogatym smaku i aromacie. Sycąca i pożywna zupa, idealna na obiad.",
        "source": "Шеф-кухар SoulFood Lab Андрій Коваль",
        "source_en": "Chef of SoulFood Lab Andriy Koval",
        "source_pl": "Szef kuchni SoulFood Lab Andrij Kowal",
        "cooking_time": 50,
        "portions": 4,
        "calories": 350,
        "difficulty": Difficulty.HARD,
        "cuisine": [Cuisine.UKRAINIAN],
        "meal_times": [MealTime.LUNCH],
        "dietary_tags": [Diet.TRADITIONAL],
        "dish_types": [DishType.SOUP],
        "ingredients": [
            ("Буряк", 300, UnitChoice.G),
            ("Картопля", 300, UnitChoice.G),
            ("Морква", 100, UnitChoice.G),
            ("Капуста білокачанна", 200, UnitChoice.G),
            ("Цибуля ріпчаста", 100, UnitChoice.G),
            ("Томатна паста", 1, UnitChoice.TBSP),
            ("Часник", 2, UnitChoice.CLOVE),
            ("Рослинна олія", 1, UnitChoice.TBSP),
            ("Вода", 1, UnitChoice.L),
            ("Сіль", None, UnitChoice.TASTE),
            ("Перець чорний", None, UnitChoice.TASTE),
            ("Кріп", None, UnitChoice.TASTE),
        ],
        "steps": [
            {
                "uk": "Підготуйте овочі: буряк, моркву та картоплю очистіть. Буряк наріжте тонкою соломкою, моркву натріть або наріжте дрібною соломкою, картоплю — кубиками, капусту нашаткуйте, цибулю дрібно наріжте.",
                "en": "Prepare the vegetables: peel beets, carrots, and potatoes. Julienne the beets, grate or finely julienne the carrots, cube the potatoes, shred the cabbage, and finely chop the onion.",
                "pl": "Przygotuj warzywa: obierz buraki, marchew i ziemniaki. Buraki pokrój w cienkie paski, marchew zetrzyj na tarce, ziemniaki w kostkę, kapustę poszatkuj, a cebulę drobno posiekaj."},
            {
                "uk": "У каструлі розігрійте рослинну олію та обсмажте цибулю до прозорості, додайте моркву та готуйте ще 2–3 хвилини до м’якості.",
                "en": "Heat vegetable oil in a pot and sauté the onion until translucent, add carrots and cook another 2-3 minutes until soft.",
                "pl": "Rozgrzej olej w garnku i podsmaż cebulę na złoty kolor, dodaj marchew i gotuj jeszcze 2-3 minuty."},
            {
                "uk": "Додайте буряк і томатну пасту, перемішайте та тушкуйте 5–7 хвилин, щоб буряк зберіг колір і набув насиченого смаку.",
                "en": "Add the beets and tomato paste, stir and simmer for 5-7 minutes so the beets retain their color and gain a rich flavor.",
                "pl": "Dodaj buraki i koncentrat pomidorowy, wymieszaj i duś przez 5-7 minut, aby burak zachował kolor i smak."},
            {"uk": "Влийте воду, доведіть до кипіння та додайте картоплю. Варіть 10 хвилин на середньому вогні.",
             "en": "Pour in water, bring to a boil, and add the potatoes. Cook for 10 minutes over medium heat.",
             "pl": "Wlej wodę, doprowadź do wrzenia i dodaj ziemniaki. Gotuj przez 10 minut na średnim ogniu."},
            {"uk": "Додайте нашатковану капусту та продовжуйте варити ще 10–12 хвилин до м’якості овочів.",
             "en": "Add shredded cabbage and continue cooking for 10-12 minutes until vegetables are tender.",
             "pl": "Dodaj poszatkowaną kapustę i gotuj przez kolejne 10-12 minut, aż warzywa będą miękkie."},
            {"uk": "Приправте сіллю та чорним перцем за смаком.", "en": "Season with salt and black pepper to taste.",
             "pl": "Dopraw solą i czarnym pieprzem do smaku."},
            {"uk": "Наприкінці додайте подрібнений часник та свіжий кріп, перемішайте та зніміть з вогню.",
             "en": "At the end, add minced garlic and fresh dill, stir, and remove from heat.",
             "pl": "Na koniec dodaj posiekany czosnek i świeży koperek, wymieszaj i zdejmij z ognia."}
        ]
    },
    {
        "title": "Французький омлет з сиром",
        "title_en": "French omelette with cheese",
        "title_pl": "Francuski omlet z serem",
        "description": "Ніжний і повітряний омлет із розплавленим сиром — класичний варіант швидкого сніданку. Легка текстура та насичений смак.",
        "description_en": "A delicate and airy omelette with melted cheese - a classic quick breakfast. Light texture and rich flavor.",
        "description_pl": "Delikatny i puszysty omlet z roztopionym serem - klasyczny wariant na szybkie śniadanie. Lekka tekstura i bogaty smak.",
        "source": "Шеф-кухар SoulFood Lab Андрій Коваль",
        "source_en": "Chef of SoulFood Lab Andriy Koval",
        "source_pl": "Szef kuchni SoulFood Lab Andrij Kowal",
        "cooking_time": 10,
        "portions": 1,
        "calories": 300,
        "difficulty": Difficulty.EASY,
        "cuisine": [Cuisine.FRENCH],
        "meal_times": [MealTime.BREAKFAST],
        "dietary_tags": [Diet.VEGETARIAN],
        "dish_types": [DishType.OMELET],
        "ingredients": [
            ("Яйця", 3, UnitChoice.PCS),
            ("Голландський сир", 50, UnitChoice.G),
            ("Вершкове масло", 10, UnitChoice.G),
            ("Сіль", None, UnitChoice.TASTE),
            ("Перець чорний", None, UnitChoice.TASTE),
        ],
        "steps": [
            {
                "uk": "Розбийте яйця у миску та збийте їх виделкою або вінчиком до однорідної консистенції без надмірного піноутворення.",
                "en": "Crack eggs into a bowl and beat them with a fork or whisk until smooth, without over-foaming.",
                "pl": "Wbij jajka do miski i ubij widelcem lub trzepaczką do gładkości, nie doprowadzając do nadmiernego spienienia."},
            {"uk": "Приправте яйця сіллю та чорним перцем, ще раз легко перемішайте.",
             "en": "Season the eggs with salt and black pepper, mix lightly again.",
             "pl": "Dopraw jajka solą i pieprzem, jeszcze raz delikatnie wymieszaj."},
            {
                "uk": "Розігрійте сковороду на середньому або середньо-низькому вогні та додайте вершкове масло, дайте йому повністю розтанути, не допускаючи підгоряння.",
                "en": "Heat a pan over medium to medium-low heat, add butter and let it melt completely without burning.",
                "pl": "Rozgrzej patelnię na średnim ogniu, dodaj masło i pozwól mu się całkowicie rozpuścić, nie przypalając."},
            {
                "uk": "Вилийте яєчну суміш на сковороду та одразу почніть обережно рухати її лопаткою, формуючи ніжну кремову текстуру.",
                "en": "Pour the egg mixture into the pan and immediately start gently moving it with a spatula, forming a tender, creamy texture.",
                "pl": "Wlej masę jajeczną na patelnię i od razu zacznij delikatnie przesuwać ją łopatką, tworząc kremową teksturę."},
            {"uk": "Коли омлет почне підсмажуватися, рівномірно посипте тертим сиром по поверхні.",
             "en": "When the omelette begins to set, evenly sprinkle grated cheese over the surface.",
             "pl": "Gdy omlet zacznie się ścinać, równomiernie posyp go startym serem."},
            {"uk": "Складіть омлет навпіл або у форму рулету, коли середина ще залишається злегка кремовою.",
             "en": "Fold the omelette in half or roll it up while the center is still slightly creamy.",
             "pl": "Złóż omlet na pół lub zwiń w rulon, gdy środek jest jeszcze lekko kremowy."},
            {"uk": "Зніміть з вогню — страва готова", "en": "Remove from heat — the dish is ready.",
             "pl": "Zdejmij z ognia — danie jest gotowe."}
        ]
    },
    {
        "title": "Американські панкейки",
        "title_en": "American pancakes",
        "title_pl": "Amerykańskie naleśniki",
        "description": "Пухкі та ніжні панкейки — ідеальний варіант для сніданку або десерту. Чудово поєднуються з ягодами, медом або сиропом.",
        "description_en": "Fluffy and tender pancakes - an ideal option for breakfast or dessert. They pair wonderfully with berries, honey, or syrup.",
        "description_pl": "Puszyste i delikatne naleśniki – idealna opcja na śniadanie lub deser. Świetnie komponują się z jagodami, miodem lub syropem.",
        "source": "Шеф-кухар SoulFood Lab Андрій Коваль",
        "source_en": "Chef of SoulFood Lab Andriy Koval",
        "source_pl": "Szef kuchni SoulFood Lab Andrij Kowal",
        "cooking_time": 25,
        "portions": 3,
        "calories": 420,
        "difficulty": Difficulty.MEDIUM,
        "cuisine": [Cuisine.AMERICAN],
        "meal_times": [MealTime.BREAKFAST],
        "dietary_tags": [Diet.VEGETARIAN],
        "dish_types": [DishType.DESSERT, DishType.FLOUR],
        "ingredients": [
            ("Пшеничне борошно", 150, UnitChoice.G),
            ("Яйця", 1, UnitChoice.PCS),
            ("Молоко", 200, UnitChoice.ML),
            ("Цукор", 1, UnitChoice.TBSP),
            ("Розпушувач", 1, UnitChoice.TSP),
            ("Вершкове масло", 20, UnitChoice.G),
        ],
        "steps": [
            {"uk": "У великій мисці просійте пшеничне борошно, щоб уникнути грудочок.",
             "en": "In a large bowl, sift the wheat flour to avoid lumps.",
             "pl": "Do dużej miski przesiej mąkę pszenną, aby uniknąć grudek."},
            {"uk": "Додайте цукор і розпушувач, ретельно перемішайте.",
             "en": "Add sugar and baking powder, mix thoroughly.",
             "pl": "Dodaj cukier i proszek do pieczenia, dokładnie wymieszaj."},
            {
                "uk": "В окремій мисці злегка збийте яйце, додайте молоко та розтоплене вершкове масло, перемішайте до однорідності.",
                "en": "In a separate bowl, lightly beat the egg, add milk and melted butter, mix until smooth.",
                "pl": "W osobnej misce lekko ubij jajko, dodaj mleko i roztopione masło, wymieszaj do gładkości."},
            {
                "uk": "Влийте рідку суміш у сухі інгредієнти та акуратно перемішайте до об’єднання. Не вимішуйте надто довго — тісто має залишатися злегка грудкуватим.",
                "en": "Pour the wet mixture into the dry ingredients and gently mix until combined. Do not overmix - the batter should remain slightly lumpy.",
                "pl": "Wlej mokrą mieszankę do suchych składników i delikatnie wymieszaj. Nie mieszaj za długo – ciasto powinno być lekko grudkowate."},
            {"uk": "Розігрійте сковороду на середньому вогні та злегка змастіть її маслом.",
             "en": "Heat a frying pan over medium heat and lightly grease with butter.",
             "pl": "Rozgrzej patelnię na średnim ogniu i lekko natłuść masłem."},
            {"uk": "Виливайте невеликі порції тіста, формуючи панкейки бажаного розміру.",
             "en": "Pour small portions of batter to form pancakes of desired size.",
             "pl": "Wylewaj małe porcje ciasta, formując naleśniki o pożądanej wielkości."},
            {
                "uk": "Смажте до появи бульбашок на поверхні та золотистого кольору знизу, після чого переверніть і доведіть до готовності протягом ще 1–2 хвилин.",
                "en": "Cook until bubbles form on the surface and the bottom is golden brown, then flip and cook for another 1-2 minutes until done.",
                "pl": "Smaż do pojawienia się bąbelków na powierzchni, a spód będzie złoty, następnie przewróć i smaż jeszcze 1-2 minuty."}
        ]
    },
    {
        "title": "Китайський салат з огірком",
        "title_en": "Chinese cucumber salad",
        "title_pl": "Chińska sałatka z ogórkiem",
        "description": "Легкий і освіжаючий салат із пікантною заправкою. Чудовий варіант для швидкого перекусу.",
        "description_en": "A light and refreshing salad with a spicy dressing. A great option for a quick snack.",
        "description_pl": "Lekka i orzeźwiająca sałatka z pikantnym sosem. Świetna propozycja na szybką przekąskę.",
        "source": "Шеф-кухар SoulFood Lab Андрій Коваль",
        "source_en": "Chef of SoulFood Lab Andriy Koval",
        "source_pl": "Szef kuchni SoulFood Lab Andrij Kowal",
        "cooking_time": 10,
        "portions": 2,
        "calories": 140,
        "difficulty": Difficulty.EASY,
        "cuisine": [Cuisine.CHINESE],
        "meal_times": [MealTime.SNACK],
        "dietary_tags": [Diet.VEGAN],
        "dish_types": [DishType.SALAD],
        "ingredients": [
            ("Огірок", 200, UnitChoice.G),
            ("Часник", 2, UnitChoice.CLOVE),
            ("Соєвий соус", 1, UnitChoice.TBSP),
            ("Рисовий оцет", 1, UnitChoice.TSP),
            ("Кунжутна олія", 1, UnitChoice.TSP),
        ],
        "steps": [
            {"uk": "Ретельно промийте огірки та наріжте на шматочки або кружальця.",
             "en": "Thoroughly wash the cucumbers and slice into pieces or rounds.",
             "pl": "Dokładnie umyj ogórki i pokrój w plasterki lub kawałki."},
            {
                "uk": "Посоліть огірки легенько та залиште на 5 хвилин, щоб вони пустили сік, після чого злегка відтисніть.",
                "en": "Lightly salt the cucumbers and leave for 5 minutes so they release juice, then squeeze lightly.",
                "pl": "Lekko posól ogórki i odstaw na 5 minut, aby puściły sok, a następnie delikatnie wyciśnij."},
            {"uk": "Подрібніть часник для максимально інтенсивного аромату.",
             "en": "Mince the garlic for maximum intense aroma.", "pl": "Posiekaj czosnek dla maksymalnego aromatu."},
            {"uk": "У невеликій мисці змішайте соєвий соус, рисовий оцет та кунжутну олію до однорідної заправки.",
             "en": "In a small bowl, mix soy sauce, rice vinegar, and sesame oil to make a smooth dressing.",
             "pl": "W małej misce wymieszaj sos sojowy, ocet ryżowy i olej sezamowy."},
            {"uk": "Додайте подрібнений часник до заправки та перемішайте.",
             "en": "Add the minced garlic to the dressing and mix.",
             "pl": "Dodaj posiekany czosnek do sosu i wymieszaj."},
            {"uk": "Ретельно перемішайте огірки із соусом, щоб кожен шматочок був покритий заправкою.",
             "en": "Thoroughly toss the cucumbers with the sauce to coat every piece.",
             "pl": "Dokładnie wymieszaj ogórki z sosem, aby każdy kawałek był pokryty."},
            {"uk": "Залиште салат на 5–10 хвилин для насичення смаку.",
             "en": "Leave the salad for 5-10 minutes to absorb the flavors.",
             "pl": "Odstaw sałatkę na 5-10 minut, aby smaki się przegryzły."}
        ]
    },
    {
        "title": "Японський місо-суп",
        "title_en": "Japanese miso soup",
        "title_pl": "Japońska zupa miso",
        "description": "Традиційний японський суп із ніжним смаком місо та тофу. Легка і корисна страва для обіду.",
        "description_en": "A traditional Japanese soup with a delicate miso and tofu flavor. A light and healthy dish for lunch.",
        "description_pl": "Tradycyjna japońska zupa o delikatnym smaku miso i tofu. Lekkie i zdrowe danie na lunch.",
        "source": "Шеф-кухар SoulFood Lab Андрій Коваль",
        "source_en": "Chef of SoulFood Lab Andriy Koval",
        "source_pl": "Szef kuchni SoulFood Lab Andrij Kowal",
        "cooking_time": 15,
        "portions": 2,
        "calories": 180,
        "difficulty": Difficulty.MEDIUM,
        "cuisine": [Cuisine.JAPANESE],
        "meal_times": [MealTime.LUNCH],
        "dietary_tags": [Diet.VEGETARIAN],
        "dish_types": [DishType.SOUP],
        "ingredients": [
            ("Місо паста", 2, UnitChoice.TBSP),
            ("Тофу", 100, UnitChoice.G),
            ("Водорості вакаме", 5, UnitChoice.G),
            ("Цибуля зелена", 20, UnitChoice.G),
            ("Вода", 500, UnitChoice.ML),
        ],
        "steps": [
            {
                "uk": "Нагрійте воду в каструлі до гарячого стану, не доводячи до сильного кипіння, щоб зберегти делікатний смак бульйону.",
                "en": "Heat water in a pot until hot, without boiling vigorously, to preserve the delicate flavor of the broth.",
                "pl": "Podgrzej wodę w garnku, nie doprowadzając do wrzenia, aby zachować delikatny smak bulionu."},
            {"uk": "Додайте водорості вакаме та дайте їм розм’якнути протягом 2–3 хвилин.",
             "en": "Add the wakame seaweed and let it soften for 2-3 minutes.",
             "pl": "Dodaj wodorosty wakame i pozwól im zmięknąć przez 2-3 minuty."},
            {"uk": "Наріжте тофу кубиками середнього розміру, щоб він зберіг форму в супі.",
             "en": "Cut tofu into medium cubes so it retains its shape in the soup.",
             "pl": "Pokrój tofu w średnią kostkę, aby zachowało kształt w zupie."},
            {"uk": "Додайте тофу в гарячий бульйон і прогрійте 1–2 хвилини без активного кипіння.",
             "en": "Add the tofu to the hot broth and heat for 1-2 minutes without boiling vigorously.",
             "pl": "Dodaj tofu do gorącego bulionu i podgrzewaj przez 1-2 minuty bez wrzenia."},
            {"uk": "У невеликій кількості гарячого бульйону розчиніть місо пасту до однорідності, уникаючи грудочок.",
             "en": "Dissolve the miso paste in a small amount of hot broth until smooth, avoiding lumps.",
             "pl": "Rozpuść pastę miso w niewielkiej ilości gorącego bulionu, aby nie było grudek."},
            {
                "uk": "Поверніть розчинену місо пасту в каструлю та перемішайте, не доводячи суп до кипіння після цього етапу.",
                "en": "Return the dissolved miso paste to the pot and mix, without bringing the soup to a boil from this point.",
                "pl": "Wlej rozpuszczoną pastę miso do garnka i wymieszaj, nie gotując zupy."},
            {"uk": "Додайте тонко нарізану зелену цибулю перед завершенням приготування.",
             "en": "Add thinly sliced green onions just before finishing.",
             "pl": "Przed podaniem dodaj cienko pokrojoną zieloną cebulkę."}
        ]
    },
    {
        "title": "Азійський імбирний чай",
        "title_en": "Asian ginger tea",
        "title_pl": "Azjatycka herbata imbirowa",
        "description": "Теплий та зігріваючий напій із яскравим смаком імбиру. Допомагає підтримати імунітет і чудово підходить для холодної пори або як корисний щоденний напій.",
        "description_en": "A warm and soothing drink with a bright ginger flavor. Helps support immunity and is perfect for cold weather or as a healthy daily drink.",
        "description_pl": "Ciepły i rozgrzewający napój o wyrazistym smaku imbiru. Wspiera odporność i świetnie nadaje się na chłodne dni lub jako codzienny, zdrowy napój.",
        "source": "Шеф-кухар SoulFood Lab Андрій Коваль",
        "source_en": "Chef of SoulFood Lab Andriy Koval",
        "source_pl": "Szef kuchni SoulFood Lab Andrij Kowal",
        "cooking_time": 10,
        "portions": 2,
        "calories": 80,
        "difficulty": Difficulty.EASY,
        "cuisine": [Cuisine.ASIAN],
        "meal_times": [MealTime.SNACK],
        "dietary_tags": [Diet.VEGETARIAN],
        "dish_types": [DishType.DRINK],
        "ingredients": [
            ("Вода", 400, UnitChoice.ML),
            ("Імбир", 10, UnitChoice.G),
            ("Лимон", 1, UnitChoice.SLICE),
            ("Мед", 1, UnitChoice.TSP),
        ],
        "steps": [
            {
                "uk": "Підготуйте імбир: ретельно промийте корінь та наріжте його тонкими скибками або легенько розчавіть для більш інтенсивного аромату.",
                "en": "Prepare ginger: wash thoroughly and slice thinly or crush slightly for a more intense aroma.",
                "pl": "Przygotuj imbir: dokładnie umyj i pokrój w cienkie plasterki lub lekko zgnieć, aby uwolnić aromat."},
            {"uk": "Доведіть воду до кипіння в невеликій каструлі.", "en": "Bring water to a boil in a small pot.",
             "pl": "Zagotuj wodę w małym garnku."},
            {
                "uk": "Додайте імбир у киплячу воду, зменшіть вогонь і варіть на повільному кипінні 5–7 хвилин для екстракції смаку.",
                "en": "Add ginger to the boiling water, reduce the heat, and simmer for 5-7 minutes to extract flavor.",
                "pl": "Dodaj imbir do wrzącej wody, zmniejsz ogień i gotuj na wolnym ogniu przez 5-7 minut."},
            {"uk": "Зніміть з вогню та дайте чаю настоятися ще 2–3 хвилини для глибшого аромату.",
             "en": "Remove from heat and steep for another 2-3 minutes for deeper aroma.",
             "pl": "Zdejmij z ognia i odstaw herbatę na kolejne 2-3 minuty, aby smak się wzmocnił."},
            {"uk": "Додайте скибку лимона для свіжості та природної кислотності.",
             "en": "Add a slice of lemon for freshness and natural acidity.",
             "pl": "Dodaj plasterek cytryny dla świeżości."},
            {
                "uk": "Додайте мед у трохи охолоджений напій (щоб зберегти його корисні властивості) та перемішайте до повного розчинення.",
                "en": "Add honey to the slightly cooled drink (to preserve its properties) and stir until dissolved.",
                "pl": "Dodaj miód do lekko przestudzonego napoju (aby zachować jego właściwości) i wymieszaj."}
        ]
    },
    {
        "title": "Свинина запечена з часником",
        "title_en": "Roast pork with garlic",
        "title_pl": "Pieczona wieprzowina z czosnkiem",
        "description": "Соковита свиняча лопатка з насиченим ароматом часнику та спецій. Запікання дозволяє зберегти ніжність м'яса та розкрити його смак.",
        "description_en": "Juicy pork shoulder with a rich aroma of garlic and spices. Baking preserves the tenderness of the meat and reveals its flavor.",
        "description_pl": "Soczysta łopatka wieprzowa z bogatym aromatem czosnku i przypraw. Pieczenie pozwala zachować delikatność mięsa i uwolnić jego smak.",
        "source": "Шеф-кухар SoulFood Lab Андрій Коваль",
        "source_en": "Chef of SoulFood Lab Andriy Koval",
        "source_pl": "Szef kuchni SoulFood Lab Andrij Kowal",
        "cooking_time": 45,
        "portions": 2,
        "calories": 520,
        "difficulty": Difficulty.MEDIUM,
        "cuisine": [Cuisine.EUROPEAN],
        "meal_times": [MealTime.LUNCH, MealTime.DINNER],
        "dietary_tags": [Diet.TRADITIONAL],
        "dish_types": [DishType.MAIN, DishType.MEAT],
        "ingredients": [
            ("Свиняча лопатка", 400, UnitChoice.G),
            ("Часник", 3, UnitChoice.CLOVE),
            ("Оливкова олія", 1, UnitChoice.TBSP),
            ("Паприка", 1, UnitChoice.TSP),
            ("Сіль", None, UnitChoice.TASTE),
            ("Перець чорний", None, UnitChoice.TASTE),
        ],
        "steps": [
            {"uk": "Наріжте свинину шматками середнього розміру для рівномірного запікання.",
             "en": "Cut the pork into medium-sized pieces for even roasting.",
             "pl": "Pokrój wieprzowinę na średniej wielkości kawałki do równomiernego pieczenia."},
            {"uk": "Подрібніть часник.", "en": "Mince the garlic.", "pl": "Posiekaj czosnek."},
            {"uk": "Натріть м’ясо сіллю, чорним перцем і паприкою з усіх боків.",
             "en": "Rub the meat with salt, black pepper, and paprika on all sides.",
             "pl": "Natrzyj mięso solą, czarnym pieprzem i papryką ze wszystkich stron."},
            {"uk": "Додайте подрібнений часник і рівномірно розподіліть по м’ясу.",
             "en": "Add the minced garlic and distribute it evenly over the meat.",
             "pl": "Dodaj posiekany czosnek i równomiernie rozprowadź na mięsie."},
            {"uk": "Полийте оливковою олією та ретельно перемішайте, щоб спеції рівномірно покрили м’ясо.",
             "en": "Drizzle with olive oil and mix thoroughly so the spices coat the meat evenly.",
             "pl": "Polej oliwą z oliwek i dokładnie wymieszaj, aby przyprawy równomiernie pokryły mięso."},
            {"uk": "Викладіть м’ясо у форму для запікання одним рівномірним шаром.",
             "en": "Place the meat in a baking dish in an even layer.",
             "pl": "Ułóż mięso w naczyniu do pieczenia w jednej warstwie."},
            {"uk": "Розігрійте духовку до 180°C.", "en": "Preheat the oven to 180°C.",
             "pl": "Rozgrzej piekarnik do 180°C."},
            {"uk": "Запікайте приблизно 35 хвилин до повної готовності м’яса.",
             "en": "Bake for about 35 minutes until the meat is fully cooked.",
             "pl": "Piecz około 35 minut, aż mięso będzie w pełni gotowe."}
        ]
    },
    {
        "title": "Крем-суп з гарбуза",
        "title_en": "Pumpkin cream soup",
        "title_pl": "Zupa krem z dyni",
        "description": "Ніжний і кремовий суп із гарбуза з м'яким солодкуватим смаком. Легка та поживна страва, яка чудово зігріває.",
        "description_en": "Delicate and creamy pumpkin soup with a mild sweet taste. A light and nutritious dish that warms perfectly.",
        "description_pl": "Delikatna zupa krem z dyni o łagodnym, słodkawym smaku. Lekkie i pożywne danie, które świetnie rozgrzewa.",
        "source": "Шеф-кухар SoulFood Lab Андрій Коваль",
        "source_en": "Chef of SoulFood Lab Andriy Koval",
        "source_pl": "Szef kuchni SoulFood Lab Andrij Kowal",
        "cooking_time": 40,
        "portions": 3,
        "calories": 210,
        "difficulty": Difficulty.MEDIUM,
        "cuisine": [Cuisine.EUROPEAN],
        "meal_times": [MealTime.LUNCH, MealTime.DINNER],
        "dietary_tags": [Diet.VEGETARIAN],
        "dish_types": [DishType.SOUP],
        "ingredients": [
            ("Гарбуз", 400, UnitChoice.G),
            ("Картопля", 150, UnitChoice.G),
            ("Морква", 100, UnitChoice.G),
            ("Цибуля ріпчаста", 100, UnitChoice.G),
            ("Вершки", 100, UnitChoice.ML),
            ("Оливкова олія", 1, UnitChoice.TBSP),
            ("Сіль", None, UnitChoice.TASTE),
            ("Перець чорний", None, UnitChoice.TASTE),
        ],
        "steps": [
            {"uk": "Очистіть гарбуз і наріжте кубиками для рівномірного приготування.",
             "en": "Peel the pumpkin and cut it into cubes for even cooking.",
             "pl": "Obierz dynię i pokrój w kostkę do równomiernego gotowania."},
            {"uk": "Наріжте картоплю, моркву та цибулю невеликими шматками.",
             "en": "Cut potatoes, carrots, and onions into small pieces.",
             "pl": "Ziemniaki, marchew i cebulę pokrój na mniejsze kawałki."},
            {"uk": "У каструлі розігрійте оливкову олію та обсмажте цибулю до прозорості.",
             "en": "Heat olive oil in a pot and sauté the onion until translucent.",
             "pl": "W garnku rozgrzej oliwę z oliwek i zeszklij cebulę."},
            {"uk": "Додайте моркву, гарбуз і картоплю, перемішайте та злегка обсмажте 2–3 хвилини.",
             "en": "Add carrots, pumpkin, and potatoes, stir and sauté lightly for 2-3 minutes.",
             "pl": "Dodaj marchew, dynię i ziemniaki, wymieszaj i lekko podsmaż przez 2-3 minuty."},
            {"uk": "Залийте овочі водою та варіть приблизно 20 хвилин до м’якості.",
             "en": "Cover vegetables with water and cook for about 20 minutes until soft.",
             "pl": "Zalej warzywa wodą i gotuj około 20 minut, aż staną się miękkie."},
            {"uk": "Збийте масу блендером до однорідної кремової консистенції.",
             "en": "Blend the mixture with an immersion blender until smooth and creamy.",
             "pl": "Zblenduj na gładką, kremową konsystencję."},
            {"uk": "Додайте вершки, сіль і чорний перець, прогрійте до однорідності.",
             "en": "Add cream, salt, and black pepper, heat through until smooth.",
             "pl": "Dodaj śmietankę, sól i czarny pieprz, podgrzej do połączenia składników."}
        ]
    }
]