from recipes.models.recipe import Difficulty, MealTime, Diet, DishType, Cuisine, UnitChoice

# Формат даних для рецептів
RECIPES_DATA_1 = [
    {
        "title": "Вівсянка з ягодами та горіхами",
        "title_en": "Oatmeal with berries and nuts",
        "title_pl": "Owsianka z jagodami i orzechami",
        "description": "Смачний і поживний сніданок, який заряджає енергією на весь день. Поєднання ніжної вівсянки, свіжих ягід і хрустких горіхів робить страву не тільки корисною, а й дуже апетитною.",
        "description_en": "A delicious and nutritious breakfast that energizes you for the whole day. The combination of tender oatmeal, fresh berries, and crunchy nuts makes the dish not only healthy but also very appetizing.",
        "description_pl": "Pyszne i pożywne śniadanie, które dodaje energii na cały dzień. Połączenie delikatnej owsianki, świeżych jagód i chrupiących orzechów sprawia, że danie jest nie tylko zdrowe, ale i bardzo apetyczne.",
        "source": "Шеф-кухар SoulFood Lab Андрій Коваль",
        "source_en": "Chef of SoulFood Lab Andriy Koval",
        "source_pl": "Szef kuchni SoulFood Lab Andrij Kowal",
        "cooking_time": 10,
        "portions": 1,
        "calories": 320,
        "difficulty": Difficulty.EASY,
        "cuisine": [Cuisine.EUROPEAN],
        "meal_times": [MealTime.BREAKFAST],
        "dietary_tags": [Diet.VEGETARIAN],
        "dish_types": [DishType.PORRIDGE],
        "ingredients": [
            ("Вівсяні пластівці", 80, UnitChoice.G),
            ("Мигдальне молоко", 200, UnitChoice.ML),
            ("Полуниця", 50, UnitChoice.G),
            ("Чорниця", 50, UnitChoice.G),
            ("Мед", 1, UnitChoice.TSP),
            ("Волоський горіх", 20, UnitChoice.G),
        ],
        "steps": [
            {"uk": "Влийте мигдальне молоко в каструлю та доведіть до кипіння на середньому вогні.",
             "en": "Pour almond milk into a saucepan and bring to a boil over medium heat.",
             "pl": "Wlej mleko migdałowe do rondla i zagotuj na średnim ogniu."},
            {
                "uk": "Додайте вівсяні пластівці, перемішайте та варіть приблизно 5 хвилин до м’якої, кремової консистенції.",
                "en": "Add oatmeal, stir and cook for about 5 minutes until soft and creamy.",
                "pl": "Dodaj płatki owsiane, wymieszaj i gotuj około 5 minut, aż staną się miękkie i kremowe."},
            {"uk": "Тим часом промийте ягоди, а волоські горіхи злегка подрібніть.",
             "en": "Meanwhile, wash the berries and lightly chop the walnuts.",
             "pl": "W międzyczasie umyj jagody i lekko posiekaj orzechy włoskie."},
            {"uk": "Перекладіть готову вівсянку в тарілку, зверху додайте ягоди, горіхи та полийте медом.",
             "en": "Transfer the finished oatmeal to a plate, top with berries, nuts and drizzle with honey.",
             "pl": "Gotową owsiankę przełóż na talerz, ułóż na wierzchu jagody, orzechy i polej miodem."}
        ]
    },
    {
        "title": "Запечені овочі з травами",
        "title_en": "Baked vegetables with herbs",
        "title_pl": "Pieczone warzywa z ziołami",
        "description": "Ароматна страва з сезонних овочів, запечених із пряними травами та оливковою олією. Легка, корисна та насичена смаком.",
        "description_en": "A fragrant dish of seasonal vegetables baked with spicy herbs and olive oil. Light, healthy, and full of flavor.",
        "description_pl": "Aromatyczne danie z sezonowych warzyw zapiekanych z ostrymi ziołami i oliwą z oliwek. Lekkie, zdrowe i pełne smaku.",
        "source": "Шеф-кухар SoulFood Lab Андрій Коваль",
        "source_en": "Chef of SoulFood Lab Andriy Koval",
        "source_pl": "Szef kuchni SoulFood Lab Andrij Kowal",
        "cooking_time": 30,
        "portions": 2,
        "calories": 150,
        "difficulty": Difficulty.EASY,
        "cuisine": [Cuisine.MEDITERRANEAN],
        "meal_times": [MealTime.LUNCH, MealTime.DINNER],
        "dietary_tags": [Diet.VEGAN],
        "dish_types": [DishType.GARNISH],
        "ingredients": [
            ("Кабачок", 300, UnitChoice.G),
            ("Перець болгарський", 150, UnitChoice.G),
            ("Морква", 100, UnitChoice.G),
            ("Броколі", 100, UnitChoice.G),
            ("Оливкова олія", 2, UnitChoice.TBSP),
            ("Часник", 2, UnitChoice.CLOVE),
            ("Орегано", 1, UnitChoice.TSP),
            ("Сіль", None, UnitChoice.TASTE),
            ("Перець чорний", None, UnitChoice.TASTE),
        ],
        "steps": [
            {"uk": "Розігрійте духовку до 180°C.", "en": "Preheat the oven to 180°C.",
             "pl": "Rozgrzej piekarnik do 180°C."},
            {
                "uk": "Помийте овочі. Кабачок, перець і моркву наріжте великими рівномірними шматками, броколі розділіть на суцвіття.",
                "en": "Wash the vegetables. Cut the zucchini, pepper, and carrot into large even pieces, divide the broccoli into florets.",
                "pl": "Umyj warzywa. Cukinię, paprykę i marchew pokrój na duże, równe kawałki, podziel brokuły na różyczki."},
            {"uk": "Очистіть часник і дрібно подрібніть або розчавіть ножем.",
             "en": "Peel the garlic and finely chop or crush it with a knife.",
             "pl": "Obrany czosnek drobno posiekaj lub rozgnieć nożem."},
            {"uk": "Викладіть овочі на деко в один шар, додайте часник.",
             "en": "Place the vegetables on a baking sheet in one layer, add the garlic.",
             "pl": "Ułóż warzywa na blasze do pieczenia w jednej warstwie, dodaj czosnek."},
            {"uk": "Полийте оливковою олією, посипте орегано, сіллю та чорним перцем, добре перемішайте.",
             "en": "Drizzle with olive oil, sprinkle with oregano, salt and black pepper, mix well.",
             "pl": "Skrop oliwą z oliwek, posyp oregano, solą i czarnym pieprzem, dobrze wymieszaj."},
            {"uk": "Запікайте 20–25 хвилин до м’якості та легкої рум’яної скоринки.",
             "en": "Bake for 20-25 minutes until soft and lightly browned.",
             "pl": "Piecz 20-25 minut, aż będą miękkie i lekko zrumienione."}
        ]
    },
    {
        "title": "Куряче філе з лимоном та зеленню",
        "title_en": "Chicken fillet with lemon and herbs",
        "title_pl": "Filet z kurczaka z cytryną i ziołami",
        "description": "Соковите куряче філе з ніжним цитрусовим ароматом і свіжою зеленню. Легка у приготуванні страва, яка чудово підходить для обіду або вечері.",
        "description_en": "Juicy chicken fillet with a delicate citrus aroma and fresh herbs. An easy-to-prepare dish that is perfect for lunch or dinner.",
        "description_pl": "Soczysty filet z kurczaka z delikatnym cytrusowym aromatem i świeżymi ziołami. Łatwe w przygotowaniu danie, idealne na obiad lub kolację.",
        "source": "Шеф-кухар SoulFood Lab Андрій Коваль",
        "source_en": "Chef of SoulFood Lab Andriy Koval",
        "source_pl": "Szef kuchni SoulFood Lab Andrij Kowal",
        "cooking_time": 30,
        "portions": 2,
        "calories": 280,
        "difficulty": Difficulty.EASY,
        "cuisine": [Cuisine.EUROPEAN],
        "meal_times": [MealTime.LUNCH, MealTime.DINNER],
        "dietary_tags": [Diet.DIETARY],
        "dish_types": [DishType.MAIN, DishType.MEAT],
        "ingredients": [
            ("Куряче філе", 400, UnitChoice.G),
            ("Лимон", 1, UnitChoice.PCS),
            ("Оливкова олія", 2, UnitChoice.TBSP),
            ("Часник", 2, UnitChoice.CLOVE),
            ("Петрушка", 10, UnitChoice.G),
            ("Сіль", None, UnitChoice.TASTE),
            ("Перець чорний", None, UnitChoice.TASTE),
        ],
        "steps": [
            {"uk": "Промийте куряче філе. Лимон розріжте навпіл і вичавіть сік, подрібніть часник.",
             "en": "Wash the chicken fillet. Cut the lemon in half and squeeze the juice, chop the garlic.",
             "pl": "Umyj filet z kurczaka. Przekrój cytrynę na pół i wyciśnij sok, posiekaj czosnek."},
            {
                "uk": "Натріть куряче філе сіллю та чорним перцем з обох боків, залиште на 5 хвилин для легкого маринування.",
                "en": "Rub the chicken fillet with salt and black pepper on both sides, leave for 5 minutes to lightly marinate.",
                "pl": "Natrzyj filet solą i pieprzem z obu stron, odstaw na 5 minut, aby lekko się zamarynował."},
            {"uk": "У невеликій мисці змішайте оливкову олію, лимонний сік і подрібнений часник до однорідності.",
             "en": "In a small bowl, mix olive oil, lemon juice and minced garlic until smooth.",
             "pl": "W małej misce wymieszaj oliwę z oliwek, sok z cytryny i mielony czosnek do uzyskania gładkiej masy."},
            {"uk": "Викладіть куряче філе у форму для запікання та рівномірно полийте підготовленим маринадом.",
             "en": "Place the chicken fillet in a baking dish and pour the prepared marinade evenly over it.",
             "pl": "Umieść filet w naczyniu do pieczenia i równomiernie zalej przygotowaną marynatą."},
            {"uk": "Запікайте у розігрітій до 180°C духовці протягом 20–25 хвилин до готовності та рум’яної скоринки.",
             "en": "Bake in a preheated 180°C oven for 20-25 minutes until done and golden brown.",
             "pl": "Piecz w nagrzanym do 180°C piekarniku przez 20-25 minut, aż do upieczenia i zarumienienia."},
            {"uk": "Додайте дрібно нарізану петрушку після завершення приготування.",
             "en": "Add finely chopped parsley after cooking.",
             "pl": "Po ugotowaniu dodaj drobno posiekaną pietruszkę."}
        ]
    },
    {
        "title": "Салат з кіноа, авокадо та овочами",
        "title_en": "Quinoa salad with avocado and vegetables",
        "title_pl": "Sałatka z komosy ryżowej, awokado i warzyw",
        "description": "Свіжий і поживний салат із кіноа та овочів, який поєднує користь і насичений смак. Легкий, але ситний варіант для обіду або вечері.",
        "description_en": "A fresh and nutritious salad with quinoa and vegetables, combining health and rich taste. A light but satisfying option for lunch or dinner.",
        "description_pl": "Świeża i pożywna sałatka z komosą ryżową i warzywami, łącząca zdrowie i bogaty smak. Lekka, ale sycąca opcja na obiad lub kolację.",
        "source": "Шеф-кухар SoulFood Lab Андрій Коваль",
        "source_en": "Chef of SoulFood Lab Andriy Koval",
        "source_pl": "Szef kuchni SoulFood Lab Andrij Kowal",
        "cooking_time": 20,
        "portions": 2,
        "calories": 340,
        "difficulty": Difficulty.EASY,
        "cuisine": [Cuisine.MEDITERRANEAN],
        "meal_times": [MealTime.LUNCH, MealTime.DINNER],
        "dietary_tags": [Diet.VEGAN],
        "dish_types": [DishType.SALAD],
        "ingredients": [
            ("Кіноа", 100, UnitChoice.G),
            ("Авокадо", 1, UnitChoice.PCS),
            ("Огірок", 100, UnitChoice.G),
            ("Помідори чері", 100, UnitChoice.G),
            ("Листя салату", 50, UnitChoice.G),
            ("Оливкова олія", 2, UnitChoice.TBSP),
            ("Лимонний сік", 1, UnitChoice.TBSP),
            ("Сіль", None, UnitChoice.TASTE),
            ("Перець чорний", None, UnitChoice.TASTE),
        ],
        "steps": [
            {
                "uk": "Промийте кіноа під проточною водою. Відваріть у підсоленій воді у співвідношенні 1:2 приблизно 12–15 хвилин до готовності. Дайте охолонути.",
                "en": "Rinse the quinoa under running water. Boil in salted water in a 1:2 ratio for about 12-15 minutes until done. Let it cool.",
                "pl": "Opłucz komosę pod bieżącą wodą. Gotuj w osolonej wodzie w proporcji 1:2 przez około 12-15 minut. Pozostaw do ostygnięcia."},
            {
                "uk": "Підготуйте овочі: огірок наріжте кубиками, помідори чері розріжте навпіл, авокадо очистіть і наріжте скибками або кубиками.",
                "en": "Prepare the vegetables: dice the cucumber, cut the cherry tomatoes in half, peel the avocado and cut into slices or cubes.",
                "pl": "Przygotuj warzywa: ogórek pokrój w kostkę, pomidorki koktajlowe przekrój na pół, awokado obierz i pokrój w plasterki lub kostkę."},
            {"uk": "Листя салату промийте, обсушіть та порвіть руками на середні шматочки.",
             "en": "Wash the lettuce leaves, dry them and tear them by hand into medium pieces.",
             "pl": "Umyj liście sałaty, osusz i porwij rękami na średnie kawałki."},
            {"uk": "У великій мисці перемішайте охолоджену кіноа, підготовлені овочі та листя салату.",
             "en": "In a large bowl, mix the cooled quinoa, prepared vegetables, and lettuce leaves.",
             "pl": "W dużej misce wymieszaj ostudzoną komosę, przygotowane warzywa i liście sałaty."},
            {"uk": "Приготуйте заправку: змішайте оливкову олію, лимонний сік, сіль та чорний перець до однорідності.",
             "en": "Prepare the dressing: mix olive oil, lemon juice, salt, and black pepper until smooth.",
             "pl": "Przygotuj sos: wymieszaj oliwę z oliwek, sok z cytryny, sól i pieprz na gładką masę."},
            {"uk": "Додайте заправку до салату та обережно перемішайте, щоб не пошкодити структуру авокадо.",
             "en": "Add the dressing to the salad and gently toss to avoid mashing the avocado.",
             "pl": "Dodaj sos do sałatki i delikatnie wymieszaj, aby nie uszkodzić awokado."}
        ]
    },
    {
        "title": "Смузі з бананом та шпинатом",
        "title_en": "Banana and spinach smoothie",
        "title_pl": "Smoothie z bananem i szpinakiem",
        "description": "Освіжаючий і корисний напій, який поєднує солодкість банана та користь зелені. Ідеальний варіант для швидкого сніданку.",
        "description_en": "A refreshing and healthy drink that combines the sweetness of banana and the benefits of greens. Perfect for a quick breakfast.",
        "description_pl": "Orzeźwiający i zdrowy napój, który łączy w sobie słodycz banana i korzyści płynące z zieleni. Idealny na szybkie śniadanie.",
        "source": "Шеф-кухар SoulFood Lab Андрій Коваль",
        "source_en": "Chef of SoulFood Lab Andriy Koval",
        "source_pl": "Szef kuchni SoulFood Lab Andrij Kowal",
        "cooking_time": 5,
        "portions": 1,
        "calories": 190,
        "difficulty": Difficulty.EASY,
        "cuisine": [Cuisine.INTERNATIONAL],
        "meal_times": [MealTime.BREAKFAST, MealTime.SNACK],
        "dietary_tags": [Diet.VEGETARIAN],
        "dish_types": [DishType.SMOOTHIE, DishType.DRINK],
        "ingredients": [
            ("Банан", 1, UnitChoice.PCS),
            ("Шпинат", 50, UnitChoice.G),
            ("Мигдальне молоко", 200, UnitChoice.ML),
            ("Насіння чіа", 1, UnitChoice.TSP),
            ("Мед", 1, UnitChoice.TSP),
        ],
        "steps": [
            {"uk": "Очистіть банан, промийте шпинат під холодною водою та злегка обсушіть.",
             "en": "Peel the banana, wash the spinach under cold water and pat dry.",
             "pl": "Obierz banana, umyj szpinak pod zimną wodą i osusz."},
            {"uk": "У чашу блендера додайте банан, шпинат, мигдальне молоко, насіння чіа та мед.",
             "en": "In a blender, add the banana, spinach, almond milk, chia seeds, and honey.",
             "pl": "Do blendera włóż banana, szpinak, mleko migdałowe, nasiona chia i miód."},
            {
                "uk": "Збивайте на високій швидкості 30–60 секунд до отримання повністю однорідної, кремової консистенції.",
                "en": "Blend on high for 30-60 seconds until completely smooth and creamy.",
                "pl": "Miksuj na wysokich obrotach przez 30-60 sekund do uzyskania gładkiej i kremowej konsystencji."},
            {"uk": "Перелийте смузі у склянку", "en": "Pour the smoothie into a glass",
             "pl": "Przelej smoothie do szklanki"}
        ]
    },
    {
        "title": "Томатний суп з базиліком",
        "title_en": "Tomato soup with basil",
        "title_pl": "Zupa pomidorowa z bazylią",
        "description": "Легкий і ароматний суп із насиченим томатним смаком та свіжим базиліком. Чудовий варіант для обіду.",
        "description_en": "A light and aromatic soup with a rich tomato flavor and fresh basil. A great option for lunch.",
        "description_pl": "Lekka i aromatyczna zupa o bogatym smaku pomidorów i świeżej bazylii. Świetna propozycja na obiad.",
        "source": "Шеф-кухар SoulFood Lab Андрій Коваль",
        "source_en": "Chef of SoulFood Lab Andriy Koval",
        "source_pl": "Szef kuchni SoulFood Lab Andrij Kowal",
        "cooking_time": 25,
        "portions": 2,
        "calories": 120,
        "difficulty": Difficulty.EASY,
        "cuisine": [Cuisine.ITALIAN],
        "meal_times": [MealTime.LUNCH],
        "dietary_tags": [Diet.VEGAN],
        "dish_types": [DishType.SOUP],
        "ingredients": [
            ("Помідор", 400, UnitChoice.G),
            ("Цибуля ріпчаста", 100, UnitChoice.G),
            ("Часник", 2, UnitChoice.CLOVE),
            ("Базилік", 10, UnitChoice.G),
            ("Оливкова олія", 1, UnitChoice.TBSP),
            ("Овочевий бульйон", 400, UnitChoice.ML),
            ("Сіль", None, UnitChoice.TASTE),
            ("Перець чорний", None, UnitChoice.TASTE),
        ],
        "steps": [
            {"uk": "Цибулю дрібно наріжте, часник подрібніть, помідори наріжте кубиками або часточками.",
             "en": "Finely chop the onion, mince the garlic, and dice or slice the tomatoes.",
             "pl": "Cebulę drobno posiekaj, czosnek przeciśnij przez praskę, a pomidory pokrój w kostkę lub w plasterki."},
            {
                "uk": "Розігрійте оливкову олію у каструлі та обсмажте цибулю до прозорості (2–3 хвилини). Додайте часник і готуйте ще 30–60 секунд до появи аромату.",
                "en": "Heat olive oil in a saucepan and sauté the onion until translucent (2-3 minutes). Add garlic and cook for another 30-60 seconds until fragrant.",
                "pl": "Rozgrzej oliwę w rondlu i smaż cebulę, aż będzie szklista (2-3 minuty). Dodaj czosnek i smaż jeszcze 30-60 sekund."},
            {"uk": "Додайте нарізані помідори та тушкуйте 5–7 хвилин, щоб вони почали розм’якшуватися та виділяти сік.",
             "en": "Add the chopped tomatoes and simmer for 5-7 minutes until they begin to soften and release their juices.",
             "pl": "Dodaj posiekane pomidory i duś przez 5-7 minut, aż zmiękną i puszczą sok."},
            {
                "uk": "Влийте овочевий бульйон, доведіть до кипіння та варіть суп на середньому вогні приблизно 10 хвилин.",
                "en": "Pour in the vegetable broth, bring to a boil, and cook the soup over medium heat for about 10 minutes.",
                "pl": "Wlej bulion warzywny, doprowadź do wrzenia i gotuj zupę na średnim ogniu przez około 10 minut."},
            {"uk": "Зніміть з вогню та подрібніть суп блендером до однорідної кремової консистенції (за бажанням).",
             "en": "Remove from heat and blend the soup until smooth and creamy (optional).",
             "pl": "Zdejmij z ognia i zblenduj zupę na gładką, kremową konsystencję (opcjonalnie)."},
            {"uk": "Приправте сіллю та чорним перцем за смаком, додайте свіжий подрібнений базилік.",
             "en": "Season with salt and black pepper to taste, and add freshly chopped basil.",
             "pl": "Dopraw solą i czarnym pieprzem do smaku, dodaj świeżo posiekaną bazylię."}
        ]
    },
    {
        "title": "Паста з грибами та часником",
        "title_en": "Pasta with mushrooms and garlic",
        "title_pl": "Makaron z grzybami i czosnkiem",
        "description": "Ніжна паста з ароматними грибами та часником — проста, але дуже смачна страва. Ідеально підходить для швидкого обіду або вечері з італійським настроєм.",
        "description_en": "Tender pasta with fragrant mushrooms and garlic is a simple but very tasty dish. Perfect for a quick lunch or dinner with an Italian mood.",
        "description_pl": "Delikatny makaron z pachnącymi grzybami i czosnkiem – to proste, ale bardzo smaczne danie. Idealne na szybki lunch lub kolację w włoskim klimacie.",
        "source": "Шеф-кухар SoulFood Lab Андрій Коваль",
        "source_en": "Chef of SoulFood Lab Andriy Koval",
        "source_pl": "Szef kuchni SoulFood Lab Andrij Kowal",
        "cooking_time": 25,
        "portions": 2,
        "calories": 480,
        "difficulty": Difficulty.EASY,
        "cuisine": [Cuisine.ITALIAN],
        "meal_times": [MealTime.LUNCH, MealTime.DINNER],
        "dietary_tags": [Diet.VEGETARIAN],
        "dish_types": [DishType.PASTA, DishType.FLOUR],
        "ingredients": [
            ("Паста", 150, UnitChoice.G),
            ("Печериці", 200, UnitChoice.G),
            ("Часник", 2, UnitChoice.CLOVE),
            ("Оливкова олія", 2, UnitChoice.TBSP),
            ("Петрушка", 10, UnitChoice.G),
            ("Сіль", None, UnitChoice.TASTE),
            ("Перець чорний", None, UnitChoice.TASTE),
        ],
        "steps": [
            {
                "uk": "Відваріть пасту у великій кількості підсоленої води до готовності. Злийте воду, залишивши трохи рідини для соусу.",
                "en": "Boil the pasta in plenty of salted water until done. Drain, reserving a little of the cooking water for the sauce.",
                "pl": "Ugotuj makaron w dużej ilości osolonej wody. Odcedź, zachowując trochę wody z gotowania do sosu."},
            {
                "uk": "Підготуйте інгредієнти: печериці очистіть та наріжте скибками, часник подрібніть, петрушку покришіть.",
                "en": "Prepare the ingredients: clean the mushrooms and slice them, mince the garlic, chop the parsley.",
                "pl": "Przygotuj składniki: oczyść pieczarki i pokrój w plasterki, posiekaj czosnek i natkę pietruszki."},
            {"uk": "На сковороді розігрійте оливкову олію та обсмажте часник до появи аромату (30–60 секунд).",
             "en": "Heat olive oil in a pan and sauté the garlic until fragrant (30-60 seconds).",
             "pl": "Rozgrzej oliwę na patelni i podsmaż czosnek, aż zacznie pachnieć (30-60 sekund)."},
            {
                "uk": "Додайте гриби та готуйте на середньому вогні 5–7 хвилин, поки вони не зменшаться в об’ємі та не підрум’яняться.",
                "en": "Add the mushrooms and cook over medium heat for 5-7 minutes until they reduce in volume and brown slightly.",
                "pl": "Dodaj grzyby i smaż na średnim ogniu przez 5-7 minut, aż zmniejszą objętość i lekko się zarumienią."},
            {
                "uk": "Додайте відварену пасту до грибів, перемішайте та за потреби додайте трохи води від варіння для створення легкого соусу.",
                "en": "Add the cooked pasta to the mushrooms, mix, and if necessary, add a little cooking water to create a light sauce.",
                "pl": "Dodaj ugotowany makaron do grzybów, wymieszaj i w razie potrzeby dodaj odrobinę wody z gotowania, aby uzyskać lekki sos."},
            {"uk": "Приправте сіллю та чорним перцем, додайте покришену петрушку та ще раз акуратно перемішайте.",
             "en": "Season with salt and black pepper, add chopped parsley and gently toss again.",
             "pl": "Dopraw solą i pieprzem, dodaj posiekaną natkę pietruszki i delikatnie wymieszaj ponownie."}
        ]
    },
    {
        "title": "Соус гуакамоле",
        "title_en": "Guacamole sauce",
        "title_pl": "Sos guacamole",
        "description": "Класичний мексиканський соус із кремового авокадо та свіжих овочів. Чудово підходить як закуска або доповнення до основних страв.",
        "description_en": "Classic Mexican sauce with creamy avocado and fresh vegetables. Perfect as a snack or side to main dishes.",
        "description_pl": "Klasyczny meksykański sos z kremowego awokado i świeżych warzyw. Świetnie nadaje się jako przekąska lub dodatek do dań głównych.",
        "source": "Шеф-кухар SoulFood Lab Андрій Коваль",
        "source_en": "Chef of SoulFood Lab Andriy Koval",
        "source_pl": "Szef kuchni SoulFood Lab Andrij Kowal",
        "cooking_time": 10,
        "portions": 2,
        "calories": 220,
        "difficulty": Difficulty.EASY,
        "cuisine": [Cuisine.MEXICAN],
        "meal_times": [MealTime.SNACK],
        "dietary_tags": [Diet.VEGAN],
        "dish_types": [DishType.SAUCE, DishType.SNACK],
        "ingredients": [
            ("Авокадо", 2, UnitChoice.PCS),
            ("Лайм", 1, UnitChoice.PCS),
            ("Помідор", 150, UnitChoice.G),
            ("Цибуля червона", 50, UnitChoice.G),
            ("Кінза", 5, UnitChoice.G),
            ("Сіль", None, UnitChoice.TASTE),
        ],
        "steps": [
            {"uk": "Розріжте авокадо навпіл, видаліть кісточку та ложкою дістаньте м’якоть у миску.",
             "en": "Cut the avocado in half, remove the pit, and scoop the flesh into a bowl with a spoon.",
             "pl": "Przekrój awokado na pół, usuń pestkę i łyżką wydrąż miąższ do miski."},
            {"uk": "Розімніть авокадо виделкою до бажаної текстури.",
             "en": "Mash the avocado with a fork to the desired texture.",
             "pl": "Rozgnieć awokado widelcem na pożądaną konsystencję."},
            {"uk": "Дрібно наріжте помідор та червону цибулю, кінзу подрібніть.",
             "en": "Finely chop the tomato and red onion, and mince the cilantro.",
             "pl": "Drobno posiekaj pomidora i czerwoną cebulę, posiekaj kolendrę."},
            {"uk": "Додайте до авокадо нарізані овочі та акуратно перемішайте.",
             "en": "Add the chopped vegetables to the avocado and gently mix.",
             "pl": "Dodaj posiekane warzywa do awokado i delikatnie wymieszaj."},
            {
                "uk": "Видавіть сік лайма та додайте сіль за смаком, щоб підкреслити свіжість і запобігти потемнінню авокадо.",
                "en": "Squeeze the lime juice and add salt to taste to highlight freshness and prevent the avocado from browning.",
                "pl": "Wyciśnij sok z limonki i dodaj sól do smaku, aby podkreślić świeżość i zapobiec ciemnieniu awokado."},
            {"uk": "Ще раз перемішайте до однорідності, зберігаючи текстуру інгредієнтів.",
             "en": "Carefully mix once more until smooth, maintaining the texture of the ingredients.",
             "pl": "Ponownie delikatnie wymieszaj, zachowując teksturę składników."}
        ]
    },
    {
        "title": "Лосось запечений з овочами",
        "title_en": "Baked salmon with vegetables",
        "title_pl": "Łosoś pieczony z warzywami",
        "description": "Ніжний лосось у поєднанні з овочами — корисна та збалансована страва. Ідеальний варіант для легкої вечері або здорового обіду.",
        "description_en": "Tender salmon combined with vegetables is a healthy and balanced dish. Perfect for a light dinner or a healthy lunch.",
        "description_pl": "Delikatny łosoś w połączeniu z warzywami to zdrowe i zbilansowane danie. Idealne na lekką kolację lub zdrowy lunch.",
        "source": "Шеф-кухар SoulFood Lab Андрій Коваль",
        "source_en": "Chef of SoulFood Lab Andriy Koval",
        "source_pl": "Szef kuchni SoulFood Lab Andrij Kowal",
        "cooking_time": 30,
        "portions": 2,
        "calories": 450,
        "difficulty": Difficulty.EASY,
        "cuisine": [Cuisine.MEDITERRANEAN],
        "meal_times": [MealTime.LUNCH, MealTime.DINNER],
        "dietary_tags": [Diet.DIETARY],
        "dish_types": [DishType.MAIN, DishType.FISH],
        "ingredients": [
            ("Філе лосося", 300, UnitChoice.G),
            ("Броколі", 150, UnitChoice.G),
            ("Кабачок", 300, UnitChoice.G),
            ("Лимон", 0.5, UnitChoice.PCS),
            ("Оливкова олія", 1, UnitChoice.TBSP),
            ("Сіль", None, UnitChoice.TASTE),
            ("Перець чорний", None, UnitChoice.TASTE),
        ],
        "steps": [
            {
                "uk": "Броколі розділіть на суцвіття, кабачок наріжте півкільцями або слайсами. Лосось промийте та обсушіть.",
                "en": "Divide the broccoli into florets, slice the zucchini into half-moons or slices. Wash and dry the salmon.",
                "pl": "Podziel brokuły na różyczki, cukinię pokrój w półplasterki. Umyj i osusz łososia."},
            {
                "uk": "Викладіть овочі на деко, застелене пергаментом, рівномірним шаром. Злегка приправте сіллю та чорним перцем.",
                "en": "Place the vegetables in an even layer on a baking sheet lined with parchment. Lightly season with salt and black pepper.",
                "pl": "Warzywa ułóż równomierną warstwą na blasze wyłożonej papierem. Lekko dopraw solą i pieprzem."},
            {"uk": "Розмістіть філе лосося серед овочів, шкіркою вниз (якщо є шкірка).",
             "en": "Place the salmon fillet among the vegetables, skin side down (if it has skin).",
             "pl": "Umieść filet z łososia wśród warzyw, skórą do dołu (jeśli ma skórę)."},
            {
                "uk": "Полийте все оливковою олією та свіжовичавленим лимонним соком, рівномірно розподіливши по інгредієнтах.",
                "en": "Drizzle everything with olive oil and freshly squeezed lemon juice, distributing evenly over the ingredients.",
                "pl": "Całość skrop oliwą i świeżo wyciśniętym sokiem z cytryny, równomiernie rozprowadzając."},
            {
                "uk": "Запікайте у розігрітій до 180°C духовці приблизно 18–20 хвилин до готовності риби та м’якості овочів.",
                "en": "Bake in a preheated 180°C oven for about 18-20 minutes until the fish is cooked and the vegetables are tender.",
                "pl": "Piecz w nagrzanym do 180°C piekarniku przez około 18-20 minut, aż ryba będzie gotowa, a warzywa miękkie."},
            {"uk": "Дістаньте з духовки та залиште на 2–3 хвилини для отримання кращого смаку",
             "en": "Remove from the oven and let sit for 2-3 minutes for best flavor",
             "pl": "Wyjmij z piekarnika i pozostaw na 2-3 minuty dla uzyskania lepszego smaku"}
        ]
    },
    {
        "title": "Салат з нутом та овочами",
        "title_en": "Chickpea and vegetable salad",
        "title_pl": "Sałatka z ciecierzycą i warzywami",
        "description": "Поживний і ситний салат із нутом та свіжими овочами. Відмінний варіант для веганського обіду або вечері.",
        "description_en": "A nutritious and satisfying salad with chickpeas and fresh vegetables. An excellent option for a vegan lunch or dinner.",
        "description_pl": "Pożywna i sycąca sałatka z ciecierzycą i świeżymi warzywami. Doskonała opcja na wegański obiad lub kolację.",
        "source": "Шеф-кухар SoulFood Lab Андрій Коваль",
        "source_en": "Chef of SoulFood Lab Andriy Koval",
        "source_pl": "Szef kuchni SoulFood Lab Andrij Kowal",
        "cooking_time": 20,
        "portions": 2,
        "calories": 320,
        "difficulty": Difficulty.EASY,
        "cuisine": [Cuisine.MEDITERRANEAN],
        "meal_times": [MealTime.LUNCH, MealTime.DINNER],
        "dietary_tags": [Diet.VEGAN],
        "dish_types": [DishType.SALAD],
        "ingredients": [
            ("Нут", 150, UnitChoice.G),
            ("Огірок", 100, UnitChoice.G),
            ("Помідор", 300, UnitChoice.G),
            ("Петрушка", 10, UnitChoice.G),
            ("Лимонний сік", 1, UnitChoice.TBSP),
            ("Оливкова олія", 1, UnitChoice.TBSP),
            ("Сіль", None, UnitChoice.TASTE),
            ("Перець чорний", None, UnitChoice.TASTE),
        ],
        "steps": [
            {
                "uk": "Підготуйте нут: якщо використовується сухий — замочіть та відваріть до м’якості. Якщо консервований — промийте під холодною водою та дайте стекти.",
                "en": "Prepare the chickpeas: if using dried, soak and boil until soft. If canned, rinse under cold water and drain.",
                "pl": "Przygotuj ciecierzycę: suchą namocz i ugotuj. Z puszki – opłucz zimną wodą i odsącz."},
            {
                "uk": "Підготуйте овочі: огірок наріжте кубиками або півкільцями, помідори розріжте на частинки або четвертинки.",
                "en": "Prepare the vegetables: dice or slice the cucumber, cut the tomatoes into wedges or quarters.",
                "pl": "Przygotuj warzywa: ogórek pokrój w kostkę lub półplasterki, pomidory w ćwiartki lub mniejsze części."},
            {"uk": "Дрібно наріжте свіжу петрушку для аромату та свіжості страви.",
             "en": "Finely chop fresh parsley to add flavor and freshness.",
             "pl": "Drobno posiekaj świeżą pietruszkę, by dodać smaku i świeżości."},
            {"uk": "У великій мисці перемішайте нут, підготовлені овочі та зелень.",
             "en": "In a large bowl, mix the chickpeas, prepared vegetables, and herbs.",
             "pl": "W dużej misce wymieszaj ciecierzycę, przygotowane warzywa i zieleninę."},
            {"uk": "Приготуйте заправку: змішайте оливкову олію, лимонний сік, сіль та чорний перець до однорідності.",
             "en": "Make the dressing: mix olive oil, lemon juice, salt, and black pepper until smooth.",
             "pl": "Przygotuj dressing: wymieszaj oliwę z oliwek, sok z cytryny, sól i pieprz do uzyskania jednolitej konsystencji."},
            {"uk": "Додайте заправку до салату та перемішайте, щоб рівномірно покрити всі інгредієнти.",
             "en": "Add the dressing to the salad and toss to coat all ingredients evenly.",
             "pl": "Dodaj dressing do sałatki i wymieszaj, aby równomiernie pokryć wszystkie składniki."},
            {"uk": "Залиште салат на 5–10 хвилин для гармонізації смаків.",
             "en": "Let the salad sit for 5-10 minutes to allow the flavors to blend.",
             "pl": "Odstaw sałatkę na 5-10 minut, by smaki się przegryzły."}
        ]
    }
]