from recipes.models.recipe import Difficulty, MealTime, Diet, DishType, Cuisine, UnitChoice

# Формат даних для рецептів
RECIPES_DATA_5 = [
    {
        "title": "Гречка з печерицями та мигдалем",
        "title_en": "Buckwheat with mushrooms and almonds",
        "title_pl": "Kasza gryczana z pieczarkami i migdałami",
        "description": "Гречка поєднується з обсмаженими печерицями, цибулею та мигдалем. Це поживний гарнір або легка основна страва.",
        "description_en": "Buckwheat is combined with roasted mushrooms, onions, and almonds. This is a nutritious side dish or a light main course.",
        "description_pl": "Kasza gryczana połączona z pieczonymi pieczarkami, cebulą i migdałami. To pożywny dodatek do dań lub lekkie danie główne.",
        "source": "Євген Клопотенко",
        "source_en": "Yevhen Klopotenko",
        "source_pl": "Jewhen Klopotenko",
        "cooking_time": 30,
        "portions": 2,
        "calories": 340,
        "difficulty": Difficulty.EASY,
        "cuisine": [Cuisine.UKRAINIAN, Cuisine.AUTHOR],
        "meal_times": [MealTime.LUNCH, MealTime.DINNER],
        "dietary_tags": [Diet.TRADITIONAL, Diet.VEGETARIAN, Diet.GLUTEN_FREE],
        "dish_types": [DishType.GARNISH, DishType.PORRIDGE],
        "ingredients": [
            ("Гречка", 150, UnitChoice.G),
            ("Вода", 300, UnitChoice.ML),
            ("Печериці", 300, UnitChoice.G),
            ("Цибуля ріпчаста", 100, UnitChoice.G),
            ("Мигдаль", 50, UnitChoice.G),
            ("Вершкове масло", 50, UnitChoice.G),
            ("Сіль", 3, UnitChoice.G),
            ("Перець чорний", 1, UnitChoice.G),
        ],
        "steps": [
            {
                "uk": "Промийте гречку і відваріть у підсоленій воді (пропорція 1:2) до повного вбирання вологи.",
                "en": "Wash the buckwheat and boil it in salted water (1:2 ratio) until the moisture is completely absorbed.",
                "pl": "Opłucz kaszę gryczaną i ugotuj w osolonej wodzie (w proporcji 1:2), aż wilgoć całkowicie się wchłonie."
            },
            {
                "uk": "Наріжте цибулю четвертинками кілець, а печериці — товстими слайсами. Сирий мигдаль грубо порубайте ножем.",
                "en": "Cut the onion into quarter rings and the mushrooms into thick slices. Roughly chop the raw almonds with a knife.",
                "pl": "Pokrój cebulę w ćwiartki krążków, a pieczarki w grube plastry. Grubo posiekaj surowe migdały nożem."
            },
            {
                "uk": "На широкій сковороді розтопіть вершкове масло. Обсмажте цибулю до стану м'якості.",
                "en": "Melt the butter in a wide pan. Sauté the onion until soft.",
                "pl": "Roztop masło na szerokiej patelni. Podsmaż cebulę, aż zmięknie."
            },
            {
                "uk": "Додайте нарізані печериці, інтенсивно смажте до випаровування вологи та появи рум'янцю; приправте сіллю і перцем. Вмішайте у грибну суміш подрібнений мигдаль.",
                "en": "Add the sliced mushrooms, fry intensively until moisture evaporates and they become browned; season with salt and pepper. Stir the chopped almonds into the mushroom mixture.",
                "pl": "Dodaj pokrojone pieczarki, intensywnie smaż, aż wilgoć wyparuje i się zarumienią; dopraw solą i pieprzem. Wymieszaj posiekane migdały z mieszanką grzybową."
            },
            {
                "uk": "Викладіть у сковороду відварену гречку, ретельно перемішайте з грибно-горіховою базою та прогрійте все разом 1-2 хвилини.",
                "en": "Place the cooked buckwheat in the pan, mix thoroughly with the mushroom-nut base, and heat everything together for 1-2 minutes.",
                "pl": "Przełóż ugotowaną kaszę gryczaną na patelnię, dokładnie wymieszaj z bazą grzybowo-orzechową i podgrzewaj wszystko razem przez 1-2 minuty."
            }
        ]
    },
    {
        "title": "Запечені яблука з рідким медом і волоськими горіхами",
        "title_en": "Baked apples with liquid honey and walnuts",
        "title_pl": "Pieczone jabłka z płynnym miodem i orzechami włoskimi",
        "description": "Яблука запікаються з медом, волоськими горіхами та вершковим маслом. Простий десерт без складної підготовки.",
        "description_en": "Apples are baked with honey, walnuts, and butter. A simple dessert without complicated preparation.",
        "description_pl": "Jabłka pieczone z miodem, orzechami włoskimi i masłem. Prosty deser bez skomplikowanego przygotowania.",
        "source": "Євген Клопотенко",
        "source_en": "Yevhen Klopotenko",
        "source_pl": "Jewhen Klopotenko",
        "cooking_time": 35,
        "portions": 4,
        "calories": 220,
        "difficulty": Difficulty.EASY,
        "cuisine": [Cuisine.UKRAINIAN],
        "meal_times": [MealTime.SNACK, MealTime.BREAKFAST],
        "dietary_tags": [Diet.VEGETARIAN, Diet.DIETARY, Diet.GLUTEN_FREE, Diet.LACTOSE_FREE],
        "dish_types": [DishType.DESSERT],
        "ingredients": [
            ("Яблуко", 600, UnitChoice.G),
            ("Мед", 40, UnitChoice.G),
            ("Волоський горіх", 100, UnitChoice.G),
            ("Вершкове масло", 20, UnitChoice.G),
        ],
        "steps": [
            {
                "uk": "Яблука ретельно вимийте. За допомогою ножа акуратно виріжте серцевину, не проткнувши дно, щоб утворилася \"чаша\" (залишайте відступ від стінок близько 0.5 см).",
                "en": "Wash the apples thoroughly. Using a knife, carefully cut out the core without piercing the bottom to form a 'bowl' (leave a margin of about 0.5 cm from the walls).",
                "pl": "Dokładnie umyj jabłka. Za pomocą noża ostrożnie wytnij gniazda nasienne, nie przebijając dna, aby utworzyć 'miseczkę' (zostaw margines około 0,5 cm od ścianek)."
            },
            {
                "uk": "Волоські горіхи подрібніть ножем або у блендері до середньої крихти.",
                "en": "Chop the walnuts with a knife or in a blender to a medium crumb.",
                "pl": "Posiekaj orzechy włoskie nożem lub w blenderze na średniej wielkości okruchy."
            },
            {
                "uk": "У кожне підготовлене яблуко щільно закладіть подрібнені горіхи.",
                "en": "Tightly pack the chopped nuts into each prepared apple.",
                "pl": "Szczelnie upchnij posiekane orzechy w każde przygotowane jabłko."
            },
            {
                "uk": "Зверху в кожне яблуко додайте по 1 ч.л. рідкого меду (близько 10 г) та маленький шматочок (5 г) вершкового масла.",
                "en": "Add 1 tsp of liquid honey (about 10 g) and a small piece (5 g) of butter on top of each apple.",
                "pl": "Na wierzch każdego jabłka dodaj 1 łyżeczkę płynnego miodu (około 10 g) i mały kawałek (5 g) masła."
            },
            {
                "uk": "Викладіть яблука на деко з пергаментом. Запікайте при 180°C протягом 15-20 хвилин до м'якості, зберігаючи структурну цілісність плоду.",
                "en": "Place the apples on a baking sheet lined with parchment paper. Bake at 180°C for 15-20 minutes until soft, maintaining the structural integrity of the fruit.",
                "pl": "Ułóż jabłka na blasze wyłożonej papierem do pieczenia. Piecz w temperaturze 180°C przez 15-20 minut do miękkości, zachowując strukturalną integralność owocu."
            }
        ]
    },
    {
        "title": "Салат Капрезе з томатами та моцарелою",
        "title_en": "Caprese salad with tomatoes and mozzarella",
        "title_pl": "Sałatka Caprese z pomidorami i mozzarellą",
        "description": "Свіжий італійський салат із стиглими томатами, ніжною моцарелою та ароматним базиліком. Ідеально підходить як легка закуска для обіду або вечері.",
        "description_en": "Fresh Italian salad with ripe tomatoes, tender mozzarella, and fragrant basil. Perfect as a light appetizer for lunch or dinner.",
        "description_pl": "Świeża włoska sałatka z dojrzałymi pomidorami, delikatną mozzarellą i pachnącą bazylią. Idealna jako lekka przekąska na lunch lub kolację.",
        "source": "Adam Bush",
        "source_en": "Adam Bush",
        "source_pl": "Adam Bush",
        "cooking_time": 10,
        "portions": 4,
        "calories": 242,
        "difficulty": Difficulty.EASY,
        "cuisine": [Cuisine.ITALIAN],
        "meal_times": [MealTime.LUNCH, MealTime.DINNER, MealTime.SNACK],
        "dietary_tags": [Diet.VEGETARIAN, Diet.GLUTEN_FREE],
        "dish_types": [DishType.COLD_SNACK, DishType.SALAD],
        "ingredients": [
            ("Помідор", 500, UnitChoice.G),
            ("Моцарела", 250, UnitChoice.G),
            ("Базилік", 15, UnitChoice.G),
            ("Оливкова олія", 30, UnitChoice.ML),
            ("Рисовий оцет", 15, UnitChoice.ML),
            ("Сіль", 3, UnitChoice.G),
            ("Перець чорний", 1, UnitChoice.G),
        ],
        "steps": [
            {"uk": "Помийте помідори та наріжте їх шматочками середньої товщини.",
             "en": "Wash the tomatoes and cut them into medium-thick slices.",
             "pl": "Umyj pomidory i pokrój je w średniej grubości plastry."},
            {"uk": "Наріжте сир Моцарела скибочками такої ж товщини, як і помідори.",
             "en": "Cut the Mozzarella cheese into slices of the same thickness as the tomatoes.",
             "pl": "Pokrój ser Mozzarella w plastry o tej samej grubości co pomidory."},
            {"uk": "Викладіть на тарілку, чергуючи: шматочок помідора, шматочок сиру.",
             "en": "Arrange on a plate, alternating: a slice of tomato, a slice of cheese.",
             "pl": "Ułóż na talerzu na przemian: plasterek pomidora, plasterek sera."},
            {"uk": "Зверху рівномірно розкладіть свіже листя базиліку.",
             "en": "Evenly distribute fresh basil leaves on top.",
             "pl": "Na wierzchu równomiernie rozłóż świeże liście bazylii."},
            {
                "uk": "Посоліть і поперчіть за смаком, після чого збризніть салат оливковою олією та рисовим оцтом. Подавайте одразу.",
                "en": "Season with salt and pepper to taste, then drizzle the salad with olive oil and rice vinegar. Serve immediately.",
                "pl": "Dopraw solą i pieprzem do smaku, a następnie skrop sałatkę oliwą z oliwek i octem ryżowym. Podawaj od razu."}
        ]
    },
    {
        "title": "Запечений Камамбер з горіхами та медом",
        "title_en": "Baked Camembert with nuts and honey",
        "title_pl": "Pieczony Camembert z orzechami i miodem",
        "description": "Гаряча закуска з розплавленим камамбером, солодким медом, волоськими горіхами та ароматом розмарину. Чудовий варіант для святкової страви або вечірнього перекусу.",
        "description_en": "Hot appetizer with melted Camembert, sweet honey, walnuts, and the aroma of rosemary. A great option for a festive dish or an evening snack.",
        "description_pl": "Gorąca przekąska z roztopionym Camembertem, słodkim miodem, orzechami włoskimi i aromatem rozmarynu. Świetna opcja na uroczyste danie lub wieczorną przekąskę.",
        "source": "Helena Busiakiewicz",
        "source_en": "Helena Busiakiewicz",
        "source_pl": "Helena Busiakiewicz",
        "cooking_time": 15,
        "portions": 4,
        "calories": 332,
        "difficulty": Difficulty.EASY,
        "cuisine": [Cuisine.FRENCH, Cuisine.EUROPEAN],
        "meal_times": [MealTime.LUNCH, MealTime.DINNER, MealTime.SNACK],
        "dietary_tags": [Diet.VEGETARIAN, Diet.GLUTEN_FREE],
        "dish_types": [DishType.HOT_SNACK, DishType.FESTIVE],
        "ingredients": [
            ("Камамбер", 250, UnitChoice.G),
            ("Волоський горіх", 75, UnitChoice.G),
            ("Мед", 50, UnitChoice.G),
            ("Паприка", 2, UnitChoice.G),
            ("Тим'ян", 2, UnitChoice.G),
            ("Розмарин", 2, UnitChoice.G),
        ],
        "steps": [
            {"uk": "Розігрійте духовку до 180°C. Зробіть ножем неглибокий хрестоподібний надріз на верхівці сиру.",
             "en": "Preheat the oven to 180°C. Make a shallow cross-shaped cut on the top of the cheese with a knife.",
             "pl": "Rozgrzej piekarnik do 180°C. Zrób płytkie, krzyżowe nacięcie nożem na wierzchu sera."},
            {"uk": "Поставте сир у духовку та випікайте камамбер, дотримуючись інструкцій на упаковці .",
             "en": "Place the cheese in the oven and bake the Camembert following the package instructions.",
             "pl": "Wstaw ser do piekarnika i piecz Camembert zgodnie z instrukcjami na opakowaniu."},
            {
                "uk": "Поки сир запікається, покладіть у невелику каструлю подрібнені горіхи, мед, паприку, розмарин і тим'ян.",
                "en": "While the cheese is baking, place the chopped nuts, honey, paprika, rosemary, and thyme in a small saucepan.",
                "pl": "Podczas gdy ser się piecze, włóż do małego rondelka posiekane orzechy, miód, paprykę, rozmaryn i tymianek."},
            {
                "uk": "Прогрійте медову суміш на слабкому вогні пару хвилин, постійно помішуючи, поки вона не стане ароматною.",
                "en": "Warm the honey mixture over low heat for a couple of minutes, stirring constantly, until fragrant.",
                "pl": "Podgrzewaj miodową mieszankę na małym ogniu przez kilka minut, ciągle mieszając, aż stanie się aromatyczna."},
            {
                "uk": "Дістаньте сир з духовки та дайте йому охолонути 3 хвилин. Полийте його гарячою медово-горіховою сумішшю та подавайте з одразу.",
                "en": "Remove the cheese from the oven and let it cool for 3 minutes. Pour the hot honey-nut mixture over it and serve immediately.",
                "pl": "Wyjmij ser z piekarnika i pozwól mu ostygnąć przez 3 minuty. Polej gorącą mieszanką miodowo-orzechową i podawaj od razu."}
        ]
    },
    {
        "title": "Хумус з нуту",
        "title_en": "Chickpea hummus",
        "title_pl": "Hummus z ciecierzycy",
        "description": "Ніжна кремова закуска з нуту з додаванням кунжутної та оливкової олій, лимонного соку і часнику. Добре підходить для поживного перекусу або як доповнення до обіду.",
        "description_en": "A tender, creamy chickpea snack with the addition of sesame and olive oils, lemon juice, and garlic. Good for a nutritious snack or as a side to lunch.",
        "description_pl": "Delikatna, kremowa przekąska z ciecierzycy z dodatkiem oleju sezamowego i oliwy z oliwek, soku z cytryny i czosnku. Idealna na pożywną przekąskę lub jako dodatek do obiadu.",
        "source": "Natasha's Kitchen",
        "source_en": "Natasha's Kitchen",
        "source_pl": "Natasha's Kitchen",
        "cooking_time": 15,
        "portions": 6,
        "calories": 180,
        "difficulty": Difficulty.EASY,
        "cuisine": [Cuisine.MEDITERRANEAN],
        "meal_times": [MealTime.LUNCH, MealTime.DINNER, MealTime.SNACK],
        "dietary_tags": [Diet.VEGAN, Diet.VEGETARIAN, Diet.GLUTEN_FREE, Diet.LACTOSE_FREE],
        "dish_types": [DishType.COLD_SNACK, DishType.SNACK],
        "ingredients": [
            ("Нут", 400, UnitChoice.G),
            ("Часник", 10, UnitChoice.G),
            ("Лимонний сік", 45, UnitChoice.ML),
            ("Оливкова олія", 45, UnitChoice.ML),
            ("Кунжутна олія", 15, UnitChoice.ML),
            ("Кмин", 2, UnitChoice.G),
            ("Сіль", 3, UnitChoice.G),
            ("Вода", 30, UnitChoice.ML),
        ],
        "steps": [
            {"uk": "Якщо використовуєте консервований нут, добре промийте його водою.",
             "en": "If using canned chickpeas, rinse them well with water.",
             "pl": "Jeśli używasz ciecierzycy z puszki, dobrze wypłucz ją wodą."},
            {
                "uk": "У чашу блендера додайте лимонний сік, кунжутну олію, оливкову олію та часник. Збийте до однорідності.",
                "en": "In a blender bowl, add lemon juice, sesame oil, olive oil, and garlic. Blend until smooth.",
                "pl": "Do kielicha blendera dodaj sok z cytryny, olej sezamowy, oliwę z oliwek i czosnek. Zblenduj na gładką masę."},
            {"uk": "Додайте в чашу нут, кмин та сіль. Почніть збивати масу.",
             "en": "Add the chickpeas, cumin, and salt to the bowl. Begin blending the mixture.",
             "pl": "Dodaj do kielicha ciecierzycę, kmin i sól. Zacznij blendować masę."},
            {"uk": "Під час збивання додайте трохи крижаної води — це зробить хумус дуже ніжним і пухким.",
             "en": "While blending, add a little ice water — this will make the hummus very tender and fluffy.",
             "pl": "Podczas blendowania dodaj trochę lodowatej wody — dzięki temu hummus będzie bardzo delikatny i puszysty."},
            {
                "uk": "Збивайте ще 2-3 хвилини до повної гладкості. Перекладіть у тарілку та полийте краплею оливкової олії.",
                "en": "Blend for another 2-3 minutes until completely smooth. Transfer to a plate and drizzle with a drop of olive oil.",
                "pl": "Blenduj jeszcze 2-3 minuty, aż będzie całkowicie gładki. Przełóż na talerz i skrop kroplą oliwy z oliwek."}
        ]
    },
    {
        "title": "Запечені гриби Портобелло з крем-сиром",
        "title_en": "Baked Portobello mushrooms with cream cheese",
        "title_pl": "Pieczone grzyby Portobello z serkiem śmietankowym",
        "description": "Ситна гаряча закуска з великих грибів портобелло, фаршированих ніжним крем-сиром і пармезаном. Відмінний вибір для легкої вечері або теплого перекусу.",
        "description_en": "A hearty hot appetizer of large portobello mushrooms stuffed with delicate cream cheese and parmesan. An excellent choice for a light dinner or a warm snack.",
        "description_pl": "Sycąca gorąca przekąska z dużych grzybów portobello faszerowanych delikatnym serkiem śmietankowym i parmezanem. Doskonały wybór na lekką kolację lub ciepłą przekąskę.",
        "source": "Джеймі Олівер",
        "source_en": "Jamie Oliver",
        "source_pl": "Jamiego Olivera",
        "cooking_time": 35,
        "portions": 4,
        "calories": 185,
        "difficulty": Difficulty.EASY,
        "cuisine": [Cuisine.ITALIAN, Cuisine.EUROPEAN],
        "meal_times": [MealTime.LUNCH, MealTime.DINNER, MealTime.SNACK],
        "dietary_tags": [Diet.VEGETARIAN, Diet.GLUTEN_FREE],
        "dish_types": [DishType.HOT_SNACK, DishType.SNACK],
        "ingredients": [
            ("Портобелло", 400, UnitChoice.G),
            ("Крем-сир", 150, UnitChoice.G),
            ("Пармезан", 40, UnitChoice.G),
            ("Лимонний сік", 10, UnitChoice.ML),
            ("Перець чилі", 5, UnitChoice.G),
            ("Орегано", 3, UnitChoice.G),
            ("Оливкова олія", 15, UnitChoice.ML),
            ("Сіль", 3, UnitChoice.G),
            ("Перець чорний", 2, UnitChoice.G),
        ],
        "steps": [
            {"uk": "Розігрійте духовку до 220°C.",
             "en": "Preheat the oven to 220°C.",
             "pl": "Rozgrzej piekarnik do 220°C."},
            {"uk": "Обережно видаліть ніжки у грибів. Змастіть капелюшки оливковою олією з усіх боків, трохи посоліть.",
             "en": "Carefully remove the stems from the mushrooms. Brush the caps with olive oil on all sides, salt slightly.",
             "pl": "Ostrożnie usuń nóżki z grzybów. Posmaruj kapelusze oliwą z oliwek ze wszystkich stron, lekko posól."},
            {"uk": "У мисці змішайте крем-сир, лимонний сік, дрібно нарізаний чилі, орегано, сіль та чорний перець.",
             "en": "In a bowl, mix cream cheese, lemon juice, finely chopped chili, oregano, salt, and black pepper.",
             "pl": "W misce wymieszaj serek śmietankowy, sok z cytryny, drobno posiekane chili, oregano, sól i czarny pieprz."},
            {"uk": "Викладіть гриби на деко і наповніть капелюшки сирною начинкою.",
             "en": "Place the mushrooms on a baking sheet and fill the caps with the cheese filling.",
             "pl": "Ułóż grzyby na blasze do pieczenia i wypełnij kapelusze farszem serowym."},
            {"uk": "Посипте зверху натертим Пармезаном і запікайте 15 хвилин до золотистої скоринки.",
             "en": "Sprinkle with grated Parmesan on top and bake for 15 minutes until golden brown.",
             "pl": "Posyp po wierzchu startym parmezanem i piecz przez 15 minut na złoty kolor."}
        ]
    },
    {
        "title": "Класичний лимонад",
        "title_en": "Classic lemonade",
        "title_pl": "Klasyczna lemoniada",
        "description": "Освіжаючий напій із лимонного соку, цедри та м'яти з приємною кисло-солодкою ноткою. Ідеально підходить для втамування спраги під час обіду або перекусу у спекотні дні.",
        "description_en": "A refreshing drink made from lemon juice, zest, and mint with a pleasant sweet and sour note. Perfect for quenching your thirst during lunch or a snack on hot days.",
        "description_pl": "Orzeźwiający napój z soku z cytryny, skórki i mięty o przyjemnej słodko-kwaśnej nucie. Idealny do ugaszenia pragnienia podczas lunchu lub przekąski w gorące dni.",
        "source": "Євген Клопотенко",
        "source_en": "Yevhen Klopotenko",
        "source_pl": "Jewhen Klopotenko",
        "cooking_time": 30,
        "portions": 5,
        "calories": 110,
        "difficulty": Difficulty.EASY,
        "cuisine": [Cuisine.AUTHOR],
        "meal_times": [MealTime.LUNCH, MealTime.SNACK],
        "dietary_tags": [Diet.VEGAN, Diet.GLUTEN_FREE, Diet.LACTOSE_FREE],
        "dish_types": [DishType.DRINK],
        "ingredients": [
            ("Лимон", 3, UnitChoice.PCS),
            ("Вода", 2000, UnitChoice.ML),
            ("Цукор", 150, UnitChoice.G),
            ("М'ята", 10, UnitChoice.G),
        ],
        "steps": [
            {"uk": "Зріжте жовту цедру з двох лимонів, намагаючись не чіпати білу частину. Вичавіть з цих лимонів сік.",
             "en": "Cut the yellow zest from two lemons, trying not to touch the white pith. Squeeze the juice from these lemons.",
             "pl": "Zetnij żółtą skórkę z dwóch cytryn, starając się nie dotykać białej części. Wyciśnij sok z tych cytryn."},
            {"uk": "Третій лимон наріжте гарними кружальцями для подачі.",
             "en": "Slice the third lemon into nice rounds for serving.",
             "pl": "Trzecią cytrynę pokrój w ładne plasterki do podania."},
            {
                "uk": "У каструлю налийте 500 мл води, додайте цукор, лимонний сік та зрізану цедру. Доведіть до кипіння і поваріть 5 хвилин.",
                "en": "Pour 500 ml of water into a saucepan, add sugar, lemon juice, and the removed zest. Bring to a boil and simmer for 5 minutes.",
                "pl": "Wlej 500 ml wody do rondla, dodaj cukier, sok z cytryny i ściętą skórkę. Doprowadź do wrzenia i gotuj przez 5 minut."},
            {"uk": "Процідіть готовий сироп через сито і дайте йому повністю охолонути.",
             "en": "Strain the finished syrup through a sieve and let it cool completely.",
             "pl": "Przecedź gotowy syrop przez sitko i odstaw do całkowitego ostygnięcia."},
            {
                "uk": "У великий глечик покладіть кружальця лимона, свіжу м'яту, влийте охолоджений сироп і додайте 1500 мл холодної води. Добре перемішайте.",
                "en": "In a large pitcher, place the lemon slices, fresh mint, pour in the cooled syrup, and add 1500 ml of cold water. Mix well.",
                "pl": "Do dużego dzbanka włóż plasterki cytryny, świeżą miętę, wlej ostudzony syrop i dodaj 1500 ml zimnej wody. Dobrze wymieszaj."}
        ]
    },
    {
        "title": "Безалкогольний імбирний ель",
        "title_en": "Non-alcoholic ginger ale",
        "title_pl": "Bezalkoholowy imbirny ale",
        "description": "Пряний домашній напій на основі свіжого імбиру та лимона з легкою природною газацією. Чудово зігріває та підходить для будь-якого прийому їжі або як самостійний перекус.",
        "description_en": "A spicy homemade drink based on fresh ginger and lemon with light natural carbonation. Warms you up wonderfully and is suitable for any meal or as an independent snack.",
        "description_pl": "Pikantny domowy napój na bazie świeżego imbiru i cytryny z lekkim naturalnym nagazowaniem. Wspaniale rozgrzewa i nadaje się do każdego posiłku lub jako samodzielna przekąska.",
        "source": "Євген Клопотенко",
        "source_en": "Yevhen Klopotenko",
        "source_pl": "Jewhen Klopotenko",
        "cooking_time": 1480,
        "portions": 10,
        "calories": 85,
        "difficulty": Difficulty.MEDIUM,
        "cuisine": [Cuisine.EUROPEAN],
        "meal_times": [MealTime.BREAKFAST, MealTime.LUNCH, MealTime.DINNER, MealTime.SNACK],
        "dietary_tags": [Diet.VEGAN, Diet.GLUTEN_FREE, Diet.LACTOSE_FREE],
        "dish_types": [DishType.DRINK],
        "ingredients": [
            ("Імбир", 40, UnitChoice.G),
            ("Цукор", 40, UnitChoice.G),
            ("Лимон", 2, UnitChoice.PCS),
            ("Вода", 4000, UnitChoice.ML),
        ],
        "steps": [
            {"uk": "У великій каструлі закип'ятіть 2 літри води.",
             "en": "Boil 2 liters of water in a large pot.",
             "pl": "W dużym garnku zagotuj 2 litry wody."},
            {"uk": "Очистіть імбир, натріть його на тертці, додайте в окріп і варіть на слабкому вогні 30 хвилин.",
             "en": "Peel the ginger, grate it, add to boiling water, and simmer over low heat for 30 minutes.",
             "pl": "Obierz imbir, zetrzyj go na tarce, dodaj do wrzącej wody i gotuj na małym ogniu przez 30 minut."},
            {"uk": "Процідіть напій через сито. Відварений імбир не викидайте — він ще знадобиться.",
             "en": "Strain the drink through a sieve. Do not throw away the boiled ginger — it will still be needed.",
             "pl": "Przecedź napój przez sitko. Nie wyrzucaj ugotowanego imbiru — nadal się przyda."},
            {
                "uk": "Додайте в гарячу рідину цукор і перемішайте до розчинення. Влийте лимонний сік і ще 2 літри холодної води.",
                "en": "Add sugar to the hot liquid and stir until dissolved. Pour in the lemon juice and another 2 liters of cold water.",
                "pl": "Dodaj cukier do gorącego płynu i mieszaj aż do rozpuszczenia. Wlej sok z cytryny i kolejne 2 litry zimnej wody."},
            {
                "uk": "Поверніть у напій залишки імбиру. Залиште банку при кімнатній температурі на 24 години, щоб з'явилися легкі бульбашки, потім процідіть і поставте в холодильник.",
                "en": "Return the remaining ginger to the drink. Leave the jar at room temperature for 24 hours until light bubbles appear, then strain and refrigerate.",
                "pl": "Dodaj resztki imbiru z powrotem do napoju. Pozostaw słoik w temperaturze pokojowej na 24 godziny, aż pojawią się lekkie bąbelki, następnie przecedź i wstaw do lodówki."}
        ]
    },
    {
        "title": "Ягідний смузі з мигдальним молоком",
        "title_en": "Berry smoothie with almond milk",
        "title_pl": "Smoothie jagodowe z mlekiem migdałowym",
        "description": "Густий і поживний напій із заморожених ягід, банана, вівсяних пластівців та мигдального молока. Швидкий і корисний варіант для сніданку або енергійного перекусу.",
        "description_en": "A thick and nutritious drink made from frozen berries, banana, oat flakes, and almond milk. A quick and healthy option for breakfast or an energetic snack.",
        "description_pl": "Gęsty i pożywny napój z mrożonych jagód, banana, płatków owsianych i mleka migdałowego. Szybka i zdrowa opcja na śniadanie lub energetyczną przekąskę.",
        "source": "Джеймі Олівер",
        "source_en": "Jamie Oliver",
        "source_pl": "Jamiego Olivera",
        "cooking_time": 10,
        "portions": 4,
        "calories": 160,
        "difficulty": Difficulty.EASY,
        "cuisine": [Cuisine.BRITISH, Cuisine.INTERNATIONAL],
        "meal_times": [MealTime.BREAKFAST, MealTime.SNACK],
        "dietary_tags": [Diet.VEGETARIAN],
        "dish_types": [DishType.SMOOTHIE, DishType.DRINK],
        "ingredients": [
            ("Малина", 100, UnitChoice.G),
            ("Полуниця", 100, UnitChoice.G),
            ("Мигдальне молоко", 300, UnitChoice.ML),
            ("Йогурт", 90, UnitChoice.G),
            ("Банан", 1, UnitChoice.PCS),
            ("Вівсяні пластівці", 35, UnitChoice.G),
            ("Насіння льону", 15, UnitChoice.G),
            ("Мед", 15, UnitChoice.G),
        ],
        "steps": [
            {"uk": "Очистіть банан від шкірки та наріжте його шматочками.",
             "en": "Peel the banana and cut it into pieces.",
             "pl": "Obierz banana i pokrój go na kawałki."},
            {"uk": "Помістіть заморожені ягоди, банан і йогурт у чашу блендера.",
             "en": "Place the frozen berries, banana, and yogurt in a blender bowl.",
             "pl": "Umieść zamrożone owoce, banana i jogurt w kielichu blendera."},
            {"uk": "Додайте мигдальне молоко, вівсяні пластівці, насіння льону та мед.",
             "en": "Add almond milk, oat flakes, flax seeds, and honey.",
             "pl": "Dodaj mleko migdałowe, płatki owsiane, nasiona lnu i miód."},
            {"uk": "Збивайте все на високій швидкості близько хвилини, поки маса не стане повністю однорідною.",
             "en": "Blend everything on high speed for about a minute until the mixture is completely smooth.",
             "pl": "Miksuj wszystko na wysokich obrotach przez około minutę, aż masa będzie całkowicie jednolita."},
            {"uk": "Розлийте смузі у склянки та подавайте одразу.",
             "en": "Pour the smoothie into glasses and serve immediately.",
             "pl": "Przelej smoothie do szklanek i podawaj od razu."}
        ]
    },
    {
        "title": "Гарячий шоколад від Гордона Рамзі",
        "title_en": "Gordon Ramsay's hot chocolate",
        "title_pl": "Gorąca czekolada Gordona Ramsaya",
        "description": "Насичений зігріваючий напій з темного шоколаду та молока, доповнений несподіваною ноткою оливкової олії. Ідеальний десертний напій для затишної вечері або солодкого перекусу.",
        "description_en": "A rich, warming drink made of dark chocolate and milk, complemented by an unexpected hint of olive oil. The perfect dessert drink for a cozy dinner or sweet snack.",
        "description_pl": "Bogaty, rozgrzewający napój z ciemnej czekolady i mleka, dopełniony nieoczekiwaną nutą oliwy z oliwek. Idealny napój deserowy na przytulną kolację lub słodką przekąskę.",
        "source": "Гордон Рамзі",
        "source_en": "Gordon Ramsay",
        "source_pl": "Gordona Ramsaya",
        "cooking_time": 10,
        "portions": 2,
        "calories": 340,
        "difficulty": Difficulty.EASY,
        "cuisine": [Cuisine.BRITISH, Cuisine.AUTHOR],
        "meal_times": [MealTime.SNACK, MealTime.DINNER],
        "dietary_tags": [Diet.VEGETARIAN, Diet.GLUTEN_FREE],
        "dish_types": [DishType.DRINK, DishType.DESSERT],
        "ingredients": [
            ("Молоко", 150, UnitChoice.ML),
            ("Темний шоколад", 70, UnitChoice.G),
            ("Оливкова олія", 15, UnitChoice.ML),
            ("Цукор", 15, UnitChoice.G),
            ("Сіль", 1, UnitChoice.G),
        ],
        "steps": [
            {"uk": "Дрібно порубайте темний шоколад ножем.",
             "en": "Finely chop the dark chocolate with a knife.",
             "pl": "Drobno posiekaj gorzką czekoladę nożem."},
            {"uk": "Налийте молоко в невелику каструлю і нагрійте майже до кипіння, але не кип'ятіть.",
             "en": "Pour the milk into a small saucepan and heat almost to boiling, but do not boil.",
             "pl": "Wlej mleko do małego rondelka i podgrzej prawie do wrzenia, ale nie gotuj."},
            {"uk": "Зніміть молоко з вогню. Додайте подрібнений шоколад, цукор та дрібку солі.",
             "en": "Remove the milk from the heat. Add the chopped chocolate, sugar, and a pinch of salt.",
             "pl": "Zdejmij mleko z ognia. Dodaj posiekaną czekoladę, cukier i szczyptę soli."},
            {"uk": "Добре перемішуйте вінчиком, поки шоколад повністю не розчиниться.",
             "en": "Whisk well until the chocolate is completely dissolved.",
             "pl": "Dobrze wymieszaj trzepaczką, aż czekolada całkowicie się rozpuści."},
            {"uk": "Додайте оливкову олію, ще раз енергійно перемішайте та одразу розлийте по чашках.",
             "en": "Add the olive oil, whisk vigorously again, and immediately pour into cups.",
             "pl": "Dodaj oliwę z oliwek, jeszcze raz energicznie wymieszaj i od razu rozlej do filiżanek."}
        ]
    }
]