from recipes.models.recipe import Difficulty, MealTime, Diet, DishType, Cuisine, UnitChoice

# Формат даних для рецептів
RECIPES_DATA_3 = [
    {
        "title": "Сирники",
        "title_en": "Cheesecakes",
        "title_pl": "Placuszki serowe",
        "description": "Традиційна страва з ніжного сиру з рум'яною скоринкою та м'якою текстурою всередині. Ідеально підходять для сніданку.",
        "description_en": "A traditional dish made of delicate cottage cheese with a golden crust and soft texture inside. Perfect for breakfast.",
        "description_pl": "Tradycyjne danie z delikatnego twarogu z rumianą skórką i miękkim wnętrzem. Idealne na śniadanie.",
        "source": "Шеф-кухар SoulFood Lab Андрій Коваль",
        "source_en": "Chef of SoulFood Lab Andriy Koval",
        "source_pl": "Szef kuchni SoulFood Lab Andrij Kowal",
        "cooking_time": 25,
        "portions": 3,
        "calories": 340,
        "difficulty": Difficulty.EASY,
        "cuisine": [Cuisine.UKRAINIAN],
        "meal_times": [MealTime.BREAKFAST, MealTime.SNACK],
        "dietary_tags": [Diet.VEGETARIAN],
        "dish_types": [DishType.DESSERT, DishType.FLOUR],
        "ingredients": [
            ("Кисломолочний сир", 300, UnitChoice.G),
            ("Яйця", 1, UnitChoice.PCS),
            ("Пшеничне борошно", 3, UnitChoice.TBSP),
            ("Цукор", 1, UnitChoice.TBSP),
            ("Рослинна олія", 1, UnitChoice.TBSP),
        ],
        "steps": [
            {"uk": "Помістіть кисломолочний сир у миску та розімніть його до однорідної консистенції.",
             "en": "Place cottage cheese in a bowl and mash until smooth.",
             "pl": "Włóż twaróg do miski i rozgnieć do jednolitej konsystencji."},
            {"uk": "Додайте яйце, цукор і пшеничне борошно, ретельно перемішайте до утворення однорідного тіста.",
             "en": "Add egg, sugar, and flour, mix thoroughly into a uniform dough.",
             "pl": "Dodaj jajko, cukier i mąkę, dokładnie wymieszaj."},
            {"uk": "Сформуйте з тіста невеликі сирники однакового розміру.",
             "en": "Form small, equally-sized pancakes from the dough.",
             "pl": "Uformuj małe, równej wielkości placuszki."},
            {"uk": "Розігрійте сковороду та додайте рослинну олію.", "en": "Heat a frying pan and add vegetable oil.",
             "pl": "Rozgrzej patelnię i dodaj olej roślinny."},
            {
                "uk": "Викладіть сирники на сковороду та обсмажуйте на середньому вогні до утворення золотистої скоринки з обох боків.",
                "en": "Place the pancakes in the pan and fry over medium heat until golden brown on both sides.",
                "pl": "Smaż na średnim ogniu, aż będą złociste z obu stron."}
        ]
    },
    {
        "title": "Шоколадний мус",
        "title_en": "Chocolate mousse",
        "title_pl": "Mus czekoladowy",
        "description": "Легкий і повітряний десерт із насиченим шоколадним смаком. Тане в роті та дарує справжнє задоволення — ідеальний варіант для солодкого завершення дня.",
        "description_en": "A light and airy dessert with a rich chocolate flavor. Melts in your mouth and brings true pleasure - perfect for ending the day sweetly.",
        "description_pl": "Lekki i puszysty deser o bogatym smaku czekolady. Rozpływa się w ustach - idealny na słodkie zakończenie dnia.",
        "source": "Шеф-кухар SoulFood Lab Андрій Коваль",
        "source_en": "Chef of SoulFood Lab Andriy Koval",
        "source_pl": "Szef kuchni SoulFood Lab Andrij Kowal",
        "cooking_time": 140,
        "portions": 3,
        "calories": 410,
        "difficulty": Difficulty.MEDIUM,
        "cuisine": [Cuisine.FRENCH],
        "meal_times": [MealTime.SNACK],
        "dietary_tags": [Diet.VEGETARIAN],
        "dish_types": [DishType.DESSERT],
        "ingredients": [
            ("Темний шоколад", 150, UnitChoice.G),
            ("Вершки", 200, UnitChoice.ML),
            ("Цукор", 1, UnitChoice.TBSP),
            ("Яйця", 2, UnitChoice.PCS),
        ],
        "steps": [
            {"uk": "Розтопіть темний шоколад до однорідної консистенції.",
             "en": "Melt the dark chocolate until smooth.",
             "pl": "Rozpuść gorzką czekoladę do jednolitej konsystencji."},
            {"uk": "Візьміть 2 курячих яйця та відокремте жовтки від білків.",
             "en": "Separate yolks from whites of 2 eggs.", "pl": "Oddziel żółtka od białek."},
            {"uk": "Додайте жовтки до розтопленого шоколаду та ретельно перемішайте.",
             "en": "Add yolks to the melted chocolate and mix thoroughly.",
             "pl": "Dodaj żółtka do rozpuszczonej czekolady i wymieszaj."},
            {"uk": "Збийте вершки до м’яких піків.", "en": "Whip the cream to soft peaks.",
             "pl": "Ubij śmietankę na miękkie szczyty."},
            {"uk": "Збийте білки з цукром до стійкої піни.", "en": "Whip egg whites with sugar to stiff peaks.",
             "pl": "Ubij białka z cukrem na sztywną pianę."},
            {"uk": "Змішайте шоколадну масу зі збитими вершками до однорідності, а потім змішайте збиті білки",
             "en": "Fold the chocolate mixture into the whipped cream, then fold in the egg whites.",
             "pl": "Wymieszaj masę czekoladową z ubitą śmietaną, a następnie z białkami."},
            {"uk": "Легкими рухами перемішайте масу до рівномірного стану.",
             "en": "Gently mix everything until evenly combined.",
             "pl": "Delikatnie wymieszaj, aż masa będzie jednolita."},
            {"uk": "Розподіліть масу по формах або порційних ємностях.",
             "en": "Divide the mousse among serving glasses.", "pl": "Rozlej mus do naczyń lub pucharków."},
            {"uk": "Охолодіть у холодильнику протягом 2 годин.", "en": "Chill in the refrigerator for 2 hours.",
             "pl": "Schładzaj w lodówce przez 2 godziny."}
        ]
    },
    {
        "title": "Вареники з картоплею",
        "title_en": "Varenyky with potatoes",
        "title_pl": "Pierogi z ziemniakami",
        "description": "Класична українська страва з ніжним тістом і ситною картопляною начинкою. Домашній смак і аромат роблять її ідеальним вибором для обіду.",
        "description_en": "A classic Ukrainian dish with delicate dough and a hearty potato filling. Homemade taste and aroma make it an ideal choice for lunch.",
        "description_pl": "Klasyczne ukraińskie danie (pierogi) z delikatnego ciasta i obfitego ziemniaczanego farszu. Domowy smak i aromat to idealny wybór na obiad.",
        "source": "Шеф-кухар SoulFood Lab Андрій Коваль",
        "source_en": "Chef of SoulFood Lab Andriy Koval",
        "source_pl": "Szef kuchni SoulFood Lab Andrij Kowal",
        "cooking_time": 60,
        "portions": 3,
        "calories": 450,
        "difficulty": Difficulty.MEDIUM,
        "cuisine": [Cuisine.UKRAINIAN],
        "meal_times": [MealTime.LUNCH, MealTime.DINNER],
        "dietary_tags": [Diet.TRADITIONAL],
        "dish_types": [DishType.MAIN, DishType.FLOUR],
        "ingredients": [
            ("Пшеничне борошно", 300, UnitChoice.G),
            ("Вода", 150, UnitChoice.ML),
            ("Картопля", 400, UnitChoice.G),
            ("Цибуля ріпчаста", 100, UnitChoice.G),
            ("Рослинна олія", 1, UnitChoice.TBSP),
            ("Сіль", None, UnitChoice.TASTE),
            ("Перець чорний", None, UnitChoice.TASTE),
        ],
        "steps": [
            {"uk": "Просійте пшеничне борошно, додайте воду та замісіть еластичне тісто.",
             "en": "Sift the wheat flour, add water, and knead an elastic dough.",
             "pl": "Przesiej mąkę pszenną, dodaj wodę i zagnieć elastyczne ciasto."},
            {"uk": "Очистіть картоплю та відваріть до м’якості.", "en": "Peel the potatoes and boil until tender.",
             "pl": "Obierz ziemniaki i ugotuj do miękkości."},
            {"uk": "Розімніть картоплю у пюре до однорідної консистенції.",
             "en": "Mash the potatoes into a smooth puree.", "pl": "Ziemniaki ugnieć na gładkie purée."},
            {
                "uk": "Дрібно наріжте цибулю та обсмажте її до золотистого кольору, після чого додайте до картопляного пюре.",
                "en": "Finely chop the onion and fry until golden, then add to the potato puree.",
                "pl": "Drobno posiekaj cebulę i usmaż na złoty kolor, po czym dodaj do purée ziemniaczanego."},
            {"uk": "Розкачайте тісто тонким шаром та виріжте кружечки однакового розміру.",
             "en": "Roll the dough out thinly and cut out circles of equal size.",
             "pl": "Cienko rozwałkuj ciasto i wytnij równe kółka."},
            {"uk": "Викладіть картопляну начинку на кожен кружечок та щільно зліпіть краї вареників.",
             "en": "Place potato filling on each circle and tightly pinch the edges of the dumplings.",
             "pl": "Na każde kółko nałóż nadzienie ziemniaczane i mocno zlep brzegi pierogów."},
            {"uk": "Відваріть вареники у киплячій підсоленій воді до моменту їх спливання та готовності тіста.",
             "en": "Boil the varenyky in salted boiling water until they float and the dough is cooked.",
             "pl": "Gotuj pierogi we wrzącej osolonej wodzie, aż wypłyną i ciasto będzie gotowe."},
            {"uk": "Додайте обсмажену цибулю до вареників після завершення варіння.",
             "en": "Toss the varenyky with fried onions after cooking.",
             "pl": "Po ugotowaniu wymieszaj pierogi z usmażoną cebulą."}
        ]
    },
    {
        "title": "Салат із запеченим буряком та сиром Фета",
        "title_en": "Baked beetroot and feta salad",
        "title_pl": "Sałatka z pieczonym burakiem i serem feta",
        "description": "Салат із солодким запеченим буряком, фетою та легкою лимонно-олійною заправкою. Добре підходить для обіду, вечері або поживного перекусу.",
        "description_en": "A salad with sweet baked beetroot, feta, and a light lemon-oil dressing. Perfect for lunch, dinner, or a nutritious snack.",
        "description_pl": "Sałatka ze słodkim pieczonym burakiem, fetą i lekkim sosem cytrynowo-oliwnym. Idealna na obiad, kolację lub pożywną przekąskę.",
        "source": "Євген Клопотенко",
        "source_en": "Yevhen Klopotenko",
        "source_pl": "Jewhen Klopotenko",
        "cooking_time": 100,
        "portions": 2,
        "calories": 250,
        "difficulty": Difficulty.EASY,
        "cuisine": [Cuisine.UKRAINIAN, Cuisine.AUTHOR],
        "meal_times": [MealTime.LUNCH, MealTime.DINNER, MealTime.SNACK],
        "dietary_tags": [Diet.TRADITIONAL, Diet.VEGETARIAN, Diet.GLUTEN_FREE],
        "dish_types": [DishType.SALAD, DishType.COLD_SNACK],
        "ingredients": [
            ("Буряк", 300, UnitChoice.G),
            ("Фета", 250, UnitChoice.G),
            ("Оливкова олія", 45, UnitChoice.ML),
            ("Лимонний сік", 15, UnitChoice.ML),
            ("Орегано", 3, UnitChoice.G),
            ("Сіль", 2, UnitChoice.G),
        ],
        "steps": [
            {
                "uk": "Ретельно вимийте коренеплоди буряка та герметично загорніть у харчову фольгу. Запікайте у духовій шафі при температурі 180°C протягом 1.5 годин.",
                "en": "Wash the beetroot thoroughly and wrap tightly in foil. Bake in the oven at 180°C for 1.5 hours.",
                "pl": "Dokładnie umyj buraki i zawiń szczelnie w folię. Piecz w piekarniku w 180°C przez 1,5 godziny."},
            {"uk": "Охолодіть буряк до кімнатної температури, очистіть від шкірки та наріжте кубиками.",
             "en": "Cool the beetroot to room temperature, peel, and dice.",
             "pl": "Ostudź buraki do temperatury pokojowej, obierz i pokrój w kostkę."},
            {"uk": "Наріжте сир Фета кубиками.",
             "en": "Dice the feta cheese.",
             "pl": "Pokrój ser feta w kostkę."},
            {"uk": "Сформуйте емульсію з оливкової олії, лимонного соку та розтертого сушеного орегано.",
             "en": "Make an emulsion of olive oil, lemon juice, and crushed dried oregano.",
             "pl": "Przygotuj emulsję z oliwy z oliwek, soku z cytryny i rozgniecionego suszonego oregano."},
            {
                "uk": "Викладіть буряк на тарілку, поверх нього розмістіть Фету, після чого полийте кисло-олійною емульсією.",
                "en": "Place the beetroot on a plate, top with feta, and drizzle with the sour-oil emulsion.",
                "pl": "Ułóż buraki na talerzu, na wierzchu połóż fetę, a następnie polej kwaśno-oliwną emulsją."}
        ]
    },
    {
        "title": "Грецький салат",
        "title_en": "Greek salad",
        "title_pl": "Sałatka grecka",
        "description": "Свіжий овочевий салат із фетою, оливковою олією та орегано. Легкий варіант для обіду, вечері або швидкого перекусу.",
        "description_en": "Fresh vegetable salad with feta, olive oil, and oregano. A light option for lunch, dinner, or a quick snack.",
        "description_pl": "Świeża sałatka warzywna z fetą, oliwą z oliwek i oregano. Lekka opcja na obiad, kolację lub szybką przekąskę.",
        "source": "Євген Клопотенко",
        "source_en": "Yevhen Klopotenko",
        "source_pl": "Jewhen Klopotenko",
        "cooking_time": 15,
        "portions": 2,
        "calories": 270,
        "difficulty": Difficulty.EASY,
        "cuisine": [Cuisine.MEDITERRANEAN],
        "meal_times": [MealTime.LUNCH, MealTime.DINNER, MealTime.SNACK],
        "dietary_tags": [Diet.TRADITIONAL, Diet.VEGETARIAN, Diet.GLUTEN_FREE],
        "dish_types": [DishType.SALAD, DishType.COLD_SNACK],
        "ingredients": [
            ("Помідор", 200, UnitChoice.G),
            ("Огірок", 200, UnitChoice.G),
            ("Перець болгарський", 150, UnitChoice.G),
            ("Цибуля червона", 50, UnitChoice.G),
            ("Фета", 200, UnitChoice.G),
            ("Орегано", 3, UnitChoice.G),
            ("Оливкова олія", 3, UnitChoice.TBSP),
            ("Сіль", 2, UnitChoice.G),
        ],
        "steps": [
            {"uk": "Огірки частково очистіть від шкірки паралельними смужками і наріжте великими шматками.",
             "en": "Partially peel the cucumbers in parallel strips and cut into large pieces.",
             "pl": "Częściowo obierz ogórki w równoległe paski i pokrój na duże kawałki."},
            {"uk": "Болгарський перець та помідори наріжте фракціями, співмірними з розміром огірка.",
             "en": "Cut the bell pepper and tomatoes into pieces proportional to the cucumber.",
             "pl": "Paprykę i pomidory pokrój na kawałki proporcjonalne do wielkości ogórka."},
            {"uk": "Червону цибулю наріжте тонкими півкільцями.",
             "en": "Slice the red onion into thin half-rings.",
             "pl": "Czerwoną cebulę pokrój w cienkie półplasterki."},
            {"uk": "Сир Фета сформуйте у вигляді великих кубиків (категорично уникайте дрібної нарізки).",
             "en": "Cut the feta cheese into large cubes (strictly avoid fine chopping).",
             "pl": "Ser feta pokrój w duże kostki (zdecydowanie unikaj drobnego krojenia)."},
            {
                "uk": "Об'єднайте овочі, приправте сіллю, оливковою олією та розтертим орегано. Акуратно викладіть сир зверху.",
                "en": "Combine the vegetables, season with salt, olive oil, and crushed oregano. Carefully place the cheese on top.",
                "pl": "Połącz warzywa, dopraw solą, oliwą z oliwek i rozgniecionym oregano. Ostrożnie połóż ser na wierzchu."}
        ]
    },
    {
        "title": "Салат Табуле з булгуром, томатами та сиром",
        "title_en": "Tabbouleh salad with bulgur, tomatoes and cheese",
        "title_pl": "Sałatka Tabbouleh z bulgurem, pomidorami i serem",
        "description": "Ситний салат із булгуром, помідорами, м’ятою та фетою. Має свіжий смак і добре підходить як легка основна страва або перекус.",
        "description_en": "A hearty salad with bulgur, tomatoes, mint, and feta. It has a fresh taste and is well suited as a light main course or snack.",
        "description_pl": "Sycąca sałatka z bulgurem, pomidorami, miętą i fetą. Ma świeży smak i świetnie nadaje się jako lekkie danie główne lub przekąska.",
        "source": "Євген Клопотенко",
        "source_en": "Yevhen Klopotenko",
        "source_pl": "Jewhen Klopotenko",
        "cooking_time": 40,
        "portions": 2,
        "calories": 280,
        "difficulty": Difficulty.EASY,
        "cuisine": [Cuisine.INTERNATIONAL, Cuisine.AUTHOR],
        "meal_times": [MealTime.LUNCH, MealTime.DINNER, MealTime.SNACK],
        "dietary_tags": [Diet.TRADITIONAL, Diet.VEGETARIAN],
        "dish_types": [DishType.SALAD, DishType.COLD_SNACK],
        "ingredients": [
            ("Булгур", 100, UnitChoice.G),
            ("Вода", 300, UnitChoice.ML),
            ("Помідор", 200, UnitChoice.G),
            ("Цибуля червона", 50, UnitChoice.G),
            ("М'ята", 10, UnitChoice.G),
            ("Фета", 185, UnitChoice.G),
            ("Оливкова олія", 30, UnitChoice.ML),
            ("Лимонний сік", 15, UnitChoice.ML),
            ("Сіль", 2, UnitChoice.G),
            ("Рослинна олія", 2, UnitChoice.TBSP),
        ],
        "steps": [
            {
                "uk": "Проведіть термічну гідратацію булгуру у киплячій воді до повного вбирання вологи. Під впливом температури відбувається клейстеризація крохмалю.",
                "en": "Hydrate the bulgur in boiling water until the moisture is completely absorbed. Gelatinization of starch occurs under the influence of temperature.",
                "pl": "Namocz bulgur we wrzącej wodzie, aż wilgoć zostanie całkowicie wchłonięta. Kleikowanie skrobi zachodzi pod wpływem temperatury."},
            {"uk": "Після завершення термічної обробки охолодіть булгур до кімнатної температури.",
             "en": "After cooking, cool the bulgur to room temperature.",
             "pl": "Po ugotowaniu ostudź bulgur do temperatury pokojowej."},
            {"uk": "Наріжте червону цибулю та помідори великими фракціями.",
             "en": "Cut the red onion and tomatoes into large pieces.",
             "pl": "Czerwoną cebulę i pomidory pokrój na duże kawałki."},
            {"uk": "Наріжте сир кубиками з особливою обережністю.",
             "en": "Cut the cheese into cubes with special care.",
             "pl": "Ostrożnie pokrój ser w kostkę."},
            {
                "uk": "Сформуйте емульсію з оливкової олії та лимонного соку з додаванням солі. Змішайте всі інгредієнти у глибокій посудині разом із дрібно нарізаним листям м'яти.",
                "en": "Make an emulsion of olive oil and lemon juice with the addition of salt. Mix all ingredients in a deep bowl along with finely chopped mint leaves.",
                "pl": "Przygotuj emulsję z oliwy z oliwek i soku z cytryny z dodatkiem soli. Wymieszaj wszystkie składniki w głębokiej misce z drobno posiekanymi liśćmi mięty."}
        ]
    },
    {
        "title": "Смажені кабачкові оладки",
        "title_en": "Fried zucchini fritters",
        "title_pl": "Smażone placuszki z cukinii",
        "description": "Літні оладки з кабачка, зелені та ніжного тіста. Швидкий варіант для сніданку або легкого перекусу.",
        "description_en": "Summer zucchini fritters with greens and tender dough. A quick option for breakfast or a light snack.",
        "description_pl": "Letnie placuszki z cukinii, zieleni i delikatnego ciasta. Szybka opcja na śniadanie lub lekką przekąskę.",
        "source": "Євген Клопотенко",
        "source_en": "Yevhen Klopotenko",
        "source_pl": "Jewhen Klopotenko",
        "cooking_time": 15,
        "portions": 2,
        "calories": 220,
        "difficulty": Difficulty.EASY,
        "cuisine": [Cuisine.UKRAINIAN],
        "meal_times": [MealTime.BREAKFAST, MealTime.SNACK],
        "dietary_tags": [Diet.TRADITIONAL, Diet.VEGETARIAN],
        "dish_types": [DishType.HOT_SNACK, DishType.FLOUR],
        "ingredients": [
            ("Кабачок", 500, UnitChoice.G),
            ("Яйця", 2, UnitChoice.PCS),
            ("Сметана", 30, UnitChoice.G),
            ("Пшеничне борошно", 80, UnitChoice.G),
            ("Кріп", 10, UnitChoice.G),
            ("Рослинна олія", 45, UnitChoice.ML),
            ("Сіль", 3, UnitChoice.G),
            ("Перець чорний", 1, UnitChoice.G),
        ],
        "steps": [
            {
                "uk": "Натріть кабачок на крупній тертці. Обов'язково відіжміть овоч від зайвого соку, щоб тісто не стало занадто водянистим під час смаження.",
                "en": "Grate the zucchini on a coarse grater. Be sure to squeeze the excess juice from the vegetable so the dough doesn't become too watery during frying.",
                "pl": "Zetrzyj cukinię na grubej tarce. Pamiętaj, aby wycisnąć nadmiar soku z warzywa, aby ciasto nie stało się zbyt wodniste podczas smażenia."},
            {
                "uk": "Додайте до віджатого кабачка сіль, перець, яйця, пшеничне борошно, сметану та дрібно нарізаний кріп.",
                "en": "Add salt, pepper, eggs, wheat flour, sour cream, and finely chopped dill to the squeezed zucchini.",
                "pl": "Do odciśniętej cukinii dodaj sól, pieprz, jajka, mąkę pszenną, śmietanę i drobno posiekany koperek."},
            {"uk": "Ретельно перемішайте масу до утворення однорідного тіста середньої густоти.",
             "en": "Mix the mass thoroughly to form a smooth dough of medium thickness.",
             "pl": "Dokładnie wymieszaj masę, aż powstanie jednolite ciasto o średniej gęstoości."},
            {
                "uk": "Викладайте масу столовою ложкою на розігріту з олією сковороду, злегка притискаючи для формування оладок.",
                "en": "Spoon the mixture onto a hot pan with oil, pressing lightly to form fritters.",
                "pl": "Wykładaj masę łyżką na rozgrzaną patelnię z olejem, lekko dociskając, by uformować placki."},
            {"uk": "Смажте з обох боків до утворення стійкої золотистої скоринки (реакція Майяра).",
             "en": "Fry on both sides until a firm golden crust forms (Maillard reaction).",
             "pl": "Smaż z obu stron, aż powstanie złocista skórka (reakcja Maillarda)."}
        ]
    },
    {
        "title": "Спагеті з томатами та базиліком",
        "title_en": "Spaghetti with tomatoes and basil",
        "title_pl": "Spaghetti z pomidorami i bazylią",
        "description": "Проста паста з томатним соусом, базиліком і твердим сиром. Підійде для швидкого обіду або вечері без складних інгредієнтів.",
        "description_en": "Simple pasta with tomato sauce, basil, and hard cheese. Suitable for a quick lunch or dinner without complex ingredients.",
        "description_pl": "Prosty makaron z sosem pomidorowym, bazylią i twardym serem. Nadaje się na szybki obiad lub kolację bez skomplikowanych składników.",
        "source": "Джеймі Олівер",
        "source_en": "Jamie Oliver",
        "source_pl": "Jamiego Olivera",
        "cooking_time": 30,
        "portions": 4,
        "calories": 316,
        "difficulty": Difficulty.EASY,
        "cuisine": [Cuisine.ITALIAN, Cuisine.BRITISH],
        "meal_times": [MealTime.LUNCH, MealTime.DINNER],
        "dietary_tags": [Diet.TRADITIONAL, Diet.VEGETARIAN],
        "dish_types": [DishType.PASTA, DishType.MAIN],
        "ingredients": [
            ("Паста", 240, UnitChoice.G),
            ("Помідор", 1500, UnitChoice.G),
            ("Цибуля ріпчаста", 50, UnitChoice.G),
            ("Часник", 5, UnitChoice.G),
            ("Базилік", 15, UnitChoice.G),
            ("Оливкова олія", 15, UnitChoice.ML),
            ("Пармезан", 10, UnitChoice.G),
            ("Сіль", 2, UnitChoice.G),
            ("Перець чорний", 1, UnitChoice.G),
        ],
        "steps": [
            {"uk": "Відокремте листя базиліка від стебел. Листя відкладіть, а стебла, цибулю та часник дрібно наріжте.",
             "en": "Separate the basil leaves from the stems. Set the leaves aside, and finely chop the stems, onion, and garlic.",
             "pl": "Oddziel liście bazylii od łodyg. Odłóż liście na bok, a łodygi, cebulę i czosnek drobno posiekaj."},
            {
                "uk": "Розігрійте оливкову олію на середньому вогні. Додайте цибулю, часник та стебла базиліка. Пасеруйте до розм'якшення (близько 5-7 хвилин).",
                "en": "Heat olive oil over medium heat. Add the onion, garlic, and basil stems. Sauté until softened (about 5-7 minutes).",
                "pl": "Rozgrzej oliwę na średnim ogniu. Dodaj cebulę, czosnek i łodygi bazylii. Smaż do miękkości (około 5-7 minut)."},
            {
                "uk": "Додайте подрібнені помідори. Приправте сіллю та перцем. Зменште вогонь і тушкуйте соус близько 15 хвилин до загустіння. Наприкінці додайте подрібнене листя базиліка.",
                "en": "Add the chopped tomatoes. Season with salt and pepper. Reduce the heat and simmer the sauce for about 15 minutes until thickened. Finally, add the chopped basil leaves.",
                "pl": "Dodaj posiekane pomidory. Dopraw solą i pieprzem. Zmniejsz ogień i duś sos przez około 15 minut, aż zgęstnieje. Na koniec dodaj posiekane liście bazylii."},
            {
                "uk": "Паралельно відваріть пасту у великій кількості підсоленої води до стану al dente. Збережіть трохи крохмалистої води.",
                "en": "Meanwhile, boil the pasta in plenty of salted water until al dente. Reserve some of the starchy water.",
                "pl": "W międzyczasie ugotuj makaron w dużej ilości osolonej wody al dente. Zachowaj trochę wody z gotowania."},
            {
                "uk": "Змішайте відварену пасту з томатним соусом, за необхідності додавши воду від варіння для кращої емульсії. Подавайте з натертим твердим сиром.",
                "en": "Mix the cooked pasta with the tomato sauce, adding pasta water if necessary for a better emulsion. Serve with grated hard cheese.",
                "pl": "Wymieszaj ugotowany makaron z sosem pomidorowym, dodając w razie potrzeby wodę z gotowania, aby uzyskać lepszą emulsję. Podawaj ze startym twardym serem."}
        ]
    },
    {
        "title": "Паста з куркою, томатами та беконом",
        "title_en": "Pasta with chicken, tomatoes, and bacon",
        "title_pl": "Makaron z kurczakiem, pomidorami i boczkiem",
        "description": "Ситна паста з курячим філе, беконом, томатами та базиліком. Це зручна основна страва для обіду або вечері.",
        "description_en": "A hearty pasta with chicken fillet, bacon, tomatoes, and basil. It is a convenient main dish for lunch or dinner.",
        "description_pl": "Sycący makaron z filetem z kurczaka, boczkiem, pomidorami i bazylią. To wygodne danie główne na obiad lub kolację.",
        "source": "Nom Nom Nelly",
        "source_en": "Nom Nom Nelly",
        "source_pl": "Nom Nom Nelly",
        "cooking_time": 30,
        "portions": 2,
        "calories": 480,
        "difficulty": Difficulty.EASY,
        "cuisine": [Cuisine.EUROPEAN],
        "meal_times": [MealTime.LUNCH, MealTime.DINNER],
        "dietary_tags": [Diet.TRADITIONAL, Diet.MEAT],
        "dish_types": [DishType.PASTA, DishType.MAIN, DishType.MEAT],
        "ingredients": [
            ("Паста", 280, UnitChoice.G),
            ("Куряче філе", 300, UnitChoice.G),
            ("Бекон", 80, UnitChoice.G),
            ("Помідор", 300, UnitChoice.G),
            ("Цибуля ріпчаста", 180, UnitChoice.G),
            ("Часник", 10, UnitChoice.G),
            ("Базилік", 15, UnitChoice.G),
            ("Бульйон", 150, UnitChoice.ML),
            ("Пармезан", 30, UnitChoice.G),
            ("Сіль", 2, UnitChoice.G),
        ],
        "steps": [
            {
                "uk": "Запечіть куряче філе в духовці (200°C) близько 20 хвилин до готовності, або обсмажте. Наріжте невеликими шматочками. Окремо підсмажте бекон до хрускоту.",
                "en": "Bake the chicken fillet in the oven (200°C) for about 20 minutes until done, or fry. Cut into small pieces. Separately, fry the bacon until crispy.",
                "pl": "Upiecz filet z kurczaka w piekarniku (200°C) przez około 20 minut do miękkości, lub usmaż. Pokrój na małe kawałki. Osobno usmaż boczek na chrupko."},
            {"uk": "Відваріть пасту за інструкцією до готовності, злийте воду.",
             "en": "Boil the pasta according to instructions until done, drain the water.",
             "pl": "Ugotuj makaron zgodnie z instrukcją, odcedź wodę."},
            {
                "uk": "На антипригарній сковороді розм'якшіть нарізану цибулю. Додайте подрібнений часник та нарізані помідори (без насіння), смажте 1 хвилину.",
                "en": "Soften the chopped onion in a non-stick pan. Add minced garlic and chopped tomatoes (seeded), fry for 1 minute.",
                "pl": "Zeszklij posiekaną cebulę na patelni z powłoką nieprzywierającą. Dodaj posiekany czosnek i pokrojone pomidory (bez pestek), smaż przez 1 minutę."},
            {
                "uk": "Влийте бульйон, додайте курку і ретельно перемішайте, дозволяючи соусу трохи уваритися та сконцентрувати смаки.",
                "en": "Pour in the broth, add the chicken, and mix thoroughly, allowing the sauce to reduce slightly and concentrate the flavors.",
                "pl": "Wlej bulion, dodaj kurczaka i dokładnie wymieszaj, pozwalając sosowi nieco odparować i skoncentrować smaki."},
            {"uk": "Змішайте соус з пастою, беконом та базиліком. Подавайте, щедро посипавши натертим сиром.",
             "en": "Mix the sauce with pasta, bacon, and basil. Serve generously sprinkled with grated cheese.",
             "pl": "Wymieszaj sos z makaronem, boczkiem i bazylią. Podawaj obficie posypane startym serem."}
        ]
    },
    {
        "title": "Креветки з часником (Gambas al ajillo)",
        "title_en": "Garlic shrimp (Gambas al ajillo)",
        "title_pl": "Krewetki z czosnkiem (Gambas al ajillo)",
        "description": "Швидка гаряча закуска з креветками, часником, чилі та зеленню. Має насичений аромат і готується всього за кілька хвилин.",
        "description_en": "A quick hot appetizer with shrimp, garlic, chili, and herbs. It has a rich aroma and cooks in just a few minutes.",
        "description_pl": "Szybka gorąca przekąska z krewetkami, czosnkiem, chili i ziołami. Ma bogaty aromat i jest gotowa w zaledwie kilka minut.",
        "source": "Omar Allibhoy",
        "source_en": "Omar Allibhoy",
        "source_pl": "Omar Allibhoy",
        "cooking_time": 10,
        "portions": 2,
        "calories": 342,
        "difficulty": Difficulty.EASY,
        "cuisine": [Cuisine.MEDITERRANEAN],
        "meal_times": [MealTime.LUNCH, MealTime.DINNER, MealTime.SNACK],
        "dietary_tags": [Diet.TRADITIONAL, Diet.SEAFOOD_DIET, Diet.GLUTEN_FREE],
        "dish_types": [DishType.HOT_SNACK, DishType.SEAFOOD],
        "ingredients": [
            ("Креветки очищені", 200, UnitChoice.G),
            ("Часник", 15, UnitChoice.G),
            ("Оливкова олія", 100, UnitChoice.ML),
            ("Перець чилі", 2, UnitChoice.G),
            ("Петрушка", 10, UnitChoice.G),
            ("Сіль", 2, UnitChoice.G),
            ("Перець чорний", 1, UnitChoice.G),
        ],
        "steps": [
            {"uk": "Очищені креветки злегка приправте кристалічною сіллю.",
             "en": "Lightly season peeled shrimp with crystal salt.",
             "pl": "Obrane krewetki lekko dopraw grubą solą."},
            {
                "uk": "У сковороду налийте оливкову олію, додайте тонко нарізаний часник та подрібнений перець чилі. Поставте на сильний вогонь.",
                "en": "Pour olive oil into a pan, add thinly sliced garlic and minced chili pepper. Place over high heat.",
                "pl": "Na patelnię wlej oliwę z oliwek, dodaj cienko pokrojony czosnek i posiekaną papryczkę chili. Postaw na silnym ogniu."},
            {
                "uk": "Уважно стежте за часником: як тільки він почне набувати золотистого відтінку (відбувається реакція карамелізації), олія готова.",
                "en": "Watch the garlic carefully: as soon as it begins to take on a golden hue (caramelization reaction), the oil is ready.",
                "pl": "Uważnie obserwuj czosnek: gdy tylko zacznie nabierać złotego odcienia (reakcja karmelizacji), olej jest gotowy."},
            {
                "uk": "Одразу додайте креветки в гарячу ароматизовану олію. Готуйте по 1-2 хвилини з кожного боку, поки вони не стануть рожевими і непрозорими.",
                "en": "Immediately add the shrimp to the hot flavored oil. Cook for 1-2 minutes per side until pink and opaque.",
                "pl": "Natychmiast dodaj krewetki do gorącej aromatyzowanej oliwy. Gotuj 1-2 minuty z każdej strony, aż staną się różowe i nieprzezroczyste."},
            {
                "uk": "Зніміть з вогню, посипте свіжою подрібненою петрушкою та чорним перцем. Подавайте негайно (ідеально з хлібом для вмочування в олію).",
                "en": "Remove from heat, sprinkle with freshly chopped parsley and black pepper. Serve immediately (ideally with bread for dipping in the oil).",
                "pl": "Zdejmij z ognia, posyp świeżo posiekaną natką pietruszki i czarnym pieprzem. Podawaj natychmiast (idealnie z chlebem do maczania w oliwie)."}
        ]
    }
]