# Generated by Django 5.2.11 on 2026-03-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Улюблений рецепт',
                'verbose_name_plural': 'Улюблені рецепти',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Назва інгредієнта')),
                ('is_seasonal', models.BooleanField(default=False, verbose_name='Сезонний продукт')),
                ('is_local', models.BooleanField(default=False, verbose_name='Локальний продукт')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ingredients/images/', verbose_name='Фото інгредієнта')),
                ('seasonal_months', models.JSONField(blank=True, default=list, verbose_name='Сезонні місяці (1-12)')),
            ],
            options={
                'verbose_name': 'Інгредієнт',
                'verbose_name_plural': 'Інгредієнти',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва рецепта')),
                ('description', models.TextField(verbose_name='Опис')),
                ('cooking_time', models.PositiveIntegerField(verbose_name='Час приготування (хв)')),
                ('calories', models.PositiveIntegerField(blank=True, null=True, verbose_name='Калорії')),
                ('instructions', models.TextField(verbose_name='Покрокове приготування')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/images/', verbose_name='Фото рецепта')),
                ('dietary_tags', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дієтичні теги')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепти',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Наприклад: 200, 1.5', max_digits=6, verbose_name='Кількість')),
                ('unit', models.CharField(help_text='Наприклад: грам, шт, мл, ст. л.', max_length=50, verbose_name='Одиниця виміру')),
            ],
            options={
                'verbose_name': 'Інгредієнт у рецепті',
                'verbose_name_plural': 'Інгредієнти у рецептах',
            },
        ),
        migrations.CreateModel(
            name='WeeklyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Понеділок'), (2, 'Вівторок'), (3, 'Середа'), (4, 'Четвер'), (5, "П'ятниця"), (6, 'Субота'), (7, 'Неділя')], verbose_name='День тижня')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Сніданок'), ('lunch', 'Обід'), ('dinner', 'Вечеря')], max_length=20, verbose_name='Прийом їжі')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Тижневе меню',
            },
        ),
    ]
