# Generated by Django 5.2.11 on 2026-03-24 21:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Улюблений рецепт',
                'verbose_name_plural': 'Улюблені рецепти',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Назва інгредієнта')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ingredients/images/', verbose_name='Фото інгредієнта')),
                ('category', models.CharField(choices=[('cheese', 'Сири'), ('mushrooms', 'Гриби'), ('fruits', 'Фрукти, ягоди та цитрусові'), ('vegetables', 'Овочі та коренеплоди'), ('greens', 'Зелень та трави'), ('meat_beef', "М'ясо та птиця / Яловичина і телятина"), ('meat_pork', "М'ясо та птиця / Свинина"), ('meat_bird', "М'ясо та птиця / Птиця"), ('meat_other', "М'ясо та птиця / Інше м'ясо"), ('meat_products', "М'ясо та птиця / М'ясні вироби"), ('fish_red', 'Риба та морепродукти / Червона риба'), ('fish_white', 'Риба та морепродукти / Біла риба'), ('seafood', 'Риба та морепродукти / Морепродукти'), ('alt_protein', 'Альтернативні білки'), ('flour', 'Борошно'), ('grains', 'Крупи та бобові'), ('nuts', 'Горіхи та насіння'), ('dairy', 'Молочні продукти та яйця'), ('sweets', 'Кондитерські інгредієнти')], max_length=50, verbose_name='Категорія')),
                ('is_seasonal', models.BooleanField(default=False, verbose_name='Сезонний інгредієнт')),
                ('seasonal_months', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'Січень'), (2, 'Лютий'), (3, 'Березень'), (4, 'Квітень'), (5, 'Травень'), (6, 'Червень'), (7, 'Липень'), (8, 'Серпень'), (9, 'Вересень'), (10, 'Жовтень'), (11, 'Листопад'), (12, 'Грудень')]), blank=True, null=True, size=None, verbose_name='Місяці сезонності')),
            ],
            options={
                'verbose_name': 'Інгредієнт',
                'verbose_name_plural': 'Інгредієнти',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва рецепта')),
                ('description', models.TextField(verbose_name='Опис')),
                ('image', models.ImageField(upload_to='recipes/images/', verbose_name='Фото рецепта')),
                ('cooking_time', models.PositiveIntegerField(verbose_name='Час приготування (хв)')),
                ('portions', models.PositiveIntegerField(default=1, verbose_name='Кількість порцій')),
                ('calories', models.PositiveIntegerField(verbose_name='Калорії на 1 порцію')),
                ('difficulty', models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Середній'), ('hard', 'Важкий')], max_length=20, verbose_name='Складність')),
                ('is_seasonal', models.BooleanField(default=False, verbose_name='Сезонний рецепт')),
                ('seasonal_months', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'Січень'), (2, 'Лютий'), (3, 'Березень'), (4, 'Квітень'), (5, 'Травень'), (6, 'Червень'), (7, 'Липень'), (8, 'Серпень'), (9, 'Вересень'), (10, 'Жовтень'), (11, 'Листопад'), (12, 'Грудень')]), blank=True, null=True, size=None, verbose_name='Сезонні місяці')),
                ('cuisine', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('eu', '🇪🇺 Європейська кухня'), ('mediterranean', '🌊 Середземноморська кухня'), ('it', '🇮🇹 Італійська кухня'), ('mx', '🇲🇽 Мексиканська кухня'), ('intl', '🌍 Міжнародна кухня'), ('ua', '🇺🇦 Українська кухня'), ('fr', '🇫🇷 Французька кухня'), ('us', '🇺🇸 Американська кухня'), ('cn', '🇨🇳 Китайська кухня'), ('jp', '🇯🇵 Японська кухня')], max_length=50), blank=True, null=True, size=None, verbose_name='Кухня')),
                ('meal_times', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('breakfast', 'Сніданок'), ('lunch', 'Обід'), ('dinner', 'Вечеря'), ('snack', 'Перекус')], max_length=20), blank=True, null=True, size=None, verbose_name='Прийом їжі')),
                ('dietary_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('traditional', 'Традиційне (без жодних обмежень)'), ('vegetarian', 'Вегетаріанське'), ('vegan', 'Веганське'), ('pescatarian', 'Пескетаріанське'), ('gluten_free', 'Безглютенове'), ('lactose_free', 'Безлактозне'), ('sugar_free', 'Без цукру'), ('keto', 'Кето (Кетогенне)'), ('low_carb', 'Низьковуглеводне'), ('paleo', 'Палеодієта'), ('raw', 'Сироїдіння'), ('halal', 'Халяль'), ('kosher', 'Кошерне'), ('fasting', 'Пісне меню'), ('dietary', 'Дієтичне')], max_length=30), blank=True, null=True, size=None, verbose_name='Тип харчування / Дієта')),
                ('dish_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('first', 'Перші страви'), ('main', 'Основні страви (Другі страви)'), ('garnish', 'Гарніри'), ('salad', 'Салати'), ('snack', 'Закуски'), ('dessert', 'Десерти'), ('drink', 'Напої'), ('sauce', 'Соуси та заправки'), ('soup', 'Супи'), ('pasta', 'Пасти'), ('smoothie', 'Смузі'), ('porridge', 'Каші'), ('omelet', 'Омлет / Яєчна страва')], max_length=30), blank=True, null=True, size=None, verbose_name='Типи страв')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепти',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Кількість')),
                ('unit', models.CharField(choices=[('g', 'Грам (г)'), ('kg', 'Кілограм (кг)'), ('ml', 'Мілілітр (мл)'), ('l', 'Літр (л)'), ('tsp', 'Чайна ложка (ч. л.)'), ('tbsp', 'Столова ложка (ст. л.)'), ('glass', 'Склянка (скл.)'), ('pcs', 'Штука (шт.)'), ('pack', 'Упаковка / Пачка (уп.)'), ('can', 'Банка'), ('leaf', 'Лист'), ('clove', 'Зубчик'), ('pinch', 'Дрібка'), ('bunch', 'Пучок'), ('sprig', 'Гілочка'), ('stalk', 'Стебло'), ('drop', 'Крапля'), ('cm', 'Сантиметр (см)'), ('taste', 'За смаком'), ('garnish', 'Для подачі / прикраси')], default='g', max_length=20, verbose_name='Одиниця виміру')),
            ],
            options={
                'verbose_name': 'Інгредієнт в рецепті',
                'verbose_name_plural': 'Інгредієнти в рецепті',
            },
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(verbose_name='Номер кроку')),
                ('text', models.TextField(verbose_name='Опис кроку')),
            ],
            options={
                'verbose_name': 'Крок приготування',
                'verbose_name_plural': 'Покрокове приготування',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Понеділок'), (2, 'Вівторок'), (3, 'Середа'), (4, 'Четвер'), (5, "П'ятниця"), (6, 'Субота'), (7, 'Неділя')], verbose_name='День тижня')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Сніданок'), ('lunch', 'Обід'), ('dinner', 'Вечеря')], max_length=20, verbose_name='Прийом їжі')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Тижневе меню',
            },
        ),
    ]
