# Generated by Django 5.2.11 on 2026-03-24 21:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cuisine',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('eu', '🇪🇺 Європейська кухня'), ('mediterranean', '🌊 Середземноморська кухня'), ('it', '🇮🇹 Італійська кухня'), ('mx', '🇲🇽 Мексиканська кухня'), ('intl', '🌍 Міжнародна кухня'), ('ua', '🇺🇦 Українська кухня'), ('fr', '🇫🇷 Французька кухня'), ('us', '🇺🇸 Американська кухня'), ('cn', '🇨🇳 Китайська кухня'), ('jp', '🇯🇵 Японська кухня')], max_length=50), blank=True, default=list, size=None, verbose_name='Кухня'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='dietary_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('traditional', 'Традиційне (без жодних обмежень)'), ('vegetarian', 'Вегетаріанське'), ('vegan', 'Веганське'), ('pescatarian', 'Пескетаріанське'), ('gluten_free', 'Безглютенове'), ('lactose_free', 'Безлактозне'), ('sugar_free', 'Без цукру'), ('keto', 'Кето (Кетогенне)'), ('low_carb', 'Низьковуглеводне'), ('paleo', 'Палеодієта'), ('raw', 'Сироїдіння'), ('halal', 'Халяль'), ('kosher', 'Кошерне'), ('fasting', 'Пісне меню'), ('dietary', 'Дієтичне')], max_length=30), blank=True, default=list, size=None, verbose_name='Тип харчування / Дієта'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='dish_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('first', 'Перші страви'), ('main', 'Основні страви (Другі страви)'), ('garnish', 'Гарніри'), ('salad', 'Салати'), ('snack', 'Закуски'), ('dessert', 'Десерти'), ('drink', 'Напої'), ('sauce', 'Соуси та заправки'), ('soup', 'Супи'), ('pasta', 'Пасти'), ('smoothie', 'Смузі'), ('porridge', 'Каші'), ('omelet', 'Омлет / Яєчна страва')], max_length=30), blank=True, default=list, size=None, verbose_name='Типи страв'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='meal_times',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('breakfast', 'Сніданок'), ('lunch', 'Обід'), ('dinner', 'Вечеря'), ('snack', 'Перекус')], max_length=20), blank=True, default=list, size=None, verbose_name='Прийом їжі'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='seasonal_months',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'Січень'), (2, 'Лютий'), (3, 'Березень'), (4, 'Квітень'), (5, 'Травень'), (6, 'Червень'), (7, 'Липень'), (8, 'Серпень'), (9, 'Вересень'), (10, 'Жовтень'), (11, 'Листопад'), (12, 'Грудень')]), blank=True, default=list, size=None, verbose_name='Сезонні місяці'),
        ),
    ]
