# Generated by Django 5.2.11 on 2026-03-07 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='is_local',
        ),
    ]
