# Generated by Django 5.2.11 on 2026-03-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_cuisine_alter_recipe_dietary_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('cheese', 'Сири'), ('mushrooms', 'Гриби'), ('fruits', 'Фрукти, ягоди та цитрусові'), ('vegetables', 'Овочі та коренеплоди'), ('greens', 'Зелень та трави'), ('meat_beef', "М'ясо та птиця / Яловичина і телятина"), ('meat_pork', "М'ясо та птиця / Свинина"), ('meat_bird', "М'ясо та птиця / Птиця"), ('meat_other', "М'ясо та птиця / Інше м'ясо"), ('meat_products', "М'ясо та птиця / М'ясні вироби"), ('fish_red', 'Риба та морепродукти / Червона риба'), ('fish_white', 'Риба та морепродукти / Біла риба'), ('seafood', 'Риба та морепродукти / Морепродукти'), ('alt_protein', 'Альтернативні білки'), ('flour', 'Борошно'), ('grains', 'Крупи та бобові'), ('nuts', 'Горіхи та насіння'), ('dairy', 'Молочні продукти та яйця'), ('sweets', 'Кондитерські інгредієнти'), ('spices', 'Спеції та приправи'), ('oils_liquids', 'Спеції та приправи / Олії та рідини')], max_length=50, verbose_name='Категорія'),
        ),
    ]
