# Generated by Django 5.2.11 on 2026-03-28 10:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_ingredient_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='dietary_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('traditional', 'Традиційний (без обмежень)'), ('vegetarian', 'Вегетаріанський'), ('vegan', 'Веганський'), ('dietary', 'Дієтичний'), ('gluten_free', 'Безглютеновий'), ('lactose_free', 'Безлактозний'), ('sugar_free', 'Без цукру')], max_length=30), blank=True, default=list, size=None, verbose_name='Тип харчування / Дієта'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='dish_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('first', 'Перша страва'), ('main', 'Основна страва'), ('garnish', 'Гарнір'), ('salad', 'Салат'), ('snack', 'Закуска'), ('dessert', 'Десерт'), ('drink', 'Напій'), ('sauce', 'Соус'), ('soup', 'Суп'), ('pasta', 'Паста'), ('smoothie', 'Смузі'), ('porridge', 'Каша'), ('omelet', 'Омлет / Яєчна страва'), ('flour', 'Борошняна страва'), ('meat', 'М’ясна страва'), ('fish', 'Рибна страва'), ('seafood', 'Морепродукти')], max_length=30), blank=True, default=list, size=None, verbose_name='Типи страв'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'Грам (г)'), ('kg', 'Кілограм (кг)'), ('ml', 'Мілілітр (мл)'), ('l', 'Літр (л)'), ('tsp', 'Чайна ложка (ч. л.)'), ('tbsp', 'Столова ложка (ст. л.)'), ('glass', 'Склянка (скл.)'), ('pcs', 'Штука (шт.)'), ('pack', 'Упаковка / Пачка (уп.)'), ('can', 'Банка'), ('leaf', 'Лист'), ('clove', 'Зубчик'), ('pinch', 'Дрібка'), ('bunch', 'Пучок'), ('sprig', 'Гілочка'), ('stalk', 'Стебло'), ('drop', 'Крапля'), ('cm', 'Сантиметр (см)'), ('taste', 'За смаком'), ('garnish', 'Для подачі / прикраси'), ('frying', 'Для смаження')], default='g', max_length=20, verbose_name='Одиниця виміру'),
        ),
    ]
