# Generated by Django 5.2.11 on 2026-03-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_cuisine_alter_recipeingredient_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='source',
            field=models.CharField(blank=True, help_text='Вкажіть автора, ресторан або додайте посилання (URL) на оригінал', max_length=500, null=True, verbose_name='Джерело рецепту'),
        ),
    ]
