# Generated by Django 5.2.11 on 2026-03-28 23:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weeklymenu',
            unique_together={('user', 'recipe', 'day_of_week', 'meal_type')},
        ),
    ]
