# Generated by Django 5.2.11 on 2026-04-05 08:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_weeklymenu_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeOfDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, unique=True, verbose_name='Дата')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Рецепт дня',
                'verbose_name_plural': 'Рецепти дня',
            },
        ),
    ]
