# Generated by Django 5.2.11 on 2026-04-25 10:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_recipe_cuisine_alter_recipe_dietary_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='name_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Назва (EN)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='name_pl',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Назва (PL)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Опис (EN)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='description_pl',
            field=models.TextField(blank=True, null=True, verbose_name='Опис (PL)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Назва (EN)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='title_pl',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Назва (PL)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cuisine',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('eu', '🇪🇺 Європейська кухня'), ('mediterranean', '🌊 Середземноморська кухня'), ('it', '🇮🇹 Італійська кухня'), ('mx', '🇲🇽 Мексиканська кухня'), ('intl', '🌍 Міжнародна кухня'), ('ua', '🇺🇦 Українська кухня'), ('fr', '🇫🇷 Французька кухня'), ('us', '🇺🇸 Американська кухня'), ('cn', '🇨🇳 Китайська кухня'), ('jp', '🇯🇵 Японська кухня'), ('asian', '🥢 Азійська кухня'), ('gb', '🇬🇧 Британська кухня'), ('author', '👨\u200d🍳 Авторська кухня'), ('in', '🇮🇳 Індійська кухня')], max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='dietary_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('traditional', 'Традиційний (без обмежень)'), ('vegetarian', 'Вегетаріанський'), ('vegan', 'Веганський'), ('dietary', 'Дієтичний'), ('gluten_free', 'Безглютеновий'), ('lactose_free', 'Безлактозний'), ('sugar_free', 'Без цукру'), ('high_protein', 'Високобілковий'), ('meat_diet', 'М’ясний'), ('seafood_diet', 'Морський (Морепродукти)')], max_length=30), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='dish_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('first', 'Перша страва'), ('main', 'Основна страва'), ('garnish', 'Гарнір'), ('salad', 'Салат'), ('snack', 'Закуска'), ('dessert', 'Десерт'), ('drink', 'Напій'), ('sauce', 'Соус'), ('soup', 'Суп'), ('pasta', 'Паста'), ('smoothie', 'Смузі'), ('porridge', 'Каша'), ('omelet', 'Омлет / Яєчна страва'), ('flour', 'Борошняна страва'), ('meat', 'М’ясна страва'), ('fish', 'Рибна страва'), ('seafood', 'Морепродукти'), ('cold_snack', 'Холодна закуска'), ('hot_snack', 'Гаряча закуска'), ('festive', 'Святкова страва'), ('aspic', 'Заливне'), ('stew', 'Рагу / тушкована страва')], max_length=30), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='meal_times',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('breakfast', 'Сніданок'), ('lunch', 'Обід'), ('dinner', 'Вечеря'), ('snack', 'Перекус')], max_length=20), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='seasonal_months',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'Січень'), (2, 'Лютий'), (3, 'Березень'), (4, 'Квітень'), (5, 'Травень'), (6, 'Червень'), (7, 'Липень'), (8, 'Серпень'), (9, 'Вересень'), (10, 'Жовтень'), (11, 'Листопад'), (12, 'Грудень')]), blank=True, default=list, size=None),
        ),
    ]
