# Generated by Django 5.2.11 on 2026-04-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_ingredient_name_en_ingredient_name_pl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipestep',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Опис кроку (EN)'),
        ),
        migrations.AddField(
            model_name='recipestep',
            name='text_pl',
            field=models.TextField(blank=True, null=True, verbose_name='Опис кроку (PL)'),
        ),
    ]
