# Generated by Django 5.2.11 on 2026-04-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_recipestep_text_en_recipestep_text_pl'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='source_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Джерело (EN)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='source_pl',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Джерело (PL)'),
        ),
    ]
