# Generated by Django 5.2.11 on 2026-05-03 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_recipe_source_en_recipe_source_pl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriterecipe',
            options={'verbose_name': 'Favorite Recipe (Улюблений рецепт)', 'verbose_name_plural': 'Favorite Recipes (Улюблені рецепти)'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name'], 'verbose_name': 'Ingredient (Інгредієнт)', 'verbose_name_plural': 'Ingredients (Інгредієнти)'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created_at'], 'verbose_name': 'Recipe (Рецепт)', 'verbose_name_plural': 'Recipes (Рецепти)'},
        ),
        migrations.AlterModelOptions(
            name='recipeofday',
            options={'verbose_name': 'Recipe of the Day (Рецепт дня)', 'verbose_name_plural': 'Recipes of the Day (Рецепти дня)'},
        ),
        migrations.AlterModelOptions(
            name='weeklymenu',
            options={'verbose_name': 'Weekly Menu (Тижневе меню)', 'verbose_name_plural': 'Weekly Menus (Тижневі меню)'},
        ),
    ]
